= Blurry preview when using JavaFX
:navtitle: JavaFX blurry preview
:description: When the characters in the preview look blurry, while the editor shows sharp characters.

{description}

== Symptom

When the preview of the AsciiDoc Plugin (usually on the right) is blurry: While the characters in the editor on the left look sharp, the characters in the preview on the right look blurry.

The following JetBrains ticket contains examples: https://youtrack.jetbrains.com/issue/IDEA-213110[IDEA-213110]

== Environment

This only happens when using the JavaFX preview.
The current combinations seems to be:

* Operating System Windows 10, +
JavaFX preview +
a high-resolution display with a fractional scaling (for example 125% or 175%), +
IntelliJ running on OpenJDK 8 / JetBrains Runtime 8

or

* Operating System Linux (for example Fedora 31 Wayland), +
JavaFX preview +
a high-resolution display with scaling-factor 200% or more, +
IntelliJ running on OpenJDK or JetBrains Runtime (any version)

== How do I fix this?

Upgrade to IntelliJ 2020.3 which bundles JDK 11 as its runtime, and used the JCEF preview.

[#change_jcef]
=== Change to JCEF preview

This JCEF preview embeds a Chromium based browser in the IDE.
As it supports high-resolution displays and is the preview technology recommended by JetBrains, follow the instructions in the chapter '`xref:features/preview/jcef-preview.adoc[]`' to activate it.

== Help, preview is still blurry!

To have the maintainers investigate the issue, open a https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[GitHub issue].
