= Error Message Errno ENOENT and no preview
:navtitle: Error Message ENOENT
:description: Problems with folder names with non-US-ASCII characters. See below for the remedy.

{description}

== Symptom: Errno::ENOENT message

When rendering a preview, an error message like the following appears in the console:

----
Error rendering asciidoctor: org.jruby.exceptions.RaiseException: (Errno::ENOENT) file:/C:/Users/....gemspec
----

The preview doesn't show.

== Environment: Windows or a non-UTF-8 default encoding

This seems to happen mostly on Windows systems as they don't default to UTF-8 charsets.
Linux systems usually default to UTF-8 and are not affected.

== Cause: Folder names with non-US-ASCII characters

Running Microsoft Windows, there seems to be a problem that JRuby can't read a folder name when it contains non-US-ASCII characters that would require a UTF-8 encoding.

This has been documented first in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/210[Issue 210]

== Remedies

<<upgrading,Upgrading to the latest version of IntelliJ and the plugin>> resolves this issue.
For earlier versions, <<fileencoding,changing the file encoding for IntelliJ>> solved the issue.

[#upgrading]
=== Upgrade to the latest IntelliJ and plugin version

This issue can be resolved by upgrading to the latest version of IntelliJ and the AsciiDoc plugin.

This was tested successfully for the following environment:

* IntelliJ version 2020.3.1,
* AsciiDoc Plugin version 0.32.5,
* Windows 10 with charset Windows-1252 and
* Plugin folder containing umlauts.

[#fileencoding]
=== Add the file encoding VM option to IDE

Put the following as a new line at the end of IDE's VM options file:

----
-Dfile.encoding=UTF-8
----

Users can open the file from their IDE via menu:Help[Edit custom VM options...].

The https://www.jetbrains.com/help/idea/tuning-the-ide.html[online documentation of IntelliJ] explains how to find this file in the local file system.
