= Proxy issues with the JCEF preview
:navtitle: Proxy issues JCEF preview
:description: JCEF preview supports proxy settings since 2021.1. Restart is required.

{description}
See below how to do that.

== Symptom: Remote content not shown

Images and other referenced remote content might not show up in the preview.

Local files within the project show without problems.

== Environment: JCEF preview and behind proxy

The plugin's settings in menu:File[Settings... > Languages & Frameworks > AsciiDoc > Preview Browser] shows that "`JCEF Browser`" is used.

The user is behind a proxy, and the content in the preview includes remote files.

== Cause: Old versions of JCEF don't support proxies

The JCEF preview doesn't support the IDE's proxy settings in version 2020.3 and earlier.

https://youtrack.jetbrains.com/issue/JBR-2605[The JetBrains issue tracker shows] that this is fixed in release 2021.1 Beta 3 (Build 211.6556.6).

== Solution: Update to 2021.1

For IntelliJ 2021.1 or later, the JCEF preview uses the proxy.
After configuring the proxy, the user needs to restart the IDE for the setting to become effective.

== Workaround: Use JavaFX preview

The plugin supports different kinds of previews: Swing, JavaFX and JCEF.

As a workaround, consider using the JavaFX preview.

See section xref:features/preview/javafx-preview.adoc[] for more information on how to enable it.
