= Troubleshooting problems when working with MPS
:navtitle: Troubleshooting MPS

This chapter summarizes known problems and possible remedies for users working with MPS.
If your issue is not listed here, please open a https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[new issue on GitHub].

== If you see a PluginException at IDE startup mentioning "`RefactoringMenu`"

The assumed cause for this is MPS removing menu items compared to IntelliJ core.
This leads to the exception at startup time.
The rest of the plugin's functionality is unaffected.

To work around the exception install an AsciiDoc MPS add-on _in addition_ to the regular AsciiDoc plugin.

Follow these steps:

. Vote for MPS to remedy the situation: https://youtrack.jetbrains.com/issue/MPS-31202[MPS-31202]
. Download the "`AsciiDoc MPS add-on`": link:{attachmentsdir}/asciidoctor-intellij-plugin-mps.jar[asciidoctor-intellij-plugin-mps.jar]
. Go to menu:File[Settings... > Plugins > Gear Icon] (icon:gear[])
. Choose menu:Install plugin from disk...[]
. Choose the downloaded file in the file selection dialogue
. Restart the IDE

You can read more about this in the related GitHub issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/502[asciidoctor-intellij-plugin#502].

== If you see an exception "`Wrong dependency type: class com.intellij.openapi.util.Key`" while editing a document

This seems to be a known problem with MPS: https://youtrack.jetbrains.com/issue/MPS-30801[MPS-30801].

Please vote on the issue above for MPS to provide a remedy.

No workaround is available as of today.
See https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/502[asciidoctor-intellij-plugin#502] for more details and a discussion.

If you found a workaround for this problem, please open a new issue or edit this document.
