= Validation of AsciiDoc files
:description: The AsciiDoc plugin for IntelliJ validates cross-references and attributes.
:navtitle: Validation of files

{description}

== How the plugin can help with validation

The IDE can validate, for example, cross-references and attribute names for a set of AsciiDoc files.
It will also provide auto-completion for attribute names and references.

To do this, all files need to be in one project.

If the IDE opens a single file and not a project with all related files, it might show validation errors where it shouldn't.

== How to edit files as a project

The user selects the menu item menu:File[Open...], then selects the folder and opens it.
The IDE will open files in the folder and its sub-folder as one project.
Validation and auto-completion then works as expected.

If the user opens the dialog to open a single file, the file will not be part of a project.
The IDE can then only provide a sub-set of auto-completion and validation.

== Further reading

If files are in separate distinct folders and still belong together, the user can group them into one project.
See chapter xref:features/advanced/multimodule.adoc[] for more information.
