= Intro to plugin development
:navtitle: Plugin development
:description: Introduction to developing plugins for JetBrains' IntelliJ platform.

{description}

== Getting into development

To get into the development of IntelliJ plugins, there is an http://www.jetbrains.org/intellij/sdk/docs/[IntelliJ SDK guide].
It walks the developer through several stages of developing a custom language plugin.
There is a chat on Slack that might give short answers to short questions to plugin developers: https://plugins.jetbrains.com/slack

== Other plugins`' sources as inspiration

This plugin pulled several ideas from the Markdown plugin for IntelliJ that is now part of the IntelliJ community edition.
Clone the https://github.com/JetBrains/intellij-community[GitHub repository for the IntelliJ Community edition] and check out the https://github.com/JetBrains/intellij-community/tree/master/plugins/markdown[Markdown plugin] in particular.
There is no need to make the community edition compile, instead use it as a reference and look up example implementations for IntelliJ's extension point base classes.

