= Releasing a new version of the plugin
:navtitle: Releasing the plugin
:description: Publish a new version of the pulgin (as a pre-release of as final release)

== Publishing a preview version

. Update _CHANGELOG.adoc_ with the latest changes for the release
. Push all changes to GitHub and wait for the build to complete. +
GitHub actions create https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases[a draft release].
The plugin is attached as `asciidoctor-intellij-plugin-xx.xx.xx.zip`.
. Publish the draft release in the GitHub Web UI. +
The plugin will be available from the https://plugins.jetbrains.com/plugin/7391-asciidoc/versions[EAP (early access program) repository]. See "`xref::user/add-eap-repository-to-ide.adoc[]`" for more information.

== Publishing a stable version

. Edit the _CHANGELOG.adoc_ and remove the "`(preview ...)`" additions here
. Copy the link of the `asciidoctor-intellij-plugin-xx.xx.xx.zip` on GitHub releases to the clipboard
. Go to the https://plugins.jetbrains.com/plugin/edit?pluginId=7391[JetBrains plugin repository] and upload the plugin to the stable repository using '`Get file from URL`'

