= Setup of the development environment
:description: Prepare for developing for the IntelliJ AsciiDoc plugin.
:navtitle: Setup environment

{description}

[[JDK]]
== Choosing a Java Version and Distribution

Starting with IntelliJ 2020.3 and plugin version 0.32.x, JDK 11 is required to build the plugin.
https://blog.jetbrains.com/platform/2020/09/intellij-project-migrates-to-java-11/[See the JDK 11 announcement in the JetBrains blog for details].

JetBrains recommends https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html[Amazon Corretto JDK] for development, but other distributions based on OpenJDK should work as well.

For the Gradle build tool to pick up the Java version, point the environment variable `JAVA_HOME` to the folder with the JDK:

.Setting the environment variable on Linux/MacOS
----
export JAVA_HOME=...
----

.Setting the environment variable on Windows
----
JAVA_HOME=c:\workspace\...
----

== Verify your environment

You can check your environment using the following command in the root folder of the project:

.Linux/MacOS command
----
./gradlew --version
----

.Windows command
----
gradlew --version
----

The output should be similar to:

[%nowrap]
----
------------------------------------------------------------
Gradle ...
------------------------------------------------------------

Build time:   ...
Revision:     ...

Kotlin:       ...
Groovy:       ...
Ant:          ...
JVM:          11.0.x (Amazon.com Inc. 11.0....)
OS:           ...
----


