= Setup of the development environment
:navtitle: Setup environment

[[JDK]]
== Choosing a Java Version and Distribution

Currently, JDK 8 and JavaFX is required to build and run the plugin.

The JetBrains JDK 8 distribution is recommended for development.
As some parts of the code still support Java 8 and JavaFX 8, you can't develop with Java 11 at the moment.
The plugin will still run in environments with Java 11.

JetBrains JDK 8::
Comes with a bundled JavaFX, download here: https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime[JetBrains OpenJDK 8].
This way you can develop with the JDK that is also running the JetBrains IDE.

For the Gradle build tool to pick up the Java version, point the environment variable `JAVA_HOME` to the folder with the JDK:

.Setting the environment variable on Linux/MacOS
----
export JAVA_HOME=...
----

.Setting the environment variable on Windows
----
JAVA_HOME=c:\workspace\...
----

== Verify your environment

You can check your environment using the following command in the root folder of the project:

.Linux/MacOS command
----
./gradlew --version
----

.Windows command
----
gradlew --version
----

The output should be similar to:

----
------------------------------------------------------------
Gradle ...
------------------------------------------------------------

Build time:   ...
Revision:     ...

Kotlin:       ...
Groovy:       ...
Ant:          ...
JVM:          1.8.0_...-release (JetBrains s.r.o ...)
OS:           ...
----

== Alternative JDKs

Oracle JDK 8::
Meets both dependencies, JavaFX is bundled with it out-of-the box.
This is easy to give development a start if it is already installed on your machine, but will be different from most user's installations.

OpenJDK 8::
Is usually distributed without JavaFX; you probably need to install JavaFX manually.
This is usually the least preferred approach, although in practice Linux users often run JetBrains IDEA with the JDK provided by their local Linux distribution (that now and then leads to difficulties).

