= Asciidoctor IntelliJ Plugin Changelog

== About

This document provides a high-level view of the changes introduced by release.

[[releasenotes]]
== Release notes

=== 0.37.36

- Fixing IndexOutOfBoundsException when converting Markdown to AsciiDoc (#1109)
- Avoid IllegalArgumentException when pasting an image as a reference (#1119)
- Avoid invalid file handles when rendering Antora references for the preview (#1120)

=== 0.37.35

- Prevent null elements when resolving file references (#1118)
- Fix changing the color of inline macros (thanks to @RayOffiah) (#1105)
- Handle internal references when moving multiple files (#1117)
- Bump asciidoctorj from 2.5.4 to 2.5.5 (#1112)

=== 0.37.34

- Prevent NPE when iterating Antora nav keys (#1115)

=== 0.37.33

- Bump asciidoctorj-pdf from 2.1.4 to 2.1.6 (#1110)
- rework the bounds checking when renaming files (#1092)

=== 0.37.32

- restore Markdown-to-AsciiDoc conversion on JDK 17 (#1101)
- avoid FileNotFoundException during autocomplete for images if they have been concurrently deleted (#1102)
- don't offer conversion or preview in browser for AsciiDoc files contained in JARs (#1103)

=== 0.37.31

- handle AlreadyDisposedException (#1100)

=== 0.37.30

- additional tests for auto-completion for antora pages (#1091)

=== 0.37.29

- don't highlight Antora module names in xref macros when they are distributed and link to multiple folders (#1091)
- xref macros will resolve relative to the Antora pages folder except when they start with a dot and are relative (#1091)
- avoid NoClassDefFoundError for YAMLScalar when activating the YAML plugin after the AsciiDoc plugin (#1097)
- when reporting errors with attachments, anonymized attchments will be checked by default

=== 0.37.28

- support Vale scopes for Grazie professional's project rules (#1089)
- improve the grouping in the settings by adding horizontal rules (#972)
- preventing a StringIndexOutOfBoundsException when moving files inside an Antora module (#1092)
- performance optimization for Antora when a lot of page aliases and attributes are used (#1091)
- xref macros even when used in the Antora partials folder will resolve relative to the pages directory
- documenting built-in attribute `++{pp}++` for `++`

=== 0.37.27

- Bump asciidoctorj-pdf from 2.1.2 to 2.1.4
- delete left-over XML when creating DOCX file (#1074)

=== 0.37.26

- conversion to DOCX now generally available for macOS (#1074)

=== 0.37.25

- adding missing changelog for 0.37.23 that got scrambled in the 0.37.24 release
- when creating DOCX files, fixing permissions on Pandoc execuable on macOS (#1074)

=== 0.37.24

- add support to convert AsciiDoc to the DOCX format (#1074)
- bump asciidoctorj-pdf from 2.0.6 to 2.1.2
- fix exception when Shell plugin in IntelliJ is installed after AsciiDoc plugin had already been installed (#1082)

=== 0.37.23

- handle language name snippets with special characters by quoting them (#1072)
- validate Antora module and component names (#1057)

=== 0.37.22

- fix wrong dependency for Asciidoctor Diagram (#1066)

=== 0.37.21

- synchronize latest Kroki Ruby changes, now including a referrer indicating the IntelliJ plugin
- bump asciidoctorj-pdf from 2.0.2 to 2.0.6 (#1064, #1068)
- bump asciidoctorj-diagram from 2.2.1 to 2.2.3 (#1066)
- bump asciidoctorj from 2.5.3 to 2.5.4 (#1069)
- for Antora, assume default family directory `pages` for all includes (#1062)

=== 0.37.20

- update to AsciidoctorJ PDF 2.0.2 (#1061)

=== 0.37.19

- handle exception when JCEF can't be initialized (#1051)
- update API usage to support JavaFX preview in InteliJ 2022.2

=== 0.37.18

- allow for attribute declarations in document ending with an `@`
- provide quick-fix to change attribute references to a passthrough
- fix navigation in preview for Antora cross-module xrefs with anchors (#1018)
- support editor formatting for passthrough with `++$$++` (#1017)
- support wrapping/unwrapping of selected text as passthrough by pressing `$` or `+` (#1017)
- new inspection for passthrough with `++$$++` and a quick-fix (#1017)
- when moving pages to another folder in an Antora module, update references also for includes (#981)

=== 0.37.17

- prevent NPE in when showing run markers (#1042)

=== 0.37.16

- prevent NPE in when showing run markers (#1042)

=== 0.37.15

- prevent error message "Directory index can only be queried after project initialization" (#1038)
- prevent already disposed message during background update (#1039)
- prevent blanks in suggested language names, adding 'shell' as an alias

=== 0.37.14

- support run command from editor for source code snippets and inline commands (#977)

=== 0.37.13

- support `max-width` attribute for the preview (#1029)
- allow manual download and picking for PlantUML and Ditaa Mini (#1026)

=== 0.37.12

- remove hard dependency on Grazie plugin that resulted in a ClassNotFoundException (#1014)

=== 0.37.11

- avoid NPE when handling an exception during AsciiDoc processing (#1012)

=== 0.37.10

- avoid NPE when showing the search progress bar when there is no progress indicator (#1006)
- avoid index-out-of-bounds situation when analyzing Asciidoctor logs and file is edited at the same time (#1010)

=== 0.37.9

- avoid NPE when showing the search progress bar when a file doesn't have a file name (#1006)
- extended error logging when static initializer in AsciiDocLanguage fails (#1007)

=== 0.37.8

- include Antora default CSS for the browser preview (#997)
- fix recursion problem with descriptions (#1003)

=== 0.37.7

- update reference searches to give the write access priority to avoid blocking the EDT
- avoid error messages for background processes when file has been concurrently deleted (#999)
- better text summaries in structure view
- improved block handling at end-of-file and for reparsing
- include Antora default CSS for the preview (#997)

=== 0.37.6

- prevent exception during startup activities on initial plugin installation (#992)
- prevent message "`Unable to find providerId`" when opening a previously opened file after installing the plugin (#993)
- updated parsing for pointy brackets in reference texts (#995)
- handle moving of folders in Antora pages directory and updating the references (#981)
- in Antora restrict the list of anchors in auto-completion and validation to the current page and its includes (#986)

=== 0.37.5

- fix range issue when preparing texts for the grammar checking plugin (#990)

=== 0.37.4

- fix table column spec support for syntax highlighting (#984)
- when invoking the quick-fix for a missing file, resolve base directory according to Antora rules (#985)
- fix exception when preview was already closed when rendering completed (#987)
- avoid NoClassDefFoundError after initialization of JCEF preview failed on Linux (#988)

=== 0.37.3

- update references when moving a page in Antora (#981)

=== 0.37.2

- prevent false positive grammar messages after unknown texts (reworked) (#980)

=== 0.37.1

- minimum version of IntelliJ is now 2021.3.1
- prevent false positive grammar messages after unknown texts (#980)

=== 0.36.18

- resolve document title from sub-includes when showing xrefs in preview (#967)
- force refresh of the preview even if preview is currently rendering (#967)
- when converting a Markdown listing to AsciiDoc, make number of dashed for delimiter (#969)

=== 0.36.17

- resolve Antora references without indexes in simple scenarios to improve user experience (#967)

=== 0.36.16

- upgrade to Asciidoctor 2.0.17 and AsciidoctorJ 2.5.3 (#966)
- fix navigation to anchors in current document's preview (#965)
- detailed errormessage in the preview if an Antora prefix can't be resolved (#967)
- refresh preview once indexing is complete (#967)

=== 0.36.15

- enforcing restart can't be triggered by the marketplace, reverting change (#962)
- update to Asciidoctor PDF 1.6.2 (#961)
- updated parsing for bold/italic/monospace handling for editor and highlighting (#963)

=== 0.36.14

- enforcing restart after plugin install for upgrades from version 0.36.11/0.36.12 when internal mode is enabled (#962)

=== 0.36.13

- disable unloading of plugin at runtime, restart will be required
- fix reformatting of preprocessor macros and block macros with text content (#955)
- strip newline from attribute continuation for grammar checks, strip duplicate characters for description lists (#956)
- don't report grammar errors for monospaced text and kbd macros (#956)
- treat inline passthrough content like quotes (#956)

=== 0.36.12

- workaround change in 2021.3.1 for preview with custom CSS (#954)

=== 0.36.11

- Support Antora 3 relative resource IDs with `./` for shorthand paths (#898)

=== 0.36.10

- API changes in IntelliJ EAP 2021.2.4 ExternalSystemUtil (#937)

=== 0.36.9

- fixing lexing issue with block macro after block attributes (#941)
- don't show notification about limited functionality in light mode
- increment index version numbers on stub version id increase to avoid invalid indexes
- API changes in IntelliJ EAP 2021.2.4 UntrustedProjectNotificationProvider (#937)

=== 0.36.8

- refactoring discovery of Antora playbooks to align with IntelliJ APIs (#919)
- API changes in IntelliJ EAP 2021.3.1 TrustChangeNotifier (#937)
- resolve NPE when initialization of Asciidoctor failed (#938)
- workaround for IndexNotReadyException when updating QuickDocInfo (#939)

=== 0.36.7

- fix preview of images in browser preview (#935)

=== 0.36.6

- prevent NPE case when showing documentation for current element (#929)
- rework iteration over index keys when retrieving list of sections (#930)
- cache evaluation of section headings
- update to latest Antora 3.x playbook schema (#907)
- updated log when language has already been registered (#928)
- support IntelliJ "`trusted projects`" concept and show an unrestricted preview only in trusted projects (#935)
- support continuation after source code block without style and delimiter

=== 0.36.5

- prevent error about unbalanced markers for inline IDs (#920)

=== 0.36.4

- avoid NoClassDefFoundError on plugin initialization (#928)
- prevent class cast exception in if referenced element is not a PsiNamedElement

=== 0.36.3

- xrefs with attributes will be resolved to determine if they link to an anchor or a file
- speed up resolving block IDs for auto-completion and validation (#925)
- continue to resolve attributes in document even if they have been defined in component descriptors or playbooks
- avoid expensive check in EDT for quickfix to create missing file

=== 0.36.2

- support folding of regular paragraphs (#426)
- allowing more contents to be quoted when creating PSI (#920)
- don't lose track when using source blocks inside table cells (#923)

=== 0.36.1

- refactor PSI structure for text with quotes for better text selection (#920)

=== 0.35.16

- exception handling when processing module roots in the background (#918)
- support relative local stylesheet and fallback to Asciidoctor styles if stylesheet is not available (#921)

=== 0.35.15

- fix resolving Antora page aliases
- improve resolving of anchors in Antora for partials and examples
- caching of Antora component descriptors and playbooks to speed up user interactions (#908)
- allow file index access when resolving references to files in the editor (#912)
- prevent AWT access when opening the browser after creating HTML for AsciiDoc on macOS (#913)

=== 0.35.14

- performance optimization JCEF preview (#908)
- support unset attributes in Antora component descriptors and playbooks (#893)
- support Antora 3 value _self_ for _link_ attribute (#897)
- performance optimization for Antora environments by caching playbook and component descriptor attributes (#897)
- validation for link attribute (#897)
- implement caching of attributes and text content to speed up interactions (#908)
- implement caching texts for grammar checking on section level (#908)
- update structure outline when editing the level of a section in the editor

=== 0.35.13

- performance optimization for grammar check (#908)

=== 0.35.12

- updating Antora playbook schema to 3.0.0-alpha.10
- advise users of 2021.2.x to use at least 2021.2.3 to due to platform bugfixes
- update grammar and spell checking for xref macros that don't contain link text (#890)

=== 0.35.11

- fix resolving attribute names (#893)

=== 0.35.10

- suggest to users to switch from JavaFX preview to JCEF preview
- update to latest Asciidoctor Kroki version with improved logging and pikchr diagram support
- adjust scope to page attribute scope when resolving Antora's reftext/navtext attributes for the preview (#889)
- preventing error when updating actions for create-pdf-from-preview (#894)
- handle markdown-style listing conversions where backticks are followed by spaces (#895)
- support soft-set attributes in Antora component descriptors and playbooks (#893)

=== 0.35.9

- resolve attributes in Antora's reftext/navtext attributes for the preview (#889)
- update grammar and spell checking for btn and other macros (#890)
- two lists can be separated by a blank line and a comment (#860)
- hide editor toolbar when in presentation mode (#824)

=== 0.35.8

- avoid slow operation warning when folding attributes (#887)
- avoid slow operation warning when fetching documentation (#815)
- fix parsing of block markers after line comments

=== 0.35.7

- resolve attributes of current file even if it is opened outside the project. Show notification with warning and link (#880)
- support adding and removing quotes from selected text via hotkey (#866)
- register structurizr as kroki diagram (#886)

=== 0.35.6

- optimized dark theme for verse blocks
- improved folded summary for lists as well as description in structure view (#860)

=== 0.35.5

- removing workaround for "`Cannot Open the Page/ERR_ABORTED`" to IntelliJ 2021.1 (#658)
- upgrading grammar and spell checking to new IntelliJ API (#873)
- improved handling of lists; list items are now wrapped in another PSI element for folding (#860)

=== 0.35.4

- starting with this release, 2021.2 is required due to API changes in IntelliJ

=== 0.35.3

- added spell-checking for characters in keyboard macros
- added spell-checking for pass-through content
- plugin will show an error in the editor if case of file name in document differs from the case of the file in file system (#863)

=== 0.35.2

- handle already disposed component in workaround for HiDPI preview (#864)
- make attributes in Antora playbook available for preview and autocomplete (#776)

=== 0.35.1

- avoid JCEF preview to overlap with other windows (#751)
- starting with this release, 2021.2.1 is required due to API changes in IntelliJ

=== 0.34.2

- upgrade to AsciidoctorJ Diagram 2.2.1 (#855)
- support videos in Antora images folder (#828)
- add inspection for attributes that haven't been defined (#858)
- infer attributes from Antora playbook for auto-complete of attributes (#776)
- lazy initialization for attributes to avoid exceptions in initializer (#861)
- avoid building/clearing errors on project startup (#862)

=== 0.34.1

- lighter color for caption titles in dark mode in the preview (#841)
- extend Antora playbook schema for 3.0.0-alpha.8 and 3.0.0-alpha.9
- prevent NPE when accessing parent folder of a file (#847)
- improve parsing of links and email addresses for grammar check (#846)
- upgrade to AsciidoctorJ Diagram 2.2.0 and PlantUML 1.2021.8 (#832)
- adding live templates for curved quotes (#837)
- avoid situation where panel is re-created and contents show "Initializing..."

=== 0.33.19

- avoid logged error when converting Markdown to AsciiDoc and target file exists (#839)
- revert changes about progress indicator on slow index operations (#815)

=== 0.33.18

- improved handling of blanks for IntelliJ 2021.1.x grammar check further (#818)

=== 0.33.17

- improved handling of blanks for IntelliJ 2021.1.x grammar check (#818)

=== 0.33.16

- prevent more unbalanced markers at beginning of a heading (#822)

=== 0.33.15

- line comment with two colons will no longer be highlighted as a definition list in the editor (#822)
- log additional information and prevent parsing from failing completely when a heading doesn't contain any text (#826)
- improved parsing for definition lists resulting in better folding and structure view when definition contains multiple words (#822)
- rework to prevent unbalanced markers at beginning of a heading (#822)
- prevent PsiInvalidElementAccessException when switching document (#827)

=== 0.33.14

- fix parser/lexer for section headings with inline references
- avoid run-off lexer for attribute references in autocomplete
- handle consecutive blanks passed down for grammar check in 2021.1 (#818)
- close open block markers before heading starts (#825)

=== 0.33.13

- upgrade to AsciidoctorJ 2.5.2 (includes Asciidoctor 2.0.16)
- handle empty string passed down for grammar check in 2021.1 (#818)

=== 0.33.12

- folding of list and callout items, plus grammar check per item instead of the whole list (#822)

=== 0.33.11

- use IntelliJ API to determine event dispatch thread instead of using internal JDK API (#823)

=== 0.33.10

- restore API compatibility with Asciidoclet plugin (#789)
- split logic to handle both 2021.1 and 2021.2 contents handed down by grammar checker (#818)

=== 0.33.9

- avoid exceptions when initializing plugin's icons (#821)
- additional logging to trace grammar checker problems, handling spaces at the beginning (#818)

=== 0.33.8

- enable rendering of diagrams in preview for modes other than UNSAFE (#789)
- rework handling of leading/trailing whitespace when preparing the input for the grammar check (#818)
- restore compatibility with 2020.3/2021.1 that broken in 0.33.7 (#815)

=== 0.33.7

- parse AsciiDoc table cells for source lines, improve navigation to source line (#810)
- when converting a Markdown file to AsciiDoc, warn if target file already exists and allow overwriting it (thanks to @santik) (#763, #808)
- reduce blocking of EDT thread when accessing file indexes (#815)

=== 0.33.6

- restore compatibility with 2020.3/2021.1 and avoid NoSuchMethodError (#806)

=== 0.33.5

- plugin shouldn't interfere with HTML preview focus handling (#802)
- when calculating the cut-off for the next token, take into account that this is called before the advance method (#803)

=== 0.33.4

- prevent NPE when Antora component descriptor is an empty file (#782)
- prevent IAE when expanding attributes
- when NPE on paste occurs, log additional information (#790)
- trying to avoid LinkageError in 2021.2 (#791)
- prevent error "Already disposed" when closing an editor (#799)

=== 0.33.3

- restore compatibility for IntelliJ 2020.3.x (#779)

=== 0.33.2

- prevent NPE in startup activity when dynamically loading AsciiDoc plugin (#779)
- revisiting parsing spaces for grammar checker (#752)
- prevent NPE for zoom settings

=== 0.33.1

- support new keys _network_ and _log_ in Antora playbooks
- drop support for 2020.2.x in 0.33.x releases

=== 0.32.55

- fix dependencies/class not found problems for IDEs like PHPStorm introduced in 0.32.54 (#769)

=== 0.32.54

- in Antora component descriptors, support auto-complete for keys _nav_ and _start_page_ (#769)

=== 0.32.53

- prevent NPE when renaming files in Antora projects (#770)
- when rendering errors in the preview, allow preview to refresh without flicker (#772)

=== 0.32.52

- fixing opening wrong editor for antora.yml files (#769)

=== 0.32.51

- fixing bug that prevented the editor to scroll to a line when clicking in preview (#768)

=== 0.32.50

- support ID references appended to blocks as used in AsciiDoc documentation like `[source#hello]`
- support style in blocks used in AsciiDoc documentation like `[#id%autowidth]`
- completed support for highlight.js in the preview (#370)
- adding notification to upgrade to 2021.1.2 when using 2021.1 or 2021.1.1 on macOS to prevent UI freeze (#765)

=== 0.32.49

- fix parsing escape character for inline IDs in section headings (#758)
- update to AsciidoctorJ PDF 1.6.0
- avoid exceptions when modules/libraries have already been removed (#760)
- escape HTML characters when rendering exception in preview (#761)
- escape ampersand in documentation of attributes, as IntelliJ would replace it
- prevent unnecessary disposals (#761)

=== 0.32.48

- update Antora playbook schema to include `edit_url` also in `source` element (#757)
- avoid NPE when creating a new file via a quick-fix (#745)

=== 0.32.47

- robust parsing spaces for grammar checker (#752)

=== 0.32.46

- source highlighting with highlight.js now documented (#370)
- when working in Antora modules, read attributes from _.asciidoctorconfig_ files (#703)
- fix problem when parsing spaces for grammar checker (#752)

=== 0.32.45

- additional logging when exceptions occur when checking grammar and spelling problems (#752)
- prevent exception for quickfix when missing file can't be created (#745)

=== 0.32.44

- adding loop detection to lexer (#742)
- avoid NPE when creating a new file via a quick-fix (#745)
- update to AsciidoctorJ 2.5.1 and Asciidoctor 2.0.15 (#738)
- use attributes defined in plugin's settings for auto-complete and validation in editor (#746)
- use build-in attributes for auto-complete when entering a reference to an attribute (#746)
- remove spaces not rendered by AsciiDoc before invoking grammar check, avoiding undesired warnings (#747)
- enable find-usages and renaming for negated include tags (#730)

=== 0.32.43

- avoid infinite loop/freezing UI when parsing comments (#742)

=== 0.32.42

- update to AsciidoctorJ 2.5.0 and Asciidoctor 2.0.14 (#738)
- optimizing lexing of line comments (#742)

=== 0.32.41

- avoid exception when applying formatting to three formatting characters, like a bold asterisk (#739)

=== 0.32.40

- resolve attributes like `docname` in nested includes to validate anchors (#737)

=== 0.32.39

- rework situation when no injection is active (#732)
- rework handling of already disposed modules (#683)
- avoid URLDecoder exception when an incompletely encoded URL is entered (#736)

=== 0.32.38

- avoid error message "`already disposed`" when handling problems with JCEF refresh/crashes (#729)
- fix renaming of xrefs in attributes for example with images (#730)
- enable find-usages and renaming for include tags (#730)
- initial support for source highlighter highlight.js in preview (#370)
- add notification for users to update to 2021.1.1 (#725)
- suppress warnings in 2021.1.1 EAP (#731)
- avoid error during project initialization (#733)
- avoid error when using fragment editor and inserting for example an include preprocessor macro (#732)
- support language injection for Markdown style listings (#732)

=== 0.32.37

- when searching for references for AsciiDoc sections and IDs, limited search scope to AsciiDoc file type (#722)
- tuning comment parsing (#696)
- creating fewer references when analyzing include tags in a file (#723)
- preventing plugin-unloading earlier in the plugin's loading cycle (#724)
- support Antora's 3.x new keyword for versionless component version (#728)

=== 0.32.36

- reworking error logging to avoid logging ProcessCanceled events (#718)
- listings in IntelliJ light theme will highlight with a light grey background (like inline monospace content)

=== 0.32.35

- rework StringIndexOutOfBoundsException in Grammar Check (#718)

=== 0.32.34

- improve error messages during PDF generation, adding option to add attribute _allow-uri-read_ (#717)
- avoid StringIndexOutOfBoundsException in Grammar Check (#718)

=== 0.32.33

- update to AsciidoctorJ Diagram 2.1.2

=== 0.32.32

- restrict preview using content security policy when user chooses SAVE mode (#707)
- update to AsciidoctorJ Diagram 2.1.1
- fix spelling/grammar check for attributes with continuations (#712)
- add new file templates for AsciiDoc (#715)

=== 0.32.31

- updated plugin's description for better search results in JetBrains Marketplace
- reduce instances where recursion can occur when resolving file references
- rework typographic quotes grammar check to avoid index out of bounds exception (#699)
- support all well-known AsciiDoc file extensions when auto-completing and validating file names (#706)

=== 0.32.30

- allow folding of typographic quotes in editor (#699)
- when interpolating IDs for section headings, respect `idprefix` and `idseparator` in Antora component descriptor (#703)
- adding monospace and italic syntax highlighting for nested elements (#699)
- passing on typographic single quotes to grammar checker (#699)

=== 0.32.29

- handling typographic quotes near monospaced inline content (#699)

=== 0.32.28

- adding spell checking for footnotes (#692)
- preventing exception when project view is not available (#695)
- preventing exception when search for references for Java classes without a name (#698)

=== 0.32.27

- avoid exception that editor has already been disposed (#693)
- improved handling for parsing footnotes (#692)
- avoid exception when processing events for already disposed projects (#683)

=== 0.32.26

- minimize logic of focus handling after testing on Linux (#691)

=== 0.32.25

- focus on preview when no editor is available, therefore allowing keyboard navigation in preview (#691)
- backporting support for different zoom levels on different screens to 2020.3.2 (#690)

=== 0.32.24

- render preview in designated area in cases where primary and secondary screen have different zoom levels (#690)

=== 0.32.23

- handle escaped attribute references in headlines (#689)
- reworked support for Antora JSON Schemas to avoid exception in log (#687)

=== 0.32.22

- simplified code to handle Antora JSON Schemas to avoid exception in log (#687)
- zoom level in plugin's setting now entered without the percent sign in input fiel to avoid parsing problems when percent sign is missing (#674)

=== 0.32.21

- avoid exception when processing file events for already disposed module (#683)
- fixing exception "`spaces element contains non-spaces-characters`" in lexer (#685)

=== 0.32.20

- avoid exception when looking up items by name and item is in a library (#677)
- regression: don't show AsciiDoc content in libraries on auto-completion (#677)

=== 0.32.19

- auto-complete for images will no longer auto-suggest anchor names (#672)
- transfer long exception messages to Sentry to avoid cut-offs (#672)
- speed up lookup of references by declaring a specific search scope that excludes libraries (#672)
- adopt workaround to prevent JCEF preview error "`Cannot Open the Page/ERR_ABORTED`" to IntelliJ 2021.x. (#658)
- avoid "`Invalid root file`" error when deleting files or folders (#676)

=== 0.32.18

- avoid exception in log when opening AsciiDoc file (#667)
- report build number for IntelliJ EAP releases when submitting information to Sentry (#670)
- update to AsciidoctorJ 2.4.3
- handle auto-completion for MacOS X volume icons (#671)
- use new NIO file API when converting to HTML or PDF file to avoid file name manipulation issues (#666)

=== 0.32.17

- fix classloader problem for JRuby on IntelliJ 2021.x EAP (#664)
- rework issue #658 to restore functionality for zoom and open-links-in-external-browser (#665)

=== 0.32.16

- when un-quoting a selected text to be no longer bold italic or monospaced, the inner text must be at least one char long (#656)
- prevent JCEF preview error "`Cannot Open the Page/ERR_ABORTED`" error in IntelliJ 2020.3.x versions (#658)
- prevent exception when extending word selection for example near a double quote (#661)

=== 0.32.15

- prevent looping/blocking external annotator when post-processing of include error messages (#649)
- prevent unloading of plugin even when no project has been opened yet to avoid loading errors afterwards for icons, resources and schemas (#652)
- forcing re-indexing of AsciiDoc content as previous updates changed parsing/lexing, and the resulting IntelliJ indexes are out of date (#653)
- avoid exception when search for references in Java's root package name (#654)

=== 0.32.14

- prevent issuing a repaint on EDT thread, preventing refresh requests to queue up (#641)
- when embedding iframes in the preview, don't try an in-place update of the contents as this could break the JavaScript for example of YouTube videos (#640)
- prevent lagging UI when refreshing the preview with JCEF and not using in-place refresh (#640)
- JCEF preview is the default for new installations

=== 0.32.13 (preview, available from GitHub releases)

- fixed support for 'tags' key for sources in Antora playbook (#646)

=== 0.32.12

- performance improvement when parsing long lines and words by limiting the length of inline macro names and email addresses (#641)
- improvement data structure for handling a large number of modules (#641)

=== 0.32.11 (preview, available from GitHub releases)

- validate that language for source block is marked injectable by JetBrains (#642)
- performance optimizations on background tasks
- only changes to file in current project's modules will refresh the preview (#641)
- update cached project roots from changed files (#641)

=== 0.32.10 (preview, available from GitHub releases)

- cache project roots to speed up preview and read actions, and to prevent blocking the write thread (#641)
- use read actions with write action priority on all background tasks (#641)

=== 0.32.9 (preview, available from GitHub releases)

- update Kroki support with latest diagrams and attributes, fixing `kroki-plantuml-include` support (#639)
- prevent error messages in log when projects have already been disposed

=== 0.32.8 (preview, available from GitHub releases)

- update preview when project leaves or enters dumb mode so that pending references can be resolved
- prevent NPE when block attributes are not provided
- users can submit error reports anonymously to the plugin's project at Sentry when exceptions occur (#628)
- upgrade to AsciidoctorJ PDF 1.5.4
- Additional reformat option for blank lines after headings (thanks to @c7haki) (#633)
- upgrade to AsciidoctorJ Diagram 2.1.0 and PlantUML v1.2021.0

=== 0.32.7

- show action tool bar in light edit mode (#630)
- fix timestamp when pasting a screenshot from the clipboard (#631)

=== 0.32.6

- don't treat menu items as links
- show soft-wrap notification to all users that don't use it yet

=== 0.32.5 (preview, available from GitHub releases)

- if content in the preview is from an included file, click on the content in the preview opens included file (#557)
- stop implementing an EditorActionHandler as pasting of images seems to work without it to avoid the plugin to appear in EDT freezes when delegating calls (#605, #584)

=== 0.32.4 (preview, available from GitHub releases)

- recognize front matter when parsing page attributes
- add block and paragraph admonition live template (thanks to @rdmueller) (#609,  #611)
- support bibliography anchors alone on a line (#614)
- handling attribute references in block attributes

=== 0.32.3 (preview, available from GitHub releases)

- initial support for light edit mode (#606)

=== 0.32.2

- rework JavaFX handling with JDK 11 to avoid inaccessible exception
- rework parsing of `kbd` macro to prevent runaway escapes
- fixing wrong indexing of section titles with attributes causing "`PSI and index do not match`"
- choose-by-name will find sections with replaced attributes

=== 0.32.1 (preview, available from GitHub releases)

- fix right-click-saves-image in JavaFX preview
- changing development to JDK 11 in line with IntelliJ 2020.3 platform
- don't break section titles with custom IDs or attributes on automatic reformat (#604)
- don't use title with replaced attribute as PsiElement's name as IntelliJ might throw an "`PSI and index do not match`" exception
- formatting of words via actions in the toolbar now works with the cursor placed at the end of the word (#602)
