= Asciidoctor IntelliJ Plugin Changelog

== About

This document provides a high-level view of the changes introduced by release.

[[releasenotes]]
== Release notes

=== 0.36.13

- disable unloading of plugin at runtime, restart will be required
- fix reformatting of preprocessor macros and block macros with text content (#955)

=== 0.36.12

- workaround change in 2021.3.1 for preview with custom CSS (#954)

=== 0.36.11

- Support Antora 3 relative resource IDs with `./` for shorthand paths (#898)

=== 0.36.10

- API changes in IntelliJ EAP 2021.2.4 ExternalSystemUtil (#937)

=== 0.36.9

- fixing lexing issue with block macro after block attributes (#941)
- don't show notification about limited functionality in light mode
- increment index version numbers on stub version id increase to avoid invalid indexes
- API changes in IntelliJ EAP 2021.2.4 UntrustedProjectNotificationProvider (#937)

=== 0.36.8

- refactoring discovery of Antora playbooks to align with IntelliJ APIs (#919)
- API changes in IntelliJ EAP 2021.3.1 TrustChangeNotifier (#937)
- resolve NPE when initialization of Asciidoctor failed (#938)
- workaround for IndexNotReadyException when updating QuickDocInfo (#939)

=== 0.36.7

- fix preview of images in browser preview (#935)

=== 0.36.6

- prevent NPE case when showing documentation for current element (#929)
- rework iteration over index keys when retrieving list of sections (#930)
- cache evaluation of section headings
- update to latest Antora 3.x playbook schema (#907)
- updated log when language has already been registered (#928)
- support IntelliJ "`trusted projects`" concept and show an unrestricted preview only in trusted projects (#935)
- support continuation after source code block without style and delimiter

=== 0.36.5

- prevent error about unbalanced markers for inline IDs (#920)

=== 0.36.4

- avoid NoClassDefFoundError on plugin initialization (#928)
- prevent class cast exception in if referenced element is not a PsiNamedElement

=== 0.36.3

- xrefs with attributes will be resolved to determine if they link to an anchor or a file
- speed up resolving block IDs for auto-completion and validation (#925)
- continue to resolve attributes in document even if they have been defined in component descriptors or playbooks
- avoid expensive check in EDT for quickfix to create missing file

=== 0.36.2

- support folding of regular paragraphs (#426)
- allowing more contents to be quoted when creating PSI (#920)
- don't lose track when using source blocks inside table cells (#923)

=== 0.36.1

- refactor PSI structure for text with quotes for better text selection (#920)

=== 0.35.16

- exception handling when processing module roots in the background (#918)
- support relative local stylesheet and fallback to Asciidoctor styles if stylesheet is not available (#921)

=== 0.35.15

- fix resolving Antora page aliases
- improve resolving of anchors in Antora for partials and examples
- caching of Antora component descriptors and playbooks to speed up user interactions (#908)
- allow file index access when resolving references to files in the editor (#912)
- prevent AWT access when opening the browser after creating HTML for AsciiDoc on macOS (#913)

=== 0.35.14

- performance optimization JCEF preview (#908)
- support unset attributes in Antora component descriptors and playbooks (#893)
- support Antora 3 value _self_ for _link_ attribute (#897)
- performance optimization for Antora environments by caching playbook and component descriptor attributes (#897)
- validation for link attribute (#897)
- implement caching of attributes and text content to speed up interactions (#908)
- implement caching texts for grammar checking on section level (#908)
- update structure outline when editing the level of a section in the editor

=== 0.35.13

- performance optimization for grammar check (#908)

=== 0.35.12

- updating Antora playbook schema to 3.0.0-alpha.10
- advise users of 2021.2.x to use at least 2021.2.3 to due to platform bugfixes
- update grammar and spell checking for xref macros that don't contain link text (#890)

=== 0.35.11

- fix resolving attribute names (#893)

=== 0.35.10

- suggest to users to switch from JavaFX preview to JCEF preview
- update to latest Asciidoctor Kroki version with improved logging and pikchr diagram support
- adjust scope to page attribute scope when resolving Antora's reftext/navtext attributes for the preview (#889)
- preventing error when updating actions for create-pdf-from-preview (#894)
- handle markdown-style listing conversions where backticks are followed by spaces (#895)
- support soft-set attributes in Antora component descriptors and playbooks (#893)

=== 0.35.9

- resolve attributes in Antora's reftext/navtext attributes for the preview (#889)
- update grammar and spell checking for btn and other macros (#890)
- two lists can be separated by a blank line and a comment (#860)
- hide editor toolbar when in presentation mode (#824)

=== 0.35.8

- avoid slow operation warning when folding attributes (#887)
- avoid slow operation warning when fetching documentation (#815)
- fix parsing of block markers after line comments

=== 0.35.7

- resolve attributes of current file even if it is opened outside the project. Show notification with warning and link (#880)
- support adding and removing quotes from selected text via hotkey (#866)
- register structurizr as kroki diagram (#886)

=== 0.35.6

- optimized dark theme for verse blocks
- improved folded summary for lists as well as description in structure view (#860)

=== 0.35.5

- removing workaround for "`Cannot Open the Page/ERR_ABORTED`" to IntelliJ 2021.1 (#658)
- upgrading grammar and spell checking to new IntelliJ API (#873)
- improved handling of lists; list items are now wrapped in another PSI element for folding (#860)

=== 0.35.4

- starting with this release, 2021.2 is required due to API changes in IntelliJ

=== 0.35.3

- added spell-checking for characters in keyboard macros
- added spell-checking for pass-through content
- plugin will show an error in the editor if case of file name in document differs from the case of the file in file system (#863)

=== 0.35.2

- handle already disposed component in workaround for HiDPI preview (#864)
- make attributes in Antora playbook available for preview and autocomplete (#776)

=== 0.35.1

- avoid JCEF preview to overlap with other windows (#751)
- starting with this release, 2021.2.1 is required due to API changes in IntelliJ

=== 0.34.2

- upgrade to AsciidoctorJ Diagram 2.2.1 (#855)
- support videos in Antora images folder (#828)
- add inspection for attributes that haven't been defined (#858)
- infer attributes from Antora playbook for auto-complete of attributes (#776)
- lazy initialization for attributes to avoid exceptions in initializer (#861)
- avoid building/clearing errors on project startup (#862)

=== 0.34.1

- lighter color for caption titles in dark mode in the preview (#841)
- extend Antora playbook schema for 3.0.0-alpha.8 and 3.0.0-alpha.9
- prevent NPE when accessing parent folder of a file (#847)
- improve parsing of links and email addresses for grammar check (#846)
- upgrade to AsciidoctorJ Diagram 2.2.0 and PlantUML 1.2021.8 (#832)
- adding live templates for curved quotes (#837)
- avoid situation where panel is re-created and contents show "Initializing..."

=== 0.33.19

- avoid logged error when converting Markdown to AsciiDoc and target file exists (#839)
- revert changes about progress indicator on slow index operations (#815)

=== 0.33.18

- improved handling of blanks for IntelliJ 2021.1.x grammar check further (#818)

=== 0.33.17

- improved handling of blanks for IntelliJ 2021.1.x grammar check (#818)

=== 0.33.16

- prevent more unbalanced markers at beginning of a heading (#822)

=== 0.33.15

- line comment with two colons will no longer be highlighted as a definition list in the editor (#822)
- log additional information and prevent parsing from failing completely when a heading doesn't contain any text (#826)
- improved parsing for definition lists resulting in better folding and structure view when definition contains multiple words (#822)
- rework to prevent unbalanced markers at beginning of a heading (#822)
- prevent PsiInvalidElementAccessException when switching document (#827)

=== 0.33.14

- fix parser/lexer for section headings with inline references
- avoid run-off lexer for attribute references in autocomplete
- handle consecutive blanks passed down for grammar check in 2021.1 (#818)
- close open block markers before heading starts (#825)

=== 0.33.13

- upgrade to AsciidoctorJ 2.5.2 (includes Asciidoctor 2.0.16)
- handle empty string passed down for grammar check in 2021.1 (#818)

=== 0.33.12

- folding of list and callout items, plus grammar check per item instead of the whole list (#822)

=== 0.33.11

- use IntelliJ API to determine event dispatch thread instead of using internal JDK API (#823)

=== 0.33.10

- restore API compatibility with Asciidoclet plugin (#789)
- split logic to handle both 2021.1 and 2021.2 contents handed down by grammar checker (#818)

=== 0.33.9

- avoid exceptions when initializing plugin's icons (#821)
- additional logging to trace grammar checker problems, handling spaces at the beginning (#818)

=== 0.33.8

- enable rendering of diagrams in preview for modes other than UNSAFE (#789)
- rework handling of leading/trailing whitespace when preparing the input for the grammar check (#818)
- restore compatibility with 2020.3/2021.1 that broken in 0.33.7 (#815)

=== 0.33.7

- parse AsciiDoc table cells for source lines, improve navigation to source line (#810)
- when converting a Markdown file to AsciiDoc, warn if target file already exists and allow overwriting it (thanks to @santik) (#763, #808)
- reduce blocking of EDT thread when accessing file indexes (#815)

=== 0.33.6

- restore compatibility with 2020.3/2021.1 and avoid NoSuchMethodError (#806)

=== 0.33.5

- plugin shouldn't interfere with HTML preview focus handling (#802)
- when calculating the cut-off for the next token, take into account that this is called before the advance method (#803)

=== 0.33.4

- prevent NPE when Antora component descriptor is an empty file (#782)
- prevent IAE when expanding attributes
- when NPE on paste occurs, log additional information (#790)
- trying to avoid LinkageError in 2021.2 (#791)
- prevent error "Already disposed" when closing an editor (#799)

=== 0.33.3

- restore compatibility for IntelliJ 2020.3.x (#779)

=== 0.33.2

- prevent NPE in startup activity when dynamically loading AsciiDoc plugin (#779)
- revisiting parsing spaces for grammar checker (#752)
- prevent NPE for zoom settings

=== 0.33.1

- support new keys _network_ and _log_ in Antora playbooks
- drop support for 2020.2.x in 0.33.x releases

=== 0.32.55

- fix dependencies/class not found problems for IDEs like PHPStorm introduced in 0.32.54 (#769)

=== 0.32.54

- in Antora component descriptors, support auto-complete for keys _nav_ and _start_page_ (#769)

=== 0.32.53

- prevent NPE when renaming files in Antora projects (#770)
- when rendering errors in the preview, allow preview to refresh without flicker (#772)

=== 0.32.52

- fixing opening wrong editor for antora.yml files (#769)

=== 0.32.51

- fixing bug that prevented the editor to scroll to a line when clicking in preview (#768)

=== 0.32.50

- support ID references appended to blocks as used in AsciiDoc documentation like `[source#hello]`
- support style in blocks used in AsciiDoc documentation like `[#id%autowidth]`
- completed support for highlight.js in the preview (#370)
- adding notification to upgrade to 2021.1.2 when using 2021.1 or 2021.1.1 on macOS to prevent UI freeze (#765)

=== 0.32.49

- fix parsing escape character for inline IDs in section headings (#758)
- update to AsciidoctorJ PDF 1.6.0
- avoid exceptions when modules/libraries have already been removed (#760)
- escape HTML characters when rendering exception in preview (#761)
- escape ampersand in documentation of attributes, as IntelliJ would replace it
- prevent unnecessary disposals (#761)

=== 0.32.48

- update Antora playbook schema to include `edit_url` also in `source` element (#757)
- avoid NPE when creating a new file via a quick-fix (#745)

=== 0.32.47

- robust parsing spaces for grammar checker (#752)

=== 0.32.46

- source highlighting with highlight.js now documented (#370)
- when working in Antora modules, read attributes from _.asciidoctorconfig_ files (#703)
- fix problem when parsing spaces for grammar checker (#752)

=== 0.32.45

- additional logging when exceptions occur when checking grammar and spelling problems (#752)
- prevent exception for quickfix when missing file can't be created (#745)

=== 0.32.44

- adding loop detection to lexer (#742)
- avoid NPE when creating a new file via a quick-fix (#745)
- update to AsciidoctorJ 2.5.1 and Asciidoctor 2.0.15 (#738)
- use attributes defined in plugin's settings for auto-complete and validation in editor (#746)
- use build-in attributes for auto-complete when entering a reference to an attribute (#746)
- remove spaces not rendered by AsciiDoc before invoking grammar check, avoiding undesired warnings (#747)
- enable find-usages and renaming for negated include tags (#730)

=== 0.32.43

- avoid infinite loop/freezing UI when parsing comments (#742)

=== 0.32.42

- update to AsciidoctorJ 2.5.0 and Asciidoctor 2.0.14 (#738)
- optimizing lexing of line comments (#742)

=== 0.32.41

- avoid exception when applying formatting to three formatting characters, like a bold asterisk (#739)

=== 0.32.40

- resolve attributes like `docname` in nested includes to validate anchors (#737)

=== 0.32.39

- rework situation when no injection is active (#732)
- rework handling of already disposed modules (#683)
- avoid URLDecoder exception when an incompletely encoded URL is entered (#736)

=== 0.32.38

- avoid error message "`already disposed`" when handling problems with JCEF refresh/crashes (#729)
- fix renaming of xrefs in attributes for example with images (#730)
- enable find-usages and renaming for include tags (#730)
- initial support for source highlighter highlight.js in preview (#370)
- add notification for users to update to 2021.1.1 (#725)
- suppress warnings in 2021.1.1 EAP (#731)
- avoid error during project initialization (#733)
- avoid error when using fragment editor and inserting for example an include preprocessor macro (#732)
- support language injection for Markdown style listings (#732)

=== 0.32.37

- when searching for references for AsciiDoc sections and IDs, limited search scope to AsciiDoc file type (#722)
- tuning comment parsing (#696)
- creating fewer references when analyzing include tags in a file (#723)
- preventing plugin-unloading earlier in the plugin's loading cycle (#724)
- support Antora's 3.x new keyword for versionless component version (#728)

=== 0.32.36

- reworking error logging to avoid logging ProcessCanceled events (#718)
- listings in IntelliJ light theme will highlight with a light grey background (like inline monospace content)

=== 0.32.35

- rework StringIndexOutOfBoundsException in Grammar Check (#718)

=== 0.32.34

- improve error messages during PDF generation, adding option to add attribute _allow-uri-read_ (#717)
- avoid StringIndexOutOfBoundsException in Grammar Check (#718)

=== 0.32.33

- update to AsciidoctorJ Diagram 2.1.2

=== 0.32.32

- restrict preview using content security policy when user chooses SAVE mode (#707)
- update to AsciidoctorJ Diagram 2.1.1
- fix spelling/grammar check for attributes with continuations (#712)
- add new file templates for AsciiDoc (#715)

=== 0.32.31

- updated plugin's description for better search results in JetBrains Marketplace
- reduce instances where recursion can occur when resolving file references
- rework typographic quotes grammar check to avoid index out of bounds exception (#699)
- support all well-known AsciiDoc file extensions when auto-completing and validating file names (#706)

=== 0.32.30

- allow folding of typographic quotes in editor (#699)
- when interpolating IDs for section headings, respect `idprefix` and `idseparator` in Antora component descriptor (#703)
- adding monospace and italic syntax highlighting for nested elements (#699)
- passing on typographic single quotes to grammar checker (#699)

=== 0.32.29

- handling typographic quotes near monospaced inline content (#699)

=== 0.32.28

- adding spell checking for footnotes (#692)
- preventing exception when project view is not available (#695)
- preventing exception when search for references for Java classes without a name (#698)

=== 0.32.27

- avoid exception that editor has already been disposed (#693)
- improved handling for parsing footnotes (#692)
- avoid exception when processing events for already disposed projects (#683)

=== 0.32.26

- minimize logic of focus handling after testing on Linux (#691)

=== 0.32.25

- focus on preview when no editor is available, therefore allowing keyboard navigation in preview (#691)
- backporting support for different zoom levels on different screens to 2020.3.2 (#690)

=== 0.32.24

- render preview in designated area in cases where primary and secondary screen have different zoom levels (#690)

=== 0.32.23

- handle escaped attribute references in headlines (#689)
- reworked support for Antora JSON Schemas to avoid exception in log (#687)

=== 0.32.22

- simplified code to handle Antora JSON Schemas to avoid exception in log (#687)
- zoom level in plugin's setting now entered without the percent sign in input fiel to avoid parsing problems when percent sign is missing (#674)

=== 0.32.21

- avoid exception when processing file events for already disposed module (#683)
- fixing exception "`spaces element contains non-spaces-characters`" in lexer (#685)

=== 0.32.20

- avoid exception when looking up items by name and item is in a library (#677)
- regression: don't show AsciiDoc content in libraries on auto-completion (#677)

=== 0.32.19

- auto-complete for images will no longer auto-suggest anchor names (#672)
- transfer long exception messages to Sentry to avoid cut-offs (#672)
- speed up lookup of references by declaring a specific search scope that excludes libraries (#672)
- adopt workaround to prevent JCEF preview error "`Cannot Open the Page/ERR_ABORTED`" to IntelliJ 2021.x. (#658)
- avoid "`Invalid root file`" error when deleting files or folders (#676)

=== 0.32.18

- avoid exception in log when opening AsciiDoc file (#667)
- report build number for IntelliJ EAP releases when submitting information to Sentry (#670)
- update to AsciidoctorJ 2.4.3
- handle auto-completion for MacOS X volume icons (#671)
- use new NIO file API when converting to HTML or PDF file to avoid file name manipulation issues (#666)

=== 0.32.17

- fix classloader problem for JRuby on IntelliJ 2021.x EAP (#664)
- rework issue #658 to restore functionality for zoom and open-links-in-external-browser (#665)

=== 0.32.16

- when un-quoting a selected text to be no longer bold italic or monospaced, the inner text must be at least one char long (#656)
- prevent JCEF preview error "`Cannot Open the Page/ERR_ABORTED`" error in IntelliJ 2020.3.x versions (#658)
- prevent exception when extending word selection for example near a double quote (#661)

=== 0.32.15

- prevent looping/blocking external annotator when post-processing of include error messages (#649)
- prevent unloading of plugin even when no project has been opened yet to avoid loading errors afterwards for icons, resources and schemas (#652)
- forcing re-indexing of AsciiDoc content as previous updates changed parsing/lexing, and the resulting IntelliJ indexes are out of date (#653)
- avoid exception when search for references in Java's root package name (#654)

=== 0.32.14

- prevent issuing a repaint on EDT thread, preventing refresh requests to queue up (#641)
- when embedding iframes in the preview, don't try an in-place update of the contents as this could break the JavaScript for example of YouTube videos (#640)
- prevent lagging UI when refreshing the preview with JCEF and not using in-place refresh (#640)
- JCEF preview is the default for new installations

=== 0.32.13 (preview, available from GitHub releases)

- fixed support for 'tags' key for sources in Antora playbook (#646)

=== 0.32.12

- performance improvement when parsing long lines and words by limiting the length of inline macro names and email addresses (#641)
- improvement data structure for handling a large number of modules (#641)

=== 0.32.11 (preview, available from GitHub releases)

- validate that language for source block is marked injectable by JetBrains (#642)
- performance optimizations on background tasks
- only changes to file in current project's modules will refresh the preview (#641)
- update cached project roots from changed files (#641)

=== 0.32.10 (preview, available from GitHub releases)

- cache project roots to speed up preview and read actions, and to prevent blocking the write thread (#641)
- use read actions with write action priority on all background tasks (#641)

=== 0.32.9 (preview, available from GitHub releases)

- update Kroki support with latest diagrams and attributes, fixing `kroki-plantuml-include` support (#639)
- prevent error messages in log when projects have already been disposed

=== 0.32.8 (preview, available from GitHub releases)

- update preview when project leaves or enters dumb mode so that pending references can be resolved
- prevent NPE when block attributes are not provided
- users can submit error reports anonymously to the plugin's project at Sentry when exceptions occur (#628)
- upgrade to AsciidoctorJ PDF 1.5.4
- Additional reformat option for blank lines after headings (thanks to @c7haki) (#633)
- upgrade to AsciidoctorJ Diagram 2.1.0 and PlantUML v1.2021.0

=== 0.32.7

- show action tool bar in light edit mode (#630)
- fix timestamp when pasting a screenshot from the clipboard (#631)

=== 0.32.6

- don't treat menu items as links
- show soft-wrap notification to all users that don't use it yet

=== 0.32.5 (preview, available from GitHub releases)

- if content in the preview is from an included file, click on the content in the preview opens included file (#557)
- stop implementing an EditorActionHandler as pasting of images seems to work without it to avoid the plugin to appear in EDT freezes when delegating calls (#605, #584)

=== 0.32.4 (preview, available from GitHub releases)

- recognize front matter when parsing page attributes
- add block and paragraph admonition live template (thanks to @rdmueller) (#609,  #611)
- support bibliography anchors alone on a line (#614)
- handling attribute references in block attributes

=== 0.32.3 (preview, available from GitHub releases)

- initial support for light edit mode (#606)

=== 0.32.2

- rework JavaFX handling with JDK 11 to avoid inaccessible exception
- rework parsing of `kbd` macro to prevent runaway escapes
- fixing wrong indexing of section titles with attributes causing "`PSI and index do not match`"
- choose-by-name will find sections with replaced attributes

=== 0.32.1 (preview, available from GitHub releases)

- fix right-click-saves-image in JavaFX preview
- changing development to JDK 11 in line with IntelliJ 2020.3 platform
- don't break section titles with custom IDs or attributes on automatic reformat (#604)
- don't use title with replaced attribute as PsiElement's name as IntelliJ might throw an "`PSI and index do not match`" exception
- formatting of words via actions in the toolbar now works with the cursor placed at the end of the word (#602)

=== 0.31.43 (preview, available from GitHub releases)

- fix highlighting for escaped URL in formatting quotes
- only references with a hash contain a file name, otherwise keep slashes as part of the anchor
- support attributes in inline macro body
- first build on GitHub actions instead of Travis CI (#597)

=== 0.31.42

- when editing content in an Antora module, resolve attributes only within other Antora content of the project (#596)
- enable brace matcher to type closing curly braces automatically
- keep non-ASCII characters in automatic references for section titles (#598)

=== 0.31.41 (preview, available from GitHub releases)

- inspection to warn when inline macro `xref` is used with two colons like a block macro, or a preprocessor like `include` or block macro like `toc` is used as an inline macro (#456)
- level up with latest Spring REST docs macro
- trigger autocomplete for attributes, references and file names when typing characters like `{`, `<` or `:` (#596)
- parse pass-through content in kbd-macro correctly for syntax highlighting
- add attribute _asciidoctorconfigdir_ to auto-completed attributes values

=== 0.31.40 (preview, available from GitHub releases)

- support toc left/right in preview (#590)
- natural cross references should use pointy brackets, not xrefs (#549)
- avoid exception "`Reentrant indexing`" with headings with attributes
- upgrade to AsciidoctorJ 2.4.2/Asciidoctor 2.0.12

=== 0.31.39 (preview, available from GitHub releases)

- added https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/keymap.html[Keymap to user manual] (thanks to @EEM86) (#565, #586)
- adjusted content security policy to allow for data-URIs images in JCEF preview (#229)

=== 0.31.38

- attributes in Antora component descriptor should support null values (#581)

=== 0.31.37 (preview, available from GitHub releases)

- only show changes from the previously installed version in the notification balloon
- integration with DrawIO-Plugin: intent to create empty SVG when DrawIO file is missing and plugin is installed (thanks to @rdmueller) (#575, #578)
- highlight bash code snippets with shell script plugin (#568)
- finalized support for Antora `page-aliases`; now working in preview as well (#574)

=== 0.31.36 (preview, available from GitHub releases)

- more restrictive re-parsing of cells to avoid Inconsistent reparse error (#571)
- fixing NPE when auto-completing xrefs, regression in 0.31.35 (#577)
- links to `about:` URIs not highlighted as errors
- initial support for Antora `page-aliases` to reference moved pages (#574)

=== 0.31.35 (preview, available from GitHub releases)

- dialog to paste an image from clipboard allows adding the width (thanks to @martingreilinger) (#412, #563)
- if an Antora xref misses a file extension, show a warning in the editor and offer a quick-fix if possible (#480)
- support attribute substitution in docinfo header and footer (#567)
- show notification with the latest changes on plugin updates
- passthrough content can be escaped with a backslash for syntax highlighting/parsing
- add support for the alt text attribute in the PasteImageDialog (thanks to @martingreilinger) (#570, #566)
- limit search depth when attribute is declared in a lot of files with different values and plugin tries to resolve a file reference
- don't create temporary files in workspace for diagrams when previewing in the browser

=== 0.31.34 (preview, available from GitHub releases)

- dialog to paste an image allows adding the width for the image (thanks to @martingreilinger) (#412, #559)
- upgrade to asciidoctorj-diagram 2.0.5 (thanks to @pepijnve) (#561)

=== 0.31.33

- prevent blank preview on Windows when user folder contains non-ASCII characters (#543)

=== 0.31.32 (preview, available from GitHub releases)

- for nested includes, highlight errors in the parent files (#550)
- a number before a punctuation mark treated as end of sentence only when at end of a line (#470)
- fix `linkcss` support when no `stylesdir` has been defined (#556)

=== 0.31.31 (preview, available from GitHub releases)

- support `linkcss` attribute for custom stylesheets in the preview (#556)

=== 0.31.30

- fix link to JavaFX preview documentation (#555)

=== 0.31.29

- fix link to JCEF preview documentation (#555)
- fix description attribute inspection for Antora documents (regression to #469)

=== 0.31.28 (preview, available from GitHub releases)

- support anchors and attribute references in section titles (#469)
- upgrade to AsciidoctorJ 2.4.1
- internalize classes so JavaFX preview continues to work in IntelliJ 2020.3 and Android Studio 4.2
- update IntelliJ API usage to be in-line with upcoming 2020.3
- support includes in lists
- handle comments in header lines correctly

=== 0.31.27

- handle line comments in enumerations
- handle line comments with cell separator characters in tables
- when clicking on relative links in the preview, support relative links to parent folder
- fix auto-completion for images for Antora

=== 0.31.26 (preview, available from GitHub releases)

- Regression: keep temporary diagram files in a temporary folder for JCEF preview (#548)

=== 0.31.25 (preview, available from GitHub releases)

- block types should never be treated as setext style section header (#545)
- support SVG diagrams for PlantUML in JCEF preview (#548)
- for inlined SVGs and diagrams, redirect links to workspace files (#548)

=== 0.31.24 (preview, available from GitHub releases)

- fix highlighting where table cells have no spaces in front (#545)
- edge cases for highlighting inline macros with blanks (#546)

=== 0.31.23 (preview, available from GitHub releases)

- an empty line ends a list, even a multilevel list (#542)

=== 0.31.22 (preview, available from GitHub releases)

- improved spelling and grammar checking for reference texts (#539)

=== 0.31.21 (preview, available from GitHub releases)

- fixed incorrect parsing of setext style section titles (#535)
- backport CSS table fix from upcoming Asciidoctor release 2.0.11 (#537)

=== 0.31.20

- support AsciidoctorJ extensions in the preview (#532)
- support numeric attribute names in `antora.yml` AsciiDoc attributes (#258)

=== 0.31.19 (preview, available from GitHub releases)

- pasting image from the clipboard remembers previous selection for file type and target folder (#477)
- fix highlighting to distinguish a cell with vertical alignment from title in tables (thanks to @valhallasw) (#529)
- when saving an image from the clipboard, changed file name in textbox should take precedence (#530)
- fix occasionally broken autocomplete of macros at the end of line (#526)

=== 0.31.18 (preview, available from GitHub releases)

- regressions grammar check: end-of-sentences not forwarded to grammar check, text in cells not grammar or spell checked (#528)

=== 0.31.17 (preview, available from GitHub releases)

- fix handling multiple unconstrained formattings in a single row (#528)
- within AsciiDoc files, don't report well-known attribute names as spelling errors (#528)
- remove unconstrained formatting syntax before spell checking content (#528)

=== 0.31.16 (preview, available from GitHub releases)

- fix autocomplete for incomplete macros in lines with more marcos and/or brackets (#526)
- page attributes like description and title are spell checked and validated (#527)
- descriptions longer than 155 characters will get a warning (#527)

=== 0.31.15 (preview, available from GitHub releases)

- add intention to refactor single-line admonition to block-style admonition (#514)
- Upgrade to asciidoctorj 2.4.0, JRuby 9.2.12.0 and Rouge 3.21.0
- allow block macros after continuations in lists (#524)

=== 0.31.14 (preview, available from GitHub releases)

- support for diagrams and PDF will be downloaded on-demand (#515)

=== 0.31.13 (preview, available from GitHub releases)

- support of JSON schema for Antora playbooks, support `start_paths` property
- move Asciidoclet to separate plugin (#521)

=== 0.31.12 (preview, available from GitHub releases)

- highlighting and spell checking improved for arrows
- fix resolving of references by their titles
- support of JSON schema for Antora playbooks
- avoid blocking lock when switching AsciiDoc editor when trying to save contents of changed documents (#520)

=== 0.31.11 (preview, available from GitHub releases)

- publish file information to allow status with a filename in IntelliJ Discord plugin (thanks to @NonNullDinu) (#518)

=== 0.31.10 (preview, available from GitHub releases)

- don't lose focus of editor for JCEF preview (#517)

=== 0.31.9 (preview, available from GitHub releases)

- first support for Asciidoclet (#103)
- don't show hint to install JavaFX when JCEF is available
- Most recent 2020.2 EAP builds suggest that JavaFX will no longer pre-bundled with the IDE, instead JCEF will be included. Docs updated with link to https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins[JavaFX for plugins^]
- workaround for JCEF preview disappearing, workaround of restoring the preview component (#517)

=== 0.31.8 (preview, available from GitHub releases)

- mark indexes to be rebuilt due to AST changes (#508)

=== 0.31.7 (preview, available from GitHub releases)

- declare intellilang features as optional dependency
- declare JavaFX as optional dependency
- add notification that JCEF can be enabled if it is available and user is using Swing preview
- show block type of current block, in structure view don't pick look it up from a child element (#511)
- reworking handling of list items and their contexts to prevent false positive list items and headlines in editor's AST (#508)

=== 0.31.6 (preview, available from GitHub releases)

- simplify JavaFX image preview to work with standard `file:` URLs (#390)
- don't re-render editor previews in background (#390)
- don't allow in-place upgrading of plugin until further testing (#512)

=== 0.31.5 (preview, available from GitHub releases)

- implementing save generated image and zoom for JCEF preview (#390)

=== 0.31.4 (preview, available from GitHub releases)

- avoid error "`Directory index is already disposed for Project`"
- a continuation can't be followed by a heading (#508)
- when renaming or moving a file, update the folder and file name for the preview (#506)
- supporting `rouge` as code syntax highlighter in preview. Documents can now override the code highlighter. Improved code syntax highlighting for preview in dark mode (#505)
- workaround for IndexOutOfBoundsException when on MacOS X, possibly due to window manager / accessibility issues (#499)

=== 0.31.3 (preview, available from GitHub releases)

- fix showing icon macros in preview in Antora mode
- handling null values in Antora module descriptor, parsing special values `~` and `@` (#504)
- Implement first version of JCEF preview browser; this is still experimental (#390)

=== 0.31.2 (preview, available from GitHub releases)

- increase compatibility with Grazie grammar checker in 2020.2
- updated deprecated methods in plugin's Java code
- fixing paste-image-from-clipboard for 2020.2 EAP (#486)
- make AsciiDoc a dynamic plugin that doesn't require restarting the IDE on installation. Restart still necessary for uninstall/upgrade (#391)
- fix parsing of second level enumeration in the editor
- titles parse references

=== 0.30.77 (preview, available from GitHub releases)

- improved support for URIs starting with `file:`, allowing to use them as an `imagesdir` attribute (#498)
- fix intellisense and link checking for images in other Antora modules (#500)

=== 0.30.75 (preview, available from GitHub releases)

- parse preprocessor macros like `ifdef` in document header with highlighting of variables and autocomplete
- for language injection the error highlighting can be suppressed in the settings
- auto-complete source block when cursor is at the end of block attributes (#494)
- suggest languages when typing a comma as in `[source,]` (#494)
- don't suggest creating a missing file if it is an image (#496)
- don't reporting a missing image if the imagesdir is set in the same file (#497)
- don't reporting a missing image for data URIs (#497)

=== 0.30.74 (preview, available from GitHub releases)

- log errors to event log when Antora YAML file can't be parsed
- force a refresh of any visible AsciiDoc preview if a file in the project has been changed, enabling working in split views and multiple editors (#492)

=== 0.30.73

- Don't report broken file reference for YouTube and Vimeo video macros (#490)

=== 0.30.72 (preview, available from GitHub releases)

- Fix displaying PlantUML images in Antora environment when image directory is present (#489)

=== 0.30.71 (preview, available from GitHub releases)

- bundled font "Droid Sans Mono" for preview in browser; bundled "`Noto Serif`" and "`Open Sans`" for JavaFX preview in IDE and in browser. Removed DejaVu Sans and DejaVu Serif from plugin bundle. (#478)
- avoid logging `ProcessCanceledException` when rendering AsciiDoc for example in validation (#481)
- provide custom stylesheet for the preview using attributes `stylesheet` and `docinfo` (#487)

=== 0.30.70

- avoid NPE when auto-completing a local anchor in an Antora project (#481)
- upgrade to asciidoctorj-diagram 2.0.2 and asciidoctorj 2.3.0. This also upgrades to PlantUML 1.2020.6
- avoid exception when resolving temporary image file name for preview in the browser
- rebuild indexes after lexer/parser changes (#467)

=== 0.30.69

- add support for PacketDiag, RackDiag, Vega, Vega-Lite and WaveDrom (thanks to @Mogztter) (#422)
- set attributes document related attributes like `docname` for preview (#475)
- show notification about a possibly blurry preview also on Linux if display is scaled (#464)

=== 0.30.68 (preview, available from GitHub releases)

- avoid exception when creating a cover image for PDF
- find-grained read/write locking when creating preview, HTML or PDF
- allow incremental parsing for sections
- support inline anchors in regular text (#469)
- adding incremental table parsing on cell-level (#467)
- fixing indents for verse after reformat (#467)
- support definitions with two colons in the term (#472)
- adding table cell as re-parseable element in PSI tree (#467)

=== 0.30.67 (preview, available from GitHub releases)

- avoid NPE in Antora mode when referencing an image in another component and current component doesn't have an imagesdir folder (#468)
- suport `xref` attribute for images

=== 0.30.65 (preview, available from GitHub releases)

- fix issue when displaying block image macro in preview for Antora (#441)
- avoid deadlock when creating PDF/HTML; show cancelable popup
- when preparing the preview for Antora, calculate image path from `imagesdir` (#468)

=== 0.30.64 (preview, available from GitHub releases)

- double-check spaces before creating formatting model (#463)

=== 0.30.63 (preview, available from GitHub releases)

- prevent scope-enlarger to break refactorings like introduce-variable (#466)
- prevent parsing to mis-align tokens after a `+` that could lead to their removal upon re-format (#463)

=== 0.30.62 (preview, available from GitHub releases)

- when referencing images in other Antora modules, assume image family for reference
- refactoring resolving Antora targets for images and xrefs for HTML preview; now also works for PDFs (#441)
- avoid deadlock when creating PDF/HTML; show cancelable popup
- retrieve `reftext` or `navtitle` from page attributes when xref doesn't have a text (#441)
- allow the default zoom level to be configurable for JavaFX preview (#444)

=== 0.30.61 (preview, available from GitHub releases)

- support find-references for Antora family names
- adding a JSON schema for antora.yml to provide auto-completion, validation and quick-documentation (#461)
- don't pick the latest version when referencing a local partial or module (#462)
- support Antora xref syntax for PlantUML block macro as there is an extension for that

=== 0.30.60 (preview, available from GitHub releases)

- allow links containing only version and page file name (#405)
- check links even when anchor contains an unresolvable attribute
- given an Antora partial and a local anchor, search the complete project for a reference when trying to resolve it
- avoid NPE when an Antora component descriptor doesn't include a version (#460)
- check links for files in block, inline and preprocessor macros
- enlarge search scope for finding references to all AsciiDoc documents in project independent of project's module dependencies

=== 0.30.59.1

- prevent parsing to mis-align tokens after a `+` that could lead to their removal upon re-format (#463)

=== 0.30.59

- rebuild indexes for bibliographic references (#459)

=== 0.30.58 (preview, available from GitHub releases)

- support bibliographic references when validating links and finding references (#459)
- when an Antora xref contains a component name, it will always link to the "`latest`" version (#405)

=== 0.30.57

- re-enable setting of attributes in plugin settings on IntelliJ 2020.1+ (#458)

=== 0.30.56 (preview, available from GitHub releases)

- support PlantUML diagrams in open blocks
- fixing support for distributed Antora components when linking to a "`latest`" version (#405)

=== 0.30.55 (preview, available from GitHub releases)

- handling linking and including to "`latest`" version on Antora projects (#405)

=== 0.30.54 (preview, available from GitHub releases)

- improving performance when editing large tables (#453)

=== 0.30.53 (preview, available from GitHub releases)

- fixing performance regression when editing large documents (#453)

=== 0.30.52 (preview, available from GitHub releases)

- avoid confusion in lexer about starting and ending listings if there are blanks in a line starting with dashes
- avoid infinite recursion with too many attributes in anchors
- allow fully distributed components for Antora, where files for a module exist in multiple folders (#405)
- fix directories for antora modules to be resolved to wrong path
- don't try to resolve links traversing to a parent directory
- support version numbers and attributes in Antora xrefs (#377)

=== 0.30.51 (preview, available from GitHub releases)

- find-references shows also all declaration of attributes with the same name
- search-everywhere also finds attribute declarations
- fix monospace formatting in description lists
- allow curly braces in block IDs, as they can be used as attributes
- don't try to resolve links with unresolved or ambiguous variants; don't resolve links starting at root level or lead to URLs, resolve attributes in anchors
- parse attributes in anchor definitions

=== 0.30.50

- index TODOs only in comments for TODO window (#452)
- improve parser/lexer to support continuation after hard break (again)
- new live template to surround some selected text with tag comments to use in an include (#450)

=== 0.30.49 (preview, available from GitHub releases)

- improving link validation with Antora (#449)
- improving passthrough detection in lexer (#449)

=== 0.30.48 (preview, available from GitHub releases)

- don't create an anchor via intent for a section when one is already present (#446)
- improve parser/lexer to support continuation after hard break
- fix focus problems when switching preview modes using keyboard macros (#448)
- improve checking reference anchors and resolving (#436)
- recognize open block with style source as listing (#401)
- Resolve two colons (`::`) as ROOT module in Antora modules instead of current module (#449)

=== 0.30.47 (preview, available from GitHub releases)

- speedup lookups, validations and search-everywhere by using stub-based in indexes for block IDs and sections (#439)
- allow creating missing files from link and xref inline macros (#440)
- allow callouts with a dot instead of a number (`<.>`) to be parsed and re-formatted correctly (#443)

=== 0.30.46 (preview, available from GitHub releases)

- xrefs can point to local anchors without a prefixed hash (`#`) (#427)
- support adding section titles if anchor points to block ID (#378)
- supporting front matter style header in AsciiDoc files (#434)
- treat numbers correctly for constrained/unconstrained formatting detection in syntax highlighting
- intent to add the automatic block ID explicitly to a section (#435)
- check the pattern of block IDs and reference anchors, also test if anchors resolve (#436)
- suppress inspections for a single line or a complete file using a line comment (#436)
- don't inline includes that have attributes set as they will be lost during inlining (#437)

=== 0.30.45 (preview, available from GitHub releases)

- inline includes for sub-directories and Antora prefixes (#429)
- extend selection now stops at more delimiters and withing delimiters (#425)
- enlarge search scope for references to full project as documents (#427)
- warn about anchors that reference a section without a block ID and offer a quick-fix to add the block ID to the section (#427)
- warn about links that don't resolve for their file or their anchor (#427)

=== 0.30.44 (preview, available from GitHub releases)

- fixing broken folding of attributes (#423)

=== 0.30.43 (preview, available from GitHub releases)

- add folding for HTML entities (like `\&amp;`) and unicode characters (like `\&#x2020;`) (#423)
- avoid OOM when for example parsing contents with block markers that aren't trimmed (#424)

=== 0.30.42 (preview, available from GitHub releases)

- check monospace and italic text as part of a sentence
- show attribute name in dumb mode for folded value (#416)
- upgrade to asciidoctorj-pdf:1.5.3
- ignore non-text parts of section headings when passing contents on to grammar checker
- smart-enter to complete `include`-macros and add `leveloffset` (#379)
- smart-enter to complete `xref`- and `link`-macros to add the referenced section title in the brackets (#378)
- handle attribute declaration with blanks; handle attribute names case-insensitive (#398)
- support Antora 2.3 component attributes (#385)
- highlight and autocomplete attribute references in links

=== 0.30.41.1

- avoid OOM when for example parsing contents with block markers that aren't trimmed (#424)

=== 0.30.41

- fix handling comments in header lines after a title (#414, #415)
- adding folding support for attributes showing their value (#416)
- inline attributes can have multi-line content in brackets and continuations (#406)
- re-enable grammar check for mono and italic text
- when renaming block IDs, apply the correct validation pattern to allow for example `:` and `.` as part of IDs
- don't mistake includes of external URLs as Antora style includes (#417)

=== 0.30.40

- fix drag-and-drop of code snippets (#413)
- export-to-html creates PlantUML diagrams so that they show up when opening the HTML in the browser, the default is the directory of the source file (#409)
- prevent triggering paste-image when pasting text from a word processor
- instruct Grazie to check also comments in preparation for 2020.1 (#408)
- ignore start of line comment for Grazie grammar check
- adding folding for predefined attributes for character replacements

=== 0.30.39

- implement interface of the latest Grazie preview (#408)
- fix parsing closing brackets in attributes (#411)
- don't assume end-of-sentence inside a line if followed by a digit
- fix rendering diagrams in browser preview when multiple imagesdirs set in document (#409)

=== 0.30.38

- titles for listings and blocks are highlighted and re-formatted correctly if they start with a dot; improved parsing of titles (#400)
- allow pasting an image from the clipboard with standard keyboard shortcut Ctrl+V (#402)
- auto-suggest block and section IDs when auto-completing anchors in links (#403)

=== 0.30.37 (preview, available from GitHub releases)

- tuning highlighting of references to Java classes and packages
- avoid NPE when resolving file references (#397)
- upgrade to asciidoctorj-pdf:1.5.0
- handling exception for missing class PlatformImpl when detecting JavaFX (#399)

=== 0.30.36 (preview, available from GitHub releases)

- show editor notification to user to enable soft wrap in IDE settings when toggling soft wrap in the editor toolbar multiple times (#395)
- support tags for include for rename and go-to-declaration (#322)
- italic and monospaced inline text references files, Java classes and packages

=== 0.30.35 (preview, available from GitHub releases)

- support multiple definitions of imagesdir in document for the preview (#316)

=== 0.30.34

- preventing unbalanced tree error when parsing a block without a delimiter (#394)

=== 0.30.33 (preview, available from GitHub releases)

- optimizing lexer for performance (#389)
- ensure binary compatibility with IntelliJ 2020.EAP
- instrument parser for debug and trace logging (#394)

=== 0.30.32 (preview, available from GitHub releases)

- updated Markdown listing inspection to handle titles (#387)
- tuning folding of custom markers and blocks without delimiters (#384)
- show warning in editor if a target file name used more than once by Asciidoctor Diagram (#388)

=== 0.30.31

- highlighting for URLs and attributes in inline marco attributes (#383)
- autocompletion for link attribute contents (#383)
- restrict antora autocompletion to Antora supported macros (include, xref, image) (#373)
- support inline image macro with Antora autocompletion (#373)

=== 0.30.30 (preview, available from GitHub releases)

- support file paths for include-macro starting with `./` (#373)
- add Antora pages family for autocomplete (#373)
- Antora image-macro auto-completes resource IDs, but not longer family names (#373)
- preview Antora images from outside of current module (#373)
- upgrade to asciidoctorj-pdf:1.5.0-rc.2
- handle Antora version numbers in antora.yml even if they are unquoted numbers (#381)

=== 0.30.29 (preview, available from GitHub releases)

- support brackets inside macro for highlighting and formatting
- highlight attribute references for ifdef/ifndef (#380)
- parse contents of inline ifdef/ifndef (#380)
- support autocompletion for antora prefixes (#373)
- do not nest blocks inside literal blocks
- block attributes must not be followed by characters on same line
- populating a first set of Antora's `page-*` attributes for preview (#373)

=== 0.30.28 (preview, available from GitHub releases)

- support xref with anchors, including auto-generated IDs for sections (#373)
- support Antora module and component prefixes for blocks and inline macros (#373)
- support Antora module and component prefixes for includes (#373)

=== 0.30.27 (preview, available from GitHub releases)

- support Antora families like `example$` and `partial$` for macros in the editor. Only module-local references supported for now. (#373)
- support Antora families like `example$` and `partial$` for include macros in the preview. Only module-local references supported for now. (#373)

=== 0.30.26 (preview, available from GitHub releases)

- restrict list of suggestions for images if the file is part of an Antora module (#373)
- unit tests to recognize Antora directory structure (#373)
- when Antora is detected, set icons attribute to font as default (#373)

=== 0.30.25 (preview, available from GitHub releases)

- added notification in the editor with a link to GitHub Wiki when the plugin recognizes Antora (#373)
- on pasting images in AsciiDoc files that are part of Antora modules, default to the images folder (#330)
- fix image preview when using asciidoctor-diagram and imagesdir attribute that traverses to a parent folder (#345)

=== 0.30.24 (preview, available from GitHub releases)

- scroll bar of JavaFX preview now dark in Darcula theme (#372)
- experimental support for Antora: pre-populating the _imagesdir_, _examplesdir_ and _attachmentsdir_ attribute (#373)
- experimental support for Antora: supporting _xref_ inline macro for references inside same module (#373)
- indexing of attribute declarations within a project to allow faster autocompletion of attributes

=== 0.30.23 (preview, available from GitHub releases)

- re-added option in settings to disable showing errors in the editor (#375)
- support URLs in inline macros
- experimental support for Antora: pre-populating the _partialsdir_ attribute (#373)

=== 0.30.22 (preview, available from GitHub releases)

- Lexer/Highlighting: allow pre-block elements after anchor
- Editor: allow language injection for passthrough content (#353)
- upgrade to AsciidoctorJ 2.2.0
- process pre-processor macros in .asciidoctorconfig (#374)

=== 0.30.21

- support spring-rest-docs in Kotlin style gradle projects (#371)

=== 0.30.20

- update to AsciidoctorJ PDF v1.5.0-beta.8
- adding PDF theme attributes to quick documentation
- upgrading to Grazie 2019.3-6.2.stable
- fixing live templates `ad-doc-header-with-attributes`, `ad-list-checklist` and others (thanks to @javaru) (#369)

=== 0.30.19 (preview, available from GitHub releases)

- added a bundled dictionary for common Asciidoctor terms
- added quick fix for missing include file (#363)
- fix darcula kbd and coderay line numbers background color (thanks to @bric3) (#368)
- preserve custom CSS classes (aka roles) for preview window

=== 0.30.18

- fix extract include of snippet with language injection
- fix `subs` option for diagrams when using Kroki (thanks to @Mogztter) (#365, #366)

=== 0.30.17 (preview, available from GitHub releases)

- update to AsciidoctorJ PDF v1.5.0-beta.7
- tuning spell checking for Grazie for reference and link texts (#97)
- allow extract include of snippet with language injection
- added some live templates `ad-config...` for configuration attributes (thanks to @rdmueller) (#358, #361)
- show documentation for attributes also when cursor is set in attribute value, not only when cursor is placed in attribute name
- fix background color for code/monospace in darcula theme (thanks to @bric3) (#364)

=== 0.30.16

- upgrading to version 2019.2-5.3.stable of the https://plugins.jetbrains.com/plugin/12175-grazie/[Grazie plugin], improving performance and spell checking in different languages (#97)

=== 0.30.15 (preview, available from GitHub releases)

- support `+++[link=...]+++` in browser preview for navigation to images and other AsciiDoc sources of the project (#360)
- support interactive mode SVG in browser and JavaFX preview (#360)

=== 0.30.14 (preview, available from GitHub releases)

- adding the Asciidoctor logo as the plugin's logo (thanks to @ardlank) (#356, #357)
- experimental support for grammar checking in different languages using the https://plugins.jetbrains.com/plugin/12175-grazie/[Grazie plugin] (#97)

=== 0.30.13 (preview, available from GitHub releases)

- fixing exception when using keys to toggle formatting (#242)

=== 0.30.12 (preview, available from GitHub releases)

- quick-fix for markdown style listings (thanks to @FatihBozik) (#297, #355)
- improve formatting bold/italic/... using editor actions (#242)
- toggle formatting on selected text using formatting characters (#242)

=== 0.30.11 (preview, available from GitHub releases)

- upgrade to asciidoctorj-pdf:1.5.0-beta.6
- add HTML export to editor actions (thanks to @balabarath) (#349, #354)
- avoid exception "`Already disposed: Project`" when closing one out of many currently open projects

=== 0.30.10 (preview, available from GitHub releases)

- first version of improved "`Extend Selection`" (#341)
- preserve cursor position and selection when toggling title (thanks to @Mogztter) (#341, #344)
- improved cursor placement and selection for formatting actions like bold/italic (#341)
- add support for kroki.io when rendering diagrams in the preview (thanks to @Mogztter) (#287, #346)
- include content via URLs (https or http) when `allow-uri-read` attribute set (#348, #138)
- allow configuration of safe mode in plugin's configuration (thanks to @bit-man) (#347, #351)
- support `:prewrap!:` in preview so that listings and other pre-formatted content don't wrap (#350)

=== 0.30.9 (preview, available from GitHub releases)

- auto-save files when switching to AsciiDoc editor to ensure preview shows latest content
- clean up handling of input streams throughout the plugin
- don't switch focus to editor when browsing for example TODO list (#332)
- add menu bar item to mark/highlight selected text (#134)
- clean up stream resource leak (#342)

=== 0.30.8 (preview, available from GitHub releases)

- highlight warnings for Spring REST Docs at line in editor
- upgrade to JRuby 9.2.8.0 to avoid assertion errors when creating PDFs (#337)

=== 0.30.7

- upgrade to asciidoctorj-pdf:1.5.0-beta.5 (#325)
- allow unset of attribute after the first colon
- regression: when clicking an external link in the preview, don't navigate to external site, but open it in external browser only (#335)
- regression: when right-clicking on an image, show popup to save image (#335)

=== 0.30.6

- support attribute references in block and block macro attributes and titles (#327)

=== 0.30.5 (preview, available from GitHub releases)

- fix singleton for prepending .asciidoctorconfig information (#325)

=== 0.30.4 (preview, available from GitHub releases)

- while JavaFX preview forces PNG diagram for readability, browser and PDF should use diagram in the format specified in the source (#325)
- add editor notification with link to Wiki page for spring boot restdocs (#312)
- fix chapter numbers for included snippets (#312)

=== 0.30.3 (preview, available from GitHub releases)

- support operation block macro in https://docs.spring.io/spring-restdocs/docs/current/reference/html5/[spring-restdocs] and auto-detect the snippets folder (#312)
- prepended config via plugin shouldn't add blank line that breaks document title (#325)
- upgrade to asciidoctorj-pdf:1.5.0-beta.4 (#325)
- support HTML blanks and HTML entities in image file names for preview (#328)

=== 0.30.2 (preview, available from GitHub releases)

- support .asciidoctorconfig for PDF creation (#325)
- fix rendering problem with LaTeX style math (#326)
- improved logging for math problems, plus popup hint with MathML error message in preview (#326)

=== 0.30.1 (preview, available from GitHub releases)

- fix 'unable to read file' when creating a PDF and working with extensions (#325)

=== 0.30.0 (preview, available from GitHub releases)

- support creating a PDF from the IDE based on asciidoctorj-pdf:1.5.0-beta.2 (#325)

=== 0.29.11 (preview, available from GitHub releases)

- No end of sentence after a digit
- no end of sentence after colon in middle of line, but preserve line break after colon at end of line
- handle pre-block for block-macros when creating references

=== 0.29.10

- fixing dependency problem when running on IDEs like RubyMine (#323)

=== 0.29.9

- tuning end-of-sentence detection when potential end of sentence followed by a lowercase character

=== 0.29.8 (preview, available from GitHub releases)

- add slash also for mouse and enter key when selecting path elements during auto-completing (#320)
- support unset attribute in lexer, parser and highlighting

=== 0.29.7 (preview, available from GitHub releases)

- support `asciidoctorconfigdir` in referenced attributes when autocompleting directories and files (#320)

=== 0.29.6 (preview, available from GitHub releases)

- support autocomplete for includes with attributes in listings (#320)
- improved autocomplete for directories by handling '/', tab and other characters intuitively (#320)

=== 0.29.5 (preview, available from GitHub releases)

- support legacy `+` for continuations in attribute value declarations, with quickfix to convert (#318)
- support include block macro after level-0 headers, support appendix in book style (#319)

=== 0.29.4 (preview, available from GitHub releases)

- preview no longer increments figure numbers by two instead of one (#317)

=== 0.29.3 (preview, available from GitHub releases)

- support syntax highlighting within definition list (#307)
- support asciidoctorconfigdir attribute replacements in dependent variables for macros (#307)
- restore navigation on path elements for nested attributes in macros (#307)
- don't add new line after heading for attributes (#314)
- allow attributes to be resolved in file links, allow absolute paths in links and includes (#307)
- add highlighting for attribute references in several descriptions (#307)

=== 0.29.2 (preview, available from GitHub releases)

- restore standard copy-and-paste functionality if contents can be represented as text
- avoid mistaking typographic quote end as start of monospace
- recognize title and other block starting elements after a continuation
- prevent out of bounds exception when handling warning messages returned from Asciidoctor parsing (#311)
- support author information and attributes in documentation header for reformatting (#314)
- support attribute references in definition list and `++`-escaped links (#307)

=== 0.29.1 (preview, available from GitHub releases)

- improve handling of emails and links in editor for Ctrl+click and make-link action (#307)
- add navigatable web references for attribute values, also decode HTML entities (#307)
- allow attribute references nested in attribute declarations (#307)
- no-flicker preview for JavaFX will is now enabled by default (#241)

=== 0.28.27

- restore standard copy-and-paste functionality if contents can be represented as text

=== 0.28.26

- restore compatibility with non-Java IDEs, allow pre-bundling of plugin with IDE (#309)

=== 0.28.25

- security review for in-browser preview, adding mac to prevent browser to retrieve arbitrary file, hiding referrer from externally retrieved resources (#303)

=== 0.28.24 (preview, available from GitHub releases)

- support undo for paste-image and send out notifications to add files to VCS (#298)
- fix rendering of images in flicker-free fast preview (#241)
- prevent NPE when opening AsciiDoc documents or fragments in browser (#303)
- inspection to convert Markdown-style horizontal rules to AsciiDoc-style horizontal rules (thanks to @bbrenne) (#272, #302)

=== 0.28.23 (preview, available from GitHub releases)

- Paste image from clipboard (thanks to @bbrenne) (#298, #300)

=== 0.28.22

- Wrong test name in gutter when running tests, BrowserUrlProvider eagerly works on all files (#301)

=== 0.28.21

- fixing autocomplete for link: when brackets already provided
- avoid flickering Math preview by replacing contents in Preview via JavaScript (#241)

=== 0.28.20

- Linking to Wiki page if JavaFX initialization is stuck (#299)

=== 0.28.19

- prevent "`Initializing...`" message in preview of empty file

=== 0.28.18 (preview, available from GitHub releases)

- detecting a stuck JavaFX initialization (#299)

=== 0.28.17 (preview, available from GitHub releases)

- tuning state resetting for lexer (#289)

=== 0.28.16 (preview, available from GitHub releases)

- adding code style settings for reformat (#289)
- rework inline macro for false positives (#275)
- ifdef/ifndef/endif body references attributes in (#275)
- reset formatting after a blank line (#289)
- navigate to auto-generated IDs of sections

=== 0.28.15 (preview, available from GitHub releases)

- respect imagesdir when resolving image paths in source file (#275)
- resolve attribute names in macro definition (#275)
- auto-completion of files should include ".." (#253)

=== 0.28.14 (preview, available from GitHub releases)

- lexer and highlighting support blocks with unbalanced or no delimiters (#289)

=== 0.28.13 (preview, available from GitHub releases)

- lexer and highlighting support several new tokens (callouts, admonitions, markdown style listings, definition lists) (#289)
- reformat supports break-after-end-of-sentence, but still experimental (#289)

=== 0.28.12 (preview, available from GitHub releases)

- rework zoom for touchpads (#295)
- added setting to disable error/warning highlighting in editor (#296)

=== 0.28.11 (preview, available from GitHub releases)

- inject absolute location of .asciidoctorconfig file (thanks to @rdmueller) (#280)
- support for '.adoc' extension of .asciidoctorconfig file (thanks to @rdmueller) (#293, #294)
- new table size selector using the mouse (thanks to @bbrenne) (#92, #290)
- create tables from clipboard and converting CSV/TSV format to AsciiDoc (thanks to @bbrenne) (#92, #290)
- better zoom support for touchpads, adding min/max zoom level (#295)

=== 0.28.10 (preview, available from GitHub releases)

- inlining and extracting of includes (#271)

=== 0.28.9 (preview, available from GitHub releases)

- experimental support reformatting of AsciiDoc sources, needs to be enabled in the settings (#289)
- "`Open in Browser`" now opens the contents of the preview in the selected browser including rendered diagrams (#82)

=== 0.28.8 (preview, available from GitHub releases)

- investigating problem that parts of the UI are not refreshing (#288)

=== 0.28.7

- Save image context menu now showing up on macOS (thanks to @wimdeblauwe) (#283)

=== 0.28.6

- fixing NPE introduced when detecting potentially blurry preview (#284)

=== 0.28.5 (preview, available from GitHub releases)

- support zoom in preview window (thanks to @ianflett) (#199, #279)
- save generated images from preview (thanks to @bbrenne) (#245, #278)

=== 0.28.4 (preview, available from GitHub releases)

- autocompletion for attributes and attribute references (`:attr:` and `\{attr}`) (thanks to @bbrenne) (#277)
- renaming and find-usage for attribute names (#243)
- upgrade to AsciidoctorJ 2.1.0 and Asciidoctor 2.0.10
- statement completion adds newline if at end of file (#276)
- listing and other delimiters recognized at end of file (#276)

=== 0.28.3

- brace matching for attribute start/end (`:attr:` and `\{attr}`)
- syntax highlighting for enumerations (`.`)
- fixing "`Edit Fragment...`" for listings (#276)

=== 0.28.2

- fixed parsing for old-style headers (#274)

=== 0.28.1 (preview, available from GitHub releases)

- new automated release mechanism, also EAP plugin repository

=== 0.26.20 (preview, available from GitHub releases)

- link to Wiki how to fix blurry preview (#213)
- monospace-bold preview now working (#193)

=== 0.26.19 (preview, available from GitHub releases)

- tuning parsing and documentation (#267)
- new inspection to shorten page break (`<<<`) where possible
- `\link:file#id[]` now with navigation and autocomplete (thanks to @bbrenne) (#273)

=== 0.26.18 (preview, available from GitHub releases)

- resolve the last reference in structure view as this will be the file; the others are the subdirectories (#267)
- refactoring or shortened descriptions; now in sync for structure view and breadcrumbs (#267)
- allow browser to cache static content to avoid flickering (#267)
- allow more block types, supporting nested blocks, parsing content within blocks (#267)
- rework folding to show first significant line in block (#267)

=== 0.26.17 (preview, available from GitHub releases)

- support escaping with backslash (`\`) in editor, avoiding highlighting
- move to released markdown-to-asciidoc version 1.1 to use proper dependency management (#268)
- support spell checking on more elements including quotes, examples and comments (#269)
- fixing autocomplete for file names on `include::[]` within blocks

=== 0.26.16 (preview, available from GitHub releases)

- show includes and images in structure view, adding icon set for breadcrumbs and structure view, tuning contents (#267)

=== 0.26.15

- fixing equals check for disabled injected languages (#266)

=== 0.26.14

- fixing NullPointerException in settings processing (#266)
- supporting pass-through inline content

=== 0.26.13

- update to asciidoctorj-diagram:1.5.18
- breadcrumb support in editor

=== 0.26.12 (preview, available from GitHub releases)

- supporting blanks in block attributes (#255)

=== 0.26.11 (preview, available from GitHub releases)

- adding support for GRAPHVIZ_DOT environment variable (#261)
- adding support for statement completion (ctrl-shift-enter) (#263)
- language injection can now is now enabled by default and can be disabled for specific languages, and will be disabled when the block has an `include::[]` (#255)
- includes are now parsed and highlighted inside code blocks (#255)

=== 0.26.10 (preview, available from GitHub releases)

- Experimental highlighting in code blocks (#255, #262)

=== 0.26.9 (preview, available from GitHub releases)

- upgrading gradle and JetBrains plugin; now use `gradlew runIde` to start the plugin in development mode
- allow user to switch left/right and upper/lower in split view (#136)
- add syntax highlighter to support `\link:file[]` (thanks to @bbrenne) (#259)
- add syntax highlighter to support attribute:value and {attribute reference} (thanks to @bbrenne) (#260)

=== 0.26.8 (preview, available from GitHub releases)

- default file encoding for JRuby now UTF-8 if set file encoding is not supported by JRuby (#174)

=== 0.26.7

- fixing error in tree structure; improving test capabilities for parsing (#174)

=== 0.26.6 (preview, available from GitHub releases)

- improved brace matcher
- ensure that block IDs are part of next section when folding (#174)

=== 0.26.5 (preview, available from GitHub releases)

- decouple read action from event thread to avoid error from IDE (#204)
- highlighting for lexical quotes
- parsing referenced file from reference (#204)

=== 0.26.4 (preview, available from GitHub releases)

- Support for relative path links in preview (#256)

=== 0.26.3 (preview, available from GitHub releases)

- allow folding of sections and blocks (#174)

=== 0.26.2 (preview, available from GitHub releases)

- allow horizontal split view via settings (#136)

=== 0.26.1 (preview, available from GitHub releases)

- adding color settings for syntax highlighting (#254)

=== 0.26.0 (preview, available from GitHub releases)

- support for anchors, block ids and references including linking and refactoring (#252)

=== 0.25.14

- making linking of documents work for standard includes (#204)
- improved formatting when blank lines are edited, also handling spaces at the end of a line (#248)

=== 0.25.13

- support partitial parsing in lexer to avoid flipping formatting in IntelliJ (#248)

=== 0.25.12 (preview, available from GitHub releases)

- adding additional rules for constrained formatting (#248)

=== 0.25.11

- moving from jruby-complete to jruby dependency like AsciidoctorJ did for 2.0 (#250)

=== 0.25.10 (preview, available from GitHub releases)

- improved syntax highlighting for block IDs and references, suppressing message "possible invalid reference" (#249)
- show error message why preview wasn't rendered in preview (#251)

=== 0.25.9

- adding quote handler (#242)
- Tuning highlighting for mono and bullet lists (#244)
- Activating brace highlighting for mono/italic/bold (#244)

=== 0.25.8 (preview, available from GitHub releases)

- Tuning highlighting italic/bold/mono, adding brace matcher in text (#244)

=== 0.25.7 (preview, available from GitHub releases)

- Updating to AsciidoctorJ v2.0.0 that includes Asciidoctor 2.0.8
- adding highlighting for italic/bold/mono (#244)
- adding brace matcher for attributes

=== 0.25.6 (preview, available from GitHub releases)

- Updating to AsciidoctorJ v2.0.0-RC.2 that includes Asciidoctor 2.0.6
- Improved parsing of warnings and errors created by Asciidoctor

=== 0.25.5 (preview, available from GitHub releases)

- Addding error highlight in tree view

=== 0.25.4 (preview, available from GitHub releases)

- restart annotation processing for current file once it gets focused or settings change (#225)

=== 0.25.3 (preview, available from GitHub releases)

- improve offset calculation for .asciidoctorconfig files (#225)

=== 0.25.2 (preview, available from GitHub releases)

- annotate the file in the editor instead of logging to console for asciidoctor messages (#225)

=== 0.25.1 (preview, available from GitHub releases)

- Fixing preview line calculation when using .asciidoctorconfig-files
- Updating to AsciidoctorJ v2.0.0-RC.1 that includes Asciidoctor 2.0.2

=== 0.25.0 (preview, available from GitHub releases)

- Updating to AsciidoctorJ v1.7.0-RC.1 that includes Asciidoctor 2.0.1 and Asciidoctor Diagram 1.5.16

=== 0.24.4

- Fixing preview line calculation when using .asciidoctorconfig-files

=== 0.24.3

- Filter out problematic pass-through JavaScript with Twitter being the first candidate (#235)

=== 0.24.2 (preview, available from GitHub releases)

- Support JDK11 as of IntelliJ 2019.1 EAP (#238)

=== 0.24.1

- Upgrade to AsciidoctorJ 1.6.2 and JRuby 9.2.6.0 (it's still backed by Asciidoctor 1.5.8)
- Upgrade to asciidoctor diagram 1.5.12
- Additional logging to analyze errors (#236)

=== 0.24.0

- Upgrade to AsciidoctorJ 1.6.1 and JRuby 9.2.5.0 (it's still backed by Asciidoctor 1.5.8)
- Upgrade to asciidoctor diagram 1.5.11
- Updated parser for old style multiline headings  to be more specific (#233)
- Added description for old style heading inspection (#233)

=== 0.23.2

- Resource cleanup for Asciidoctor Ruby Extensions (#220)

=== 0.23.1 (preview, available from GitHub releases)

- Updated file icon with less intrusive icon, also introducing SVG for icons (#230)
- Editor notification to switch to JetBrains 64bit JDK (#189)
- Tuning support for Asciidoctor Ruby Extensions (#220)

=== 0.23.0 (preview, available from GitHub releases)

- EXPERIMENTAL: Support Asciidoctor Ruby Extensions when placed in _.asciidoctor/lib_ (#220)

=== 0.22.0

- Update to AsciidoctorJ 1.5.8.1
- Workaround for incompatible plugins (#226)
- Toggle softwraps only available in context menu of AsciiDoc documents (#227)
- Recognize list continuations plus block instead of marking them as old style headings (#228)
- EXPERIMENTAL: supporting _.asciidoctorconfig_ configuration files

=== 0.21.4

- Add official asciidoctor logo (#219)
- Add soft wrap to tool bar (#221)
- Editor Toolbar show status of toggles
- Update to Asciidoctor Diagram 1.5.10 (#215)

=== 0.21.3

- upgrade to MathJAX 2.4.7 (as bundled in AsciidoctorJ 1.5.7)

=== 0.21.2

- Regression: show title of document again (#217)

=== 0.21.1

- allow attributes to be pre-defined in plugin settings (#216)

=== 0.21.0 (preview, available from GitHub releases)

- Update to AsciidoctorJ 1.5.7 and Asciidoctor Diagram 1.5.9
- Treat "line must be non negative" only as a warning (#212)


