= Asciidoctor IntelliJ Plugin Changelog

== About

This document provides a high-level view of the changes introduced by release.

[[releasenotes]]
== Release notes

=== 0.41.10

- Render preamble in preview with a slightly larger font (#1567)
- Use Droid Sans Mono for rendering code in the JCEF preview

=== 0.41.9

- Bump org.asciidoctor:asciidoctorj-pdf to 2.3.13 (#1547)
- Remove code which must not be run in EDT to get compatible with IntelliJ 2024.1 EAP (#1533)
- Speed-up Java references search to parse fewer files
- When renaming Java classes, rename their references in AsciiDoc documents as well
- Fixed calculation of root paths for multi-module projects (#1558)
- New live template for Golang source code snippets (thanks to @dozer111) (#1553)
- Bump org.asciidoctor:asciidoctorj-diagram to 2.3.0 and PlantUML to 1.2024.3 (#1538)

=== 0.41.8

- Workaround for slow EDT warning (#1533)
- Support Windows 11 on ARM (#1537)

=== 0.41.7

- Upgrade Asciidoctorj Diagram to 2.2.17 and PlantUML to 1.2023.13 (thanks to @cachescrubber) (#1525)
- When opening includes from preview, move slow activities to the background (#1517)
- Hide unused AsciiDoc action group in IntelliJ 2024.1 EAP

=== 0.41.6

- Avoid deadlock when creating a new AsciiDoc file (#1502)
- Fix Sentry reporting

=== 0.41.5

- Bump org.asciidoctor:asciidoctorj from 2.5.10 to 2.5.11 (#1499)
- Bump org.asciidoctor:asciidoctorj-pdf from 2.3.9 to 2.3.10 (#1497)
- Bump org.asciidoctor:asciidoctorj-diagram from 2.2.13 to 2.2.14
- Updating embedded Kroki to support symbolator and wireviz diagrams
- Show a hint when the JCEF preview doesn't show when using a remote desktop (#1371)

=== 0.41.4

- Fixing checksum when downloading PlantUML 1.2023.12 for diagrams (#1491)

=== 0.41.3

- Upgrade to PlantUML 1.2023.12 for diagrams (#1491)

=== 0.41.2

- Always add root project folder to avoid a message that the file has been opened outside the project (#1474)

=== 0.41.1

- Add language support for C# which is known as `csharp` by highlight.js (#1474)
- Update Antora default theme (#1473)
- Fall back to root project folder if no module folders have been found to avoid a message that the file has been opened outside the project
- Fix Antora include support on non-Java JetBrains IDEs

=== 0.41.0

- Restore compatibility with latest 2023.3 EAP release

=== 0.40.7

- Restore compatibility with latest 2023.3 EAP release

=== 0.40.6

- Avoid EDT warning when changing plugin settings
- Avoid temporary files in project folder when creating a PDF file (#1446)
- Force re-generating diagrams when create an HTML file (#1446)
- Tuning support for Antora Collector for non-existing folders (#1177)

=== 0.40.5

- Downgrade to PlantUML 1.2023.5 to avoid problems with Ditaa, grapviz and icons (#1446)
- Add Asciidoctor Tabs CSS also when converting to HTML (#1425)
- Add Asciidoctor Tabs darcula CSS theme (#1425)

=== 0.40.4

- Fix exception when installing plugin with already open AsciiDoc file (#1441)
- Avoid accessing index from EDT when initializing the editor
- Avoid empty range when building folding (#1442)
- Reworking editor creation again to avoid error in EDT (#1439)

=== 0.40.3

- Add Asciidoctor Tabs CSS also for Antora themed pages (#1425)

=== 0.40.2

- Expanding or collapsing a section will not scroll the editor or open the included file (#1436)
- Update toolbar elements in the background to remove load from EDT thread
- Reworking editor creation again to avoid error in EDT (#1439)
- Support Asciidoctor Tabs extension out-of-the box (#1425)
- Avoid NPE and wrong thread when converting Markdown content (#1440)

=== 0.40.1

- Rework fix for IntelliJ 2023.3 EAP compatibility. Dropping compatibility for 2023.1 and earlier. (#1439)

=== 0.39.9

- Fix IntelliJ 2023.3 EAP compatibility (#1439)
- Reworked parsing of definition lists (#1432)

=== 0.39.8

- Fixing Pandoc download loop on macOS (thanks to @mlasevich) (#1429)
- Bump org.asciidoctor:asciidoctorj-diagram from 2.2.11 to 2.2.13 (#1433)

=== 0.39.7

- Workaround for tree parsing to avoid errors (#1432)

=== 0.39.6

- Improve lexing of URLs in description lists
- Removing EDT workaround (#1424)
- Reworking parsing to avoid unbalanced tree error (#1432)

=== 0.39.5

- Upgrade to embedded Mermaid 10.4.0 (#1430)
- Handle opening the PDF in the event dispatcher thread (#1431)

=== 0.39.4

- Fix class cast exception when parsing Antora information (#1422)
- Fix regex problem when `idseparator` contains regex special characters (#1423)
- Workaround for EDT error message when reopening a project (#1424)

=== 0.39.3

- Enhanced parsing of description lists, leading to an improved AST and grammar checking (#1419)

=== 0.39.2

- Fix detection of Apple M processors when downloading Pandoc (#1413)

=== 0.39.1

- Dropping support for IntelliJ 2022.1
- Bump asciidoctorj-pdf from 2.3.7 to 2.3.9 (#1392)
- Don't highlight attributes in equations (#1409)
- Bump org.asciidoctor:asciidoctorj-diagram from 2.2.9 to 2.2.11
- Don't show popup for page breaks (#1388)
- Support the `runtime.log.destination` properties in an Antora playbook (#1385)

=== 0.38.20

- Don't spell-check on attribute declarations on the top of a file
- Restore compatibility with the latest IntelliJ 2023.2 EAP

=== 0.38.19

- Bump asciidoctorj from 2.5.8 to 2.5.9 and Asciidoctor to 2.0.20 (#1369)
- Bump asciidoctorj from 2.5.9 to 2.5.10 and JRuby to 9.4.2.0 (#1372)
- Bump asciidoctorj-diagram to 2.2.9 to support barcodes (#1327)
- Speed up autocompletion by instantiating fewer stubs
- Fix extending selection for first sentence in paragraph (#1332)
- Reworking selection of adjecent list items (#1332)

=== 0.38.18

- Fix relative paths for images in Antora (#1366)
- Adding sentences to the extending selection breaks (#1332)

=== 0.38.17

- Fixing potential deadlock cause on auto-completion during indexing (#1362)

=== 0.38.16

- Rework structure view for nested lists (#1346)
- Pasting of images doesn't trigger Pandoc, but pastes only the image (#1349)

=== 0.38.15

- Fix download of Pandoc on Mac (#1349)
- Bump org.asciidoctor:asciidoctorj-diagram from 2.2.7 to 2.2.8 (#1354)

=== 0.38.14

- Bump org.asciidoctor:asciidoctorj-pdf from 2.3.6 to 2.3.7
- Bump org.asciidoctor:asciidoctorj from 2.5.7 to 2.5.8
- Fix structure view for nested lists (#1346)
- Trying to avoid already disposed exception when accessing settings for line wrapping
- Ignore invalid directory structures when determining extensions (#1348)
- When using the custom AsciiDoc scopes, show only files from the current project

=== 0.38.13

- Upgrade to pandoc version 3.1.2
- For JCEF preview, reset the preview when clicking on a link leads to a different page (#1324)
- Bump org.asciidoctor:asciidoctorj-diagram from 2.2.4 to 2.2.7 (#1326)
- Set attribute `allow-uri-read` when Kroki is enabled for diagrams (#1323)
- Prevent an include error when using absolute paths with Antora for example via a `partialsdir` attributes (#1325)
- Update to AsciidoctorJ PDF 2.3.6

=== 0.38.12

- Support d2 and dbml diagrams for Kroki (thanks to @croemmich) (#1305)
- Updating to Kroki Asciidoctor 0.8.0
- Includes in Antora family subfolders should work without a relative path prefix (#1298)

=== 0.38.11

- Upgrade AsciidoctorJ to 2.2.4 and PlantUML to 1.2022.14
- Ignore Antora playbooks that are inside a module, as they are probably examples (#1293)
- Update the preview also when files are deleted
- Run external annotators for formatting and error highlighting also during indexing
- Wrap PlantUML/Salt blocks for syntax highlighting (#1300)

=== 0.38.10

- Adding a debug name for AsciiDoc StubFileElementTypes to avoid a warning in IntelliJ 2023.1 EAP (#1289)
- Fix extra backticks in smart single quotes (thanks to @blueglyph) (#1286)

=== 0.38.9

- Updated dialog notice for submitting errors (#1285)
- Ignore an already disposed exception (#1284)
- Ignore an already disposed exception (#1283)

=== 0.38.8

- Fix parsing of nodes enumerations inside of blocks
- No longer look outside the project folder for context information like `.asciidoctorconfig` files or Antora component descriptors (#1279)
- Support hard unset attribute for Antora component descriptors and playbooks (#1278)
- Avoid outdated path information for the preview after moving a file (#1276)
- Remove special handling for file names on Windows with blanks (#1276)

=== 0.38.7

- Reorder stylesheets to allow dark background in custom stylesheet
- Closing blocks on attribute start
- Fix handling of comments in table cells
- Prevent EDT warning when generating a preview when adding a description
- For Antora pages with page alias, resolve anchors

=== 0.38.6

- Initialize the preview earlier, as the window might not be visible, yet (#1258)
- Initial support for the Antora Collector Extension (#1177)

=== 0.38.5

- Use the linked stylesheet in the browser preview
- Support Antora component properties `prerelease` and `ext` (#1254)
- Support superscript and subscript in the editor (#1251)
- When saving other editors contents before rendering the preview, log exceptions thrown there instead of reporting them (#1257)
- Add preview for AddBlockIdToSection if it is in another file (#1248)
- Avoid re-formatting for table content with block markers starting with `!`, `;`, `,` and `:`
- When moving editor tab to a new window, initialize preview (#1258)

=== 0.38.4

- Regression: Fix 3-seconds-delay when showing the preview (#1226)

=== 0.38.3

- Handling Invalid file exception when installing the plugin and refreshing editors (#1238)
- Bump asciidoctorj-pdf from 2.3.3 to 2.3.4 (#1246)
- Support quick-fixes in IC 2022.3 when those change a different file than the current file (#1248)
- Avoid exception that warns about EDT when toggling soft wraps (#1249)

=== 0.38.2

- Adding built-in Mermaid support (#1199)

=== 0.38.1

- Avoid exception when generating a preview on adding an ID
- Require IntelliJ 2022.1.1 as minimum version
- Handle foreground priority differently to avoid logged `ProcessCanceledException` (#1236)
- Handle AWT dialogs when auto-saving content (#1237)
- Optimize spell checking tokenizer for better handling of attributes (#1228)
- Handle problems when pasting formatted content with input encoding when the operating system is not using UTF-8 as a default (#1074)

=== 0.37.57

- Fixing already disposed preview if devtools have been closed before
- Reduce interaction with JCEF scrolling in the editor (#1226)

=== 0.37.56

- Avoid "Invalid file" error when files are removed concurrently (#1220)
- Add tab/space indent configuration for AsciiDoc code style (#1218)
- Parse formatted page titles for Antora xrefs in pages and navigations (#1223)
- Rename search scope _All files without Symlinks_ to _Project files without Symlinks_ (#1216)

=== 0.37.55

- Require IntelliJ 2021.3.2 as minimum version update deprecated APIs
- Add an action to open the dev tools for the JCEF preview
- Add custom AsciiDoc search scopes (#1216)

=== 0.37.54

- Prevent NPE when analyzing natural language text (#1204)
- Prevent ClassCastException when handling an invalid antora.yml file (#1205)

=== 0.37.53

- Allow ID attribute on all macros, for example on images
- Resolve `+++file:///+++` URIs to local files when auto-completing in the editor.

=== 0.37.52

- Add an error message in preview when loading the custom stylesheet fails (#1076)
- Line comments are now followed by a single blank (thanks to @marcoebbinghaus) (#601)
- Fixing performance regression when evaluating `ifdef::[]` (#1183)

=== 0.37.51

- Convert formatted text from clipboard on paste (#75)

=== 0.37.50

- Detect incompatible plugin _IntelliJ Scripting: Ruby_ and show advice to the user (#1160)
- Add compatibility for IntelliJ 2022.3 EAP release
- Bump asciidoctorj from 2.5.5 to 2.5.6 (#1165)
- Avoid corner-cases with open blocks when incrementally parsing sections and cells (#1168)
- Support absolute path names when picking a file in the preview (thanks to @ropelli) (#1162)
- Defer handling of settings change to avoid an IllegalArgumentException (#1171)
- Prevent IllegalAccessError when testing for JavaFX problems (#1172)
- Read Antora component descriptor contents from PSI instead of the file to avoid outdated content.
- Prevent StackOverflowError when evaluating file references (#1173)
- Prevent exception when converting a Markdown listing without terminating block (#1174)
- Before creating a missing folder, check if the name contains only valid characters (#1175)

=== 0.37.49

- An external stylesheet removes all internal stylesheets on a successful load

=== 0.37.48

- Ensure that the MathJax error message is not shown when it contains no error even for user stylesheets

=== 0.37.47

- Resolve anchors with attributes in the target within Antora modules (#1159)
- Prevent built-in highlight.js from interfering with a custom stylesheet
- Pre-bundle highlight.js dark theme in the plugin

=== 0.37.46

- Improve highlighting of the pass macro
- Show fewer errors in blocks that are excluded via ifdef/ifndef (#1150)
- Fix the option to hide validation errors in source blocks in 2022.2 (#1151)
- Update Antora CSS theme and fonts to the latest from Antora UI

=== 0.37.45

- Restore support for blanks in filenames (#1147)

=== 0.37.44

- Bump asciidoctorj-pdf from 2.1.6 to 2.3.0 (#1139)
- Parse text files for include tags on refactoring only up to 200 kB (#1121)
- Add live template for php source to the standard templates (thanks to @dozer111) (#1142)
- Extend Antora's schema to support fallback versions and no version in the component descriptor (thanks to @reitzig) (#1140)
- When validating references, allow Unicode characters in file names (#1146)

=== 0.37.43

- Fix NPE when showing images in a browser preview (#1137)
- Fix NPE when changing the global scheme and no preview is showing (#1138)

=== 0.37.42

- Fix error message "Project settings exist but not loaded yet" (#1131)
- Avoid an already disposed element (#1132)
- Fix NPE when resolving partials in Antora partials (#1133)
- Avoid hard dependency on the YAML plugin, so the AsciiDoc plugin will work even when it is turned off (#1134)

=== 0.37.41

- Don't add page title when pressing smart enter for references without anchor when in the context of an Antora module
- Don't add the section name in the preview for references with an anchor in the Antora context
- Initial support for Hugo (#1128)

=== 0.37.40

- Support imagesdir to indicate image location even if image starts with an absolute path (#1128)

=== 0.37.39

- Cleanup workarounds for JCEF to stabilize rendering of the preview (#1122)

=== 0.37.38

- Improve Value scope support for _link_/_strong_/_emphasis_ (#1089)
- Rework conditions to avoid read lock problems (#1121)
- Rework handling of internal references when moving multiple files (#1117)
- Faster update of the preview on IDE restart and file opening (#1122)

=== 0.37.37

- Optimize reference contributors to speed up editing experience (#1121)

=== 0.37.36

- Fixing IndexOutOfBoundsException when converting Markdown to AsciiDoc (#1109)
- Avoid IllegalArgumentException when pasting an image as a reference (#1119)
- Avoid invalid file handles when rendering Antora references for the preview (#1120)

=== 0.37.35

- Prevent null elements when resolving file references (#1118)
- Fix changing the color of inline macros (thanks to @RayOffiah) (#1105)
- Handle internal references when moving multiple files (#1117)
- Bump asciidoctorj from 2.5.4 to 2.5.5 (#1112)

=== 0.37.34

- Prevent NPE when iterating Antora nav keys (#1115)

=== 0.37.33

- Bump asciidoctorj-pdf from 2.1.4 to 2.1.6 (#1110)
- rework the bounds checking when renaming files (#1092)

=== 0.37.32

- restore Markdown-to-AsciiDoc conversion on JDK 17 (#1101)
- avoid FileNotFoundException during autocomplete for images if they have been concurrently deleted (#1102)
- don't offer conversion or preview in browser for AsciiDoc files contained in JARs (#1103)

=== 0.37.31

- handle AlreadyDisposedException (#1100)

=== 0.37.30

- additional tests for auto-completion for antora pages (#1091)

=== 0.37.29

- don't highlight Antora module names in xref macros when they are distributed and link to multiple folders (#1091)
- xref macros will resolve relative to the Antora pages folder except when they start with a dot and are relative (#1091)
- avoid NoClassDefFoundError for YAMLScalar when activating the YAML plugin after the AsciiDoc plugin (#1097)
- when reporting errors with attachments, anonymized attchments will be checked by default

=== 0.37.28

- support Vale scopes for Grazie professional's project rules (#1089)
- improve the grouping in the settings by adding horizontal rules (#972)
- preventing a StringIndexOutOfBoundsException when moving files inside an Antora module (#1092)
- performance optimization for Antora when a lot of page aliases and attributes are used (#1091)
- xref macros even when used in the Antora partials folder will resolve relative to the pages directory
- documenting built-in attribute `++{pp}++` for `++`

=== 0.37.27

- Bump asciidoctorj-pdf from 2.1.2 to 2.1.4
- delete left-over XML when creating DOCX file (#1074)

=== 0.37.26

- conversion to DOCX now generally available for macOS (#1074)

=== 0.37.25

- adding missing changelog for 0.37.23 that got scrambled in the 0.37.24 release
- when creating DOCX files, fixing permissions on Pandoc execuable on macOS (#1074)

=== 0.37.24

- add support to convert AsciiDoc to the DOCX format (#1074)
- bump asciidoctorj-pdf from 2.0.6 to 2.1.2
- fix exception when Shell plugin in IntelliJ is installed after AsciiDoc plugin had already been installed (#1082)

=== 0.37.23

- handle language name snippets with special characters by quoting them (#1072)
- validate Antora module and component names (#1057)

=== 0.37.22

- fix wrong dependency for Asciidoctor Diagram (#1066)

=== 0.37.21

- synchronize latest Kroki Ruby changes, now including a referrer indicating the IntelliJ plugin
- bump asciidoctorj-pdf from 2.0.2 to 2.0.6 (#1064, #1068)
- bump asciidoctorj-diagram from 2.2.1 to 2.2.3 (#1066)
- bump asciidoctorj from 2.5.3 to 2.5.4 (#1069)
- for Antora, assume default family directory `pages` for all includes (#1062)

=== 0.37.20

- update to AsciidoctorJ PDF 2.0.2 (#1061)

=== 0.37.19

- handle exception when JCEF can't be initialized (#1051)
- update API usage to support JavaFX preview in InteliJ 2022.2

=== 0.37.18

- allow for attribute declarations in document ending with an `@`
- provide quick-fix to change attribute references to a passthrough
- fix navigation in preview for Antora cross-module xrefs with anchors (#1018)
- support editor formatting for passthrough with `++$$++` (#1017)
- support wrapping/unwrapping of selected text as passthrough by pressing `$` or `+` (#1017)
- new inspection for passthrough with `++$$++` and a quick-fix (#1017)
- when moving pages to another folder in an Antora module, update references also for includes (#981)

=== 0.37.17

- prevent NPE in when showing run markers (#1042)

=== 0.37.16

- prevent NPE in when showing run markers (#1042)

=== 0.37.15

- prevent error message "Directory index can only be queried after project initialization" (#1038)
- prevent already disposed message during background update (#1039)
- prevent blanks in suggested language names, adding 'shell' as an alias

=== 0.37.14

- support run command from editor for source code snippets and inline commands (#977)

=== 0.37.13

- support `max-width` attribute for the preview (#1029)
- allow manual download and picking for PlantUML and Ditaa Mini (#1026)

=== 0.37.12

- remove hard dependency on Grazie plugin that resulted in a ClassNotFoundException (#1014)

=== 0.37.11

- avoid NPE when handling an exception during AsciiDoc processing (#1012)

=== 0.37.10

- avoid NPE when showing the search progress bar when there is no progress indicator (#1006)
- avoid index-out-of-bounds situation when analyzing Asciidoctor logs and file is edited at the same time (#1010)

=== 0.37.9

- avoid NPE when showing the search progress bar when a file doesn't have a file name (#1006)
- extended error logging when static initializer in AsciiDocLanguage fails (#1007)

=== 0.37.8

- include Antora default CSS for the browser preview (#997)
- fix recursion problem with descriptions (#1003)

=== 0.37.7

- update reference searches to give the write access priority to avoid blocking the EDT
- avoid error messages for background processes when file has been concurrently deleted (#999)
- better text summaries in structure view
- improved block handling at end-of-file and for reparsing
- include Antora default CSS for the preview (#997)

=== 0.37.6

- prevent exception during startup activities on initial plugin installation (#992)
- prevent message "`Unable to find providerId`" when opening a previously opened file after installing the plugin (#993)
- updated parsing for pointy brackets in reference texts (#995)
- handle moving of folders in Antora pages directory and updating the references (#981)
- in Antora restrict the list of anchors in auto-completion and validation to the current page and its includes (#986)

=== 0.37.5

- fix range issue when preparing texts for the grammar checking plugin (#990)

=== 0.37.4

- fix table column spec support for syntax highlighting (#984)
- when invoking the quick-fix for a missing file, resolve base directory according to Antora rules (#985)
- fix exception when preview was already closed when rendering completed (#987)
- avoid NoClassDefFoundError after initialization of JCEF preview failed on Linux (#988)

=== 0.37.3

- update references when moving a page in Antora (#981)

=== 0.37.2

- prevent false positive grammar messages after unknown texts (reworked) (#980)

=== 0.37.1

- minimum version of IntelliJ is now 2021.3.1
- prevent false positive grammar messages after unknown texts (#980)

=== 0.36.18

- resolve document title from sub-includes when showing xrefs in preview (#967)
- force refresh of the preview even if preview is currently rendering (#967)
- when converting a Markdown listing to AsciiDoc, make number of dashed for delimiter (#969)

=== 0.36.17

- resolve Antora references without indexes in simple scenarios to improve user experience (#967)

=== 0.36.16

- upgrade to Asciidoctor 2.0.17 and AsciidoctorJ 2.5.3 (#966)
- fix navigation to anchors in current document's preview (#965)
- detailed errormessage in the preview if an Antora prefix can't be resolved (#967)
- refresh preview once indexing is complete (#967)

=== 0.36.15

- enforcing restart can't be triggered by the marketplace, reverting change (#962)
- update to Asciidoctor PDF 1.6.2 (#961)
- updated parsing for bold/italic/monospace handling for editor and highlighting (#963)

=== 0.36.14

- enforcing restart after plugin install for upgrades from version 0.36.11/0.36.12 when internal mode is enabled (#962)

=== 0.36.13

- disable unloading of plugin at runtime, restart will be required
- fix reformatting of preprocessor macros and block macros with text content (#955)
- strip newline from attribute continuation for grammar checks, strip duplicate characters for description lists (#956)
- don't report grammar errors for monospaced text and kbd macros (#956)
- treat inline passthrough content like quotes (#956)

=== 0.36.12

- workaround change in 2021.3.1 for preview with custom CSS (#954)

=== 0.36.11

- Support Antora 3 relative resource IDs with `./` for shorthand paths (#898)

=== 0.36.10

- API changes in IntelliJ EAP 2021.2.4 ExternalSystemUtil (#937)

=== 0.36.9

- fixing lexing issue with block macro after block attributes (#941)
- don't show notification about limited functionality in light mode
- increment index version numbers on stub version id increase to avoid invalid indexes
- API changes in IntelliJ EAP 2021.2.4 UntrustedProjectNotificationProvider (#937)

=== 0.36.8

- refactoring discovery of Antora playbooks to align with IntelliJ APIs (#919)
- API changes in IntelliJ EAP 2021.3.1 TrustChangeNotifier (#937)
- resolve NPE when initialization of Asciidoctor failed (#938)
- workaround for IndexNotReadyException when updating QuickDocInfo (#939)

=== 0.36.7

- fix preview of images in browser preview (#935)

=== 0.36.6

- prevent NPE case when showing documentation for current element (#929)
- rework iteration over index keys when retrieving list of sections (#930)
- cache evaluation of section headings
- update to latest Antora 3.x playbook schema (#907)
- updated log when language has already been registered (#928)
- support IntelliJ "`trusted projects`" concept and show an unrestricted preview only in trusted projects (#935)
- support continuation after source code block without style and delimiter

=== 0.36.5

- prevent error about unbalanced markers for inline IDs (#920)

=== 0.36.4

- avoid NoClassDefFoundError on plugin initialization (#928)
- prevent class cast exception in if referenced element is not a PsiNamedElement

=== 0.36.3

- xrefs with attributes will be resolved to determine if they link to an anchor or a file
- speed up resolving block IDs for auto-completion and validation (#925)
- continue to resolve attributes in document even if they have been defined in component descriptors or playbooks
- avoid expensive check in EDT for quickfix to create missing file

=== 0.36.2

- support folding of regular paragraphs (#426)
- allowing more contents to be quoted when creating PSI (#920)
- don't lose track when using source blocks inside table cells (#923)

=== 0.36.1

- refactor PSI structure for text with quotes for better text selection (#920)

=== 0.35.16

- exception handling when processing module roots in the background (#918)
- support relative local stylesheet and fallback to Asciidoctor styles if stylesheet is not available (#921)

=== 0.35.15

- fix resolving Antora page aliases
- improve resolving of anchors in Antora for partials and examples
- caching of Antora component descriptors and playbooks to speed up user interactions (#908)
- allow file index access when resolving references to files in the editor (#912)
- prevent AWT access when opening the browser after creating HTML for AsciiDoc on macOS (#913)

=== 0.35.14

- performance optimization JCEF preview (#908)
- support unset attributes in Antora component descriptors and playbooks (#893)
- support Antora 3 value _self_ for _link_ attribute (#897)
- performance optimization for Antora environments by caching playbook and component descriptor attributes (#897)
- validation for link attribute (#897)
- implement caching of attributes and text content to speed up interactions (#908)
- implement caching texts for grammar checking on section level (#908)
- update structure outline when editing the level of a section in the editor

=== 0.35.13

- performance optimization for grammar check (#908)

=== 0.35.12

- updating Antora playbook schema to 3.0.0-alpha.10
- advise users of 2021.2.x to use at least 2021.2.3 to due to platform bugfixes
- update grammar and spell checking for xref macros that don't contain link text (#890)

=== 0.35.11

- fix resolving attribute names (#893)

=== 0.35.10

- suggest to users to switch from JavaFX preview to JCEF preview
- update to latest Asciidoctor Kroki version with improved logging and pikchr diagram support
- adjust scope to page attribute scope when resolving Antora's reftext/navtext attributes for the preview (#889)
- preventing error when updating actions for create-pdf-from-preview (#894)
- handle markdown-style listing conversions where backticks are followed by spaces (#895)
- support soft-set attributes in Antora component descriptors and playbooks (#893)

=== 0.35.9

- resolve attributes in Antora's reftext/navtext attributes for the preview (#889)
- update grammar and spell checking for btn and other macros (#890)
- two lists can be separated by a blank line and a comment (#860)
- hide editor toolbar when in presentation mode (#824)

=== 0.35.8

- avoid slow operation warning when folding attributes (#887)
- avoid slow operation warning when fetching documentation (#815)
- fix parsing of block markers after line comments

=== 0.35.7

- resolve attributes of current file even if it is opened outside the project. Show notification with warning and link (#880)
- support adding and removing quotes from selected text via hotkey (#866)
- register structurizr as kroki diagram (#886)

=== 0.35.6

- optimized dark theme for verse blocks
- improved folded summary for lists as well as description in structure view (#860)

=== 0.35.5

- removing workaround for "`Cannot Open the Page/ERR_ABORTED`" to IntelliJ 2021.1 (#658)
- upgrading grammar and spell checking to new IntelliJ API (#873)
- improved handling of lists; list items are now wrapped in another PSI element for folding (#860)

=== 0.35.4

- starting with this release, 2021.2 is required due to API changes in IntelliJ

=== 0.35.3

- added spell-checking for characters in keyboard macros
- added spell-checking for pass-through content
- plugin will show an error in the editor if case of file name in document differs from the case of the file in file system (#863)

=== 0.35.2

- handle already disposed component in workaround for HiDPI preview (#864)
- make attributes in Antora playbook available for preview and autocomplete (#776)

=== 0.35.1

- avoid JCEF preview to overlap with other windows (#751)
- starting with this release, 2021.2.1 is required due to API changes in IntelliJ

=== 0.34.2

- upgrade to AsciidoctorJ Diagram 2.2.1 (#855)
- support videos in Antora images folder (#828)
- add inspection for attributes that haven't been defined (#858)
- infer attributes from Antora playbook for auto-complete of attributes (#776)
- lazy initialization for attributes to avoid exceptions in initializer (#861)
- avoid building/clearing errors on project startup (#862)

=== 0.34.1

- lighter color for caption titles in dark mode in the preview (#841)
- extend Antora playbook schema for 3.0.0-alpha.8 and 3.0.0-alpha.9
- prevent NPE when accessing parent folder of a file (#847)
- improve parsing of links and email addresses for grammar check (#846)
- upgrade to AsciidoctorJ Diagram 2.2.0 and PlantUML 1.2021.8 (#832)
- adding live templates for curved quotes (#837)
- avoid situation where panel is re-created and contents show "Initializing..."

=== 0.33.19

- avoid logged error when converting Markdown to AsciiDoc and target file exists (#839)
- revert changes about progress indicator on slow index operations (#815)

=== 0.33.18

- improved handling of blanks for IntelliJ 2021.1.x grammar check further (#818)

=== 0.33.17

- improved handling of blanks for IntelliJ 2021.1.x grammar check (#818)

=== 0.33.16

- prevent more unbalanced markers at beginning of a heading (#822)

=== 0.33.15

- line comment with two colons will no longer be highlighted as a definition list in the editor (#822)
- log additional information and prevent parsing from failing completely when a heading doesn't contain any text (#826)
- improved parsing for definition lists resulting in better folding and structure view when definition contains multiple words (#822)
- rework to prevent unbalanced markers at beginning of a heading (#822)
- prevent PsiInvalidElementAccessException when switching document (#827)

=== 0.33.14

- fix parser/lexer for section headings with inline references
- avoid run-off lexer for attribute references in autocomplete
- handle consecutive blanks passed down for grammar check in 2021.1 (#818)
- close open block markers before heading starts (#825)

=== 0.33.13

- upgrade to AsciidoctorJ 2.5.2 (includes Asciidoctor 2.0.16)
- handle empty string passed down for grammar check in 2021.1 (#818)

=== 0.33.12

- folding of list and callout items, plus grammar check per item instead of the whole list (#822)

=== 0.33.11

- use IntelliJ API to determine event dispatch thread instead of using internal JDK API (#823)

=== 0.33.10

- restore API compatibility with Asciidoclet plugin (#789)
- split logic to handle both 2021.1 and 2021.2 contents handed down by grammar checker (#818)

=== 0.33.9

- avoid exceptions when initializing plugin's icons (#821)
- additional logging to trace grammar checker problems, handling spaces at the beginning (#818)

=== 0.33.8

- enable rendering of diagrams in preview for modes other than UNSAFE (#789)
- rework handling of leading/trailing whitespace when preparing the input for the grammar check (#818)
- restore compatibility with 2020.3/2021.1 that broken in 0.33.7 (#815)

=== 0.33.7

- parse AsciiDoc table cells for source lines, improve navigation to source line (#810)
- when converting a Markdown file to AsciiDoc, warn if target file already exists and allow overwriting it (thanks to @santik) (#763, #808)
- reduce blocking of EDT thread when accessing file indexes (#815)

=== 0.33.6

- restore compatibility with 2020.3/2021.1 and avoid NoSuchMethodError (#806)

=== 0.33.5

- plugin shouldn't interfere with HTML preview focus handling (#802)
- when calculating the cut-off for the next token, take into account that this is called before the advance method (#803)

=== 0.33.4

- prevent NPE when Antora component descriptor is an empty file (#782)
- prevent IAE when expanding attributes
- when NPE on paste occurs, log additional information (#790)
- trying to avoid LinkageError in 2021.2 (#791)
- prevent error "Already disposed" when closing an editor (#799)

=== 0.33.3

- restore compatibility for IntelliJ 2020.3.x (#779)

=== 0.33.2

- prevent NPE in startup activity when dynamically loading AsciiDoc plugin (#779)
- revisiting parsing spaces for grammar checker (#752)
- prevent NPE for zoom settings

=== 0.33.1

- support new keys _network_ and _log_ in Antora playbooks
- drop support for 2020.2.x in 0.33.x releases

=== 0.32.55

- fix dependencies/class not found problems for IDEs like PHPStorm introduced in 0.32.54 (#769)

=== 0.32.54

- in Antora component descriptors, support auto-complete for keys _nav_ and _start_page_ (#769)

=== 0.32.53

- prevent NPE when renaming files in Antora projects (#770)
- when rendering errors in the preview, allow preview to refresh without flicker (#772)

=== 0.32.52

- fixing opening wrong editor for antora.yml files (#769)

=== 0.32.51

- fixing bug that prevented the editor to scroll to a line when clicking in preview (#768)

=== 0.32.50

- support ID references appended to blocks as used in AsciiDoc documentation like `[source#hello]`
- support style in blocks used in AsciiDoc documentation like `[#id%autowidth]`
- completed support for highlight.js in the preview (#370)
- adding notification to upgrade to 2021.1.2 when using 2021.1 or 2021.1.1 on macOS to prevent UI freeze (#765)

=== 0.32.49

- fix parsing escape character for inline IDs in section headings (#758)
- update to AsciidoctorJ PDF 1.6.0
- avoid exceptions when modules/libraries have already been removed (#760)
- escape HTML characters when rendering exception in preview (#761)
- escape ampersand in documentation of attributes, as IntelliJ would replace it
- prevent unnecessary disposals (#761)

=== 0.32.48

- update Antora playbook schema to include `edit_url` also in `source` element (#757)
- avoid NPE when creating a new file via a quick-fix (#745)

=== 0.32.47

- robust parsing spaces for grammar checker (#752)

=== 0.32.46

- source highlighting with highlight.js now documented (#370)
- when working in Antora modules, read attributes from _.asciidoctorconfig_ files (#703)
- fix problem when parsing spaces for grammar checker (#752)

=== 0.32.45

- additional logging when exceptions occur when checking grammar and spelling problems (#752)
- prevent exception for quickfix when missing file can't be created (#745)

=== 0.32.44

- adding loop detection to lexer (#742)
- avoid NPE when creating a new file via a quick-fix (#745)
- update to AsciidoctorJ 2.5.1 and Asciidoctor 2.0.15 (#738)
- use attributes defined in plugin's settings for auto-complete and validation in editor (#746)
- use build-in attributes for auto-complete when entering a reference to an attribute (#746)
- remove spaces not rendered by AsciiDoc before invoking grammar check, avoiding undesired warnings (#747)
- enable find-usages and renaming for negated include tags (#730)

=== 0.32.43

- avoid infinite loop/freezing UI when parsing comments (#742)

=== 0.32.42

- update to AsciidoctorJ 2.5.0 and Asciidoctor 2.0.14 (#738)
- optimizing lexing of line comments (#742)

=== 0.32.41

- avoid exception when applying formatting to three formatting characters, like a bold asterisk (#739)

=== 0.32.40

- resolve attributes like `docname` in nested includes to validate anchors (#737)

=== 0.32.39

- rework situation when no injection is active (#732)
- rework handling of already disposed modules (#683)
- avoid URLDecoder exception when an incompletely encoded URL is entered (#736)

=== 0.32.38

- avoid error message "`already disposed`" when handling problems with JCEF refresh/crashes (#729)
- fix renaming of xrefs in attributes for example with images (#730)
- enable find-usages and renaming for include tags (#730)
- initial support for source highlighter highlight.js in preview (#370)
- add notification for users to update to 2021.1.1 (#725)
- suppress warnings in 2021.1.1 EAP (#731)
- avoid error during project initialization (#733)
- avoid error when using fragment editor and inserting for example an include preprocessor macro (#732)
- support language injection for Markdown style listings (#732)

=== 0.32.37

- when searching for references for AsciiDoc sections and IDs, limited search scope to AsciiDoc file type (#722)
- tuning comment parsing (#696)
- creating fewer references when analyzing include tags in a file (#723)
- preventing plugin-unloading earlier in the plugin's loading cycle (#724)
- support Antora's 3.x new keyword for versionless component version (#728)

=== 0.32.36

- reworking error logging to avoid logging ProcessCanceled events (#718)
- listings in IntelliJ light theme will highlight with a light grey background (like inline monospace content)

=== 0.32.35

- rework StringIndexOutOfBoundsException in Grammar Check (#718)

=== 0.32.34

- improve error messages during PDF generation, adding option to add attribute _allow-uri-read_ (#717)
- avoid StringIndexOutOfBoundsException in Grammar Check (#718)

=== 0.32.33

- update to AsciidoctorJ Diagram 2.1.2

=== 0.32.32

- restrict preview using content security policy when user chooses SAVE mode (#707)
- update to AsciidoctorJ Diagram 2.1.1
- fix spelling/grammar check for attributes with continuations (#712)
- add new file templates for AsciiDoc (#715)

=== 0.32.31

- updated plugin's description for better search results in JetBrains Marketplace
- reduce instances where recursion can occur when resolving file references
- rework typographic quotes grammar check to avoid index out of bounds exception (#699)
- support all well-known AsciiDoc file extensions when auto-completing and validating file names (#706)

=== 0.32.30

- allow folding of typographic quotes in editor (#699)
- when interpolating IDs for section headings, respect `idprefix` and `idseparator` in Antora component descriptor (#703)
- adding monospace and italic syntax highlighting for nested elements (#699)
- passing on typographic single quotes to grammar checker (#699)

=== 0.32.29

- handling typographic quotes near monospaced inline content (#699)

=== 0.32.28

- adding spell checking for footnotes (#692)
- preventing exception when project view is not available (#695)
- preventing exception when search for references for Java classes without a name (#698)

=== 0.32.27

- avoid exception that editor has already been disposed (#693)
- improved handling for parsing footnotes (#692)
- avoid exception when processing events for already disposed projects (#683)

=== 0.32.26

- minimize logic of focus handling after testing on Linux (#691)

=== 0.32.25

- focus on preview when no editor is available, therefore allowing keyboard navigation in preview (#691)
- backporting support for different zoom levels on different screens to 2020.3.2 (#690)

=== 0.32.24

- render preview in designated area in cases where primary and secondary screen have different zoom levels (#690)

=== 0.32.23

- handle escaped attribute references in headlines (#689)
- reworked support for Antora JSON Schemas to avoid exception in log (#687)

=== 0.32.22

- simplified code to handle Antora JSON Schemas to avoid exception in log (#687)
- zoom level in plugin's setting now entered without the percent sign in input fiel to avoid parsing problems when percent sign is missing (#674)

=== 0.32.21

- avoid exception when processing file events for already disposed module (#683)
- fixing exception "`spaces element contains non-spaces-characters`" in lexer (#685)

=== 0.32.20

- avoid exception when looking up items by name and item is in a library (#677)
- regression: don't show AsciiDoc content in libraries on auto-completion (#677)

=== 0.32.19

- auto-complete for images will no longer auto-suggest anchor names (#672)
- transfer long exception messages to Sentry to avoid cut-offs (#672)
- speed up lookup of references by declaring a specific search scope that excludes libraries (#672)
- adopt workaround to prevent JCEF preview error "`Cannot Open the Page/ERR_ABORTED`" to IntelliJ 2021.x. (#658)
- avoid "`Invalid root file`" error when deleting files or folders (#676)

=== 0.32.18

- avoid exception in log when opening AsciiDoc file (#667)
- report build number for IntelliJ EAP releases when submitting information to Sentry (#670)
- update to AsciidoctorJ 2.4.3
- handle auto-completion for MacOS X volume icons (#671)
- use new NIO file API when converting to HTML or PDF file to avoid file name manipulation issues (#666)

=== 0.32.17

- fix classloader problem for JRuby on IntelliJ 2021.x EAP (#664)
- rework issue #658 to restore functionality for zoom and open-links-in-external-browser (#665)

=== 0.32.16

- when un-quoting a selected text to be no longer bold italic or monospaced, the inner text must be at least one char long (#656)
- prevent JCEF preview error "`Cannot Open the Page/ERR_ABORTED`" error in IntelliJ 2020.3.x versions (#658)
- prevent exception when extending word selection for example near a double quote (#661)

=== 0.32.15

- prevent looping/blocking external annotator when post-processing of include error messages (#649)
- prevent unloading of plugin even when no project has been opened yet to avoid loading errors afterwards for icons, resources and schemas (#652)
- forcing re-indexing of AsciiDoc content as previous updates changed parsing/lexing, and the resulting IntelliJ indexes are out of date (#653)
- avoid exception when search for references in Java's root package name (#654)

=== 0.32.14

- prevent issuing a repaint on EDT thread, preventing refresh requests to queue up (#641)
- when embedding iframes in the preview, don't try an in-place update of the contents as this could break the JavaScript for example of YouTube videos (#640)
- prevent lagging UI when refreshing the preview with JCEF and not using in-place refresh (#640)
- JCEF preview is the default for new installations

=== 0.32.13 (preview, available from GitHub releases)

- fixed support for 'tags' key for sources in Antora playbook (#646)

=== 0.32.12

- performance improvement when parsing long lines and words by limiting the length of inline macro names and email addresses (#641)
- improvement data structure for handling a large number of modules (#641)

=== 0.32.11 (preview, available from GitHub releases)

- validate that language for source block is marked injectable by JetBrains (#642)
- performance optimizations on background tasks
- only changes to file in current project's modules will refresh the preview (#641)
- update cached project roots from changed files (#641)

=== 0.32.10 (preview, available from GitHub releases)

- cache project roots to speed up preview and read actions, and to prevent blocking the write thread (#641)
- use read actions with write action priority on all background tasks (#641)

=== 0.32.9 (preview, available from GitHub releases)

- update Kroki support with latest diagrams and attributes, fixing `kroki-plantuml-include` support (#639)
- prevent error messages in log when projects have already been disposed

=== 0.32.8 (preview, available from GitHub releases)

- update preview when project leaves or enters dumb mode so that pending references can be resolved
- prevent NPE when block attributes are not provided
- users can submit error reports anonymously to the plugin's project at Sentry when exceptions occur (#628)
- upgrade to AsciidoctorJ PDF 1.5.4
- Additional reformat option for blank lines after headings (thanks to @c7haki) (#633)
- upgrade to AsciidoctorJ Diagram 2.1.0 and PlantUML v1.2021.0

=== 0.32.7

- show action tool bar in light edit mode (#630)
- fix timestamp when pasting a screenshot from the clipboard (#631)

=== 0.32.6

- don't treat menu items as links
- show soft-wrap notification to all users that don't use it yet

=== 0.32.5 (preview, available from GitHub releases)

- if content in the preview is from an included file, click on the content in the preview opens included file (#557)
- stop implementing an EditorActionHandler as pasting of images seems to work without it to avoid the plugin to appear in EDT freezes when delegating calls (#605, #584)

=== 0.32.4 (preview, available from GitHub releases)

- recognize front matter when parsing page attributes
- add block and paragraph admonition live template (thanks to @rdmueller) (#609,  #611)
- support bibliography anchors alone on a line (#614)
- handling attribute references in block attributes

=== 0.32.3 (preview, available from GitHub releases)

- initial support for light edit mode (#606)

=== 0.32.2

- rework JavaFX handling with JDK 11 to avoid inaccessible exception
- rework parsing of `kbd` macro to prevent runaway escapes
- fixing wrong indexing of section titles with attributes causing "`PSI and index do not match`"
- choose-by-name will find sections with replaced attributes

=== 0.32.1 (preview, available from GitHub releases)

- fix right-click-saves-image in JavaFX preview
- changing development to JDK 11 in line with IntelliJ 2020.3 platform
- don't break section titles with custom IDs or attributes on automatic reformat (#604)
- don't use title with replaced attribute as PsiElement's name as IntelliJ might throw an "`PSI and index do not match`" exception
- formatting of words via actions in the toolbar now works with the cursor placed at the end of the word (#602)
