= How to Build and Contribute

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toc-placement!:

== About

This document enables you to enhance the plugin when you are new to either the project, or developing in an area you haven't previously worked in before.

== Status

This document is work in progress. Please ask questions to the maintainers for anything that is missing (either via email or via a GitHub ticket), and we'll update it.

== Getting started

=== Choosing a Java Version and Distribution

Currently JDK 8 and JavaFX is required to build and run the plugin.

The JetBrains JDK 8 distribution is recommended for development.

JetBrains JDK 8::
Comes with a bundled JavaFX, download here: https://bintray.com/jetbrains/intellij-jdk[JetBrains OpenJDK 8]
This way you can develop with the JDK that is also running the JetBrains IDE.

Oracle JDK 8::
Meets both dependencies, JavaFX is bundled with it out-of-the box.
This is easy to give development a start if it is already installed on your machine, but will be different from most user's installations.

OpenJDK::
Is usually distributed without JavaFX; you probably need to install JavaFX manually.
This is usually the least preferred approach, although in practice Linux users often run JetBrains IDEA with the JDK provided by their local Linux distribution (that now and then leads to difficulties).

=== Local Build

This plugin is built using Gradle.
If you build or run it the first time it will download the community edition of IntelliJ automatically.
You don't need to install Gradle, you just need to install Java and make it available in the path.

If you have developed the plugin before it changed to Gradle you might want to remove the contents of your `.idea` folder to trigger a re-import of the Gradle project.

To build this plugin, you need to run:

----
./gradlew -Dfile.encoding=UTF-8 buildPlugin
----

The ZIP file with plugin to distribute will be located in `build/distributions`.

=== Running the development version locally

To run the plugin for development you'll need to start

----
./gradlew -Dfile.encoding=UTF-8 runIdea
----

=== Running the plugin from with the IDE

You most likely want to do this for fast turnaround times when running single tests, and debugging both tests and the plugin itself.
Please use IntelliJ IDEA as an IDE for developing on this plugin:

. Ensure to install the following two plugin in your IDE (your IDE should recommend to install them once you open the project):
+
--
GrammarKit:: Helps with highlighting and code completion in Grammar files (*.flex).

PsiViewer:: Helps analyzing the PSI (abstract syntax tree) created from the plugin in the IDE.
--

. Checkout the GitHub project and import it as a gradle project.

. Run for example the test cases from `AsciiDocLexerTest.java` to see that running tests works in your setup

. There are two ready-to-go run configurations checked in to git that that you can run:
+
--
buildPlugin:: building the plugin as a ZIP-file that you can then install locally into your IDE

runIdea:: runs an IntelliJ community edition with the AsciiDoc plugin enabled.
You can choose to run it in debug mode.
--

== Parsing AsciiDoc files

TODO: lexing, parsing, syntax highlighting, refactorings
