= How to Build and Contribute

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toc-placement!:

== About

This document enables you to enhance the plugin when you are new to either the project, or developing in an area you haven't previously worked in before.

== Status

This document is work in progress. Please ask questions to the maintainers for anything that is missing (either via email or via a GitHub ticket), and we'll update it.

== Getting started

[[JDK]]
=== Choosing a Java Version and Distribution

Currently JDK 8 and JavaFX is required to build and run the plugin.

The JetBrains JDK 8 distribution is recommended for development.

JetBrains JDK 8::
Comes with a bundled JavaFX, download here: https://bintray.com/jetbrains/intellij-jdk[JetBrains OpenJDK 8]
This way you can develop with the JDK that is also running the JetBrains IDE.

Oracle JDK 8::
Meets both dependencies, JavaFX is bundled with it out-of-the box.
This is easy to give development a start if it is already installed on your machine, but will be different from most user's installations.

OpenJDK::
Is usually distributed without JavaFX; you probably need to install JavaFX manually.
This is usually the least preferred approach, although in practice Linux users often run JetBrains IDEA with the JDK provided by their local Linux distribution (that now and then leads to difficulties).

=== Local Build

This plugin is built using Gradle.
If you build or run it the first time it will download the community edition of IntelliJ automatically.
You don't need to install Gradle, you just need to install Java and make it available in the path.

If you have developed the plugin before it changed to Gradle you might want to remove the contents of your `.idea` folder to trigger a re-import of the Gradle project.

To build this plugin, you need to run:

----
./gradlew -Dfile.encoding=UTF-8 buildPlugin
----

The ZIP file with plugin to distribute will be located in `build/distributions`.

=== Running the development version locally

To run the plugin for development you'll need to start

----
./gradlew -Dfile.encoding=UTF-8 runIdea
----

=== Running the plugin from with the IDE

==== About

You most likely want to do this for fast turnaround times when running single tests, and debugging both tests and the plugin itself.
Please use IntelliJ IDEA as an IDE for developing on this plugin.

You can use the most recent version of the IDE.
The `build.gradle` file specifies the minimum version for all users of the plugin, but when developing you are free to use a more recent version.

==== Setup Tasks

. Checkout the GitHub project and import it as a gradle project.

. Ensure to install the following two plugin in your IDE (your IDE should recommend to install them once you open the project):
+
--
GrammarKit:: Helps with highlighting and code completion in Grammar files (*.flex).

PsiViewer:: Helps analyzing the PSI (abstract syntax tree) created from the plugin in the IDE.
--

. Go to "Project Structure... | Platform Settings | SDK":

.. add "JetBrains JDK 8" (see <<JDK>> above where to download)

.. add "IntelliJ IDEA SDK" and set "JetBrains JDK 8" as the internal Java Platform

.. choose "IntelliJ IDEA SDK" as the JDK for this project

==== Validation Tasks

Perform these tasks to ensure that your setup is ready for development.

. Run the test cases from `AsciiDocLexerTest.java` to see that running tests works in your setup

. There are two ready-to-go run configurations checked in to git that that you can run:
+
--
buildPlugin:: building the plugin as a ZIP-file that you can then install locally into your IDE

runIdea:: runs an IntelliJ community edition with the AsciiDoc plugin enabled.
You can choose to run it in debug mode.
--

== Parsing AsciiDoc files

TODO: lexing, parsing, syntax highlighting, refactorings

== Preview rendering

=== Rendering AsciiDoc to HTML

The central class and method to create AsciiDoc from HTML is `AsciiDoc.render()`.
It is implemented as a singleton.

It registers custom Asciidoctor extensions that are needed for improve the preview.
It also enables custom extensions in the `.asciidoctorconfig` folder.

=== Displaying the HTML as a preview

There is a `JeditorHtmlPanel` (for Swing) and a `JavaFxHtmlPanel` (for JavaFX) preview.

The JavaFX preview is the current default preview.
It is available when the user is running 64bit JDK with JavaFX (the default JDK for JetBrains IDE).

For the JavaFX preview the HTML is enriched with CSS and JavaScript.

The JavaFX preview uses JavaScript to scroll the preview to the current position: once the user moves the cursor, the cursor line is transmitted to the preview using `scrollToLine()` and repositions the preview using JavaScript.

When the user interacts with the JavaFX preview (for example clicks on a text or a link), there is a bridge `JavaPanelBridge` back from JavaScript to Java to trigger actions like scrolling the editor or opening a link in the browser.
