= How to Build and Contribute

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:toc:
:toc-placement!:

== About

This document enables you to enhance the plugin when you are new to either the project, or developing in an area you haven't previously worked in before.

== Status

This document is work in progress. Please ask questions to the maintainers for anything that is missing (either via email or via a GitHub ticket), and we'll update it.

== Getting started

[[JDK]]
=== Choosing a Java Version and Distribution

Currently JDK 8 and JavaFX is required to build and run the plugin.

The JetBrains JDK 8 distribution is recommended for development.

JetBrains JDK 8::
Comes with a bundled JavaFX, download here: https://bintray.com/jetbrains/intellij-jdk[JetBrains OpenJDK 8]
This way you can develop with the JDK that is also running the JetBrains IDE.

Oracle JDK 8::
Meets both dependencies, JavaFX is bundled with it out-of-the box.
This is easy to give development a start if it is already installed on your machine, but will be different from most user's installations.

OpenJDK::
Is usually distributed without JavaFX; you probably need to install JavaFX manually.
This is usually the least preferred approach, although in practice Linux users often run JetBrains IDEA with the JDK provided by their local Linux distribution (that now and then leads to difficulties).

=== Local Build

This plugin is built using Gradle.
If you build or run it the first time it will download the community edition of IntelliJ automatically.
You don't need to install Gradle, you just need to install Java and make it available in the path.

If you have developed the plugin before it changed to Gradle you might want to remove the contents of your `.idea` folder to trigger a re-import of the Gradle project.

To build this plugin, you need to run:

----
./gradlew -Dfile.encoding=UTF-8 buildPlugin
----

The ZIP file with plugin to distribute will be located in `build/distributions`.

=== Running the development version locally

To run the plugin for development you'll need to start

----
./gradlew -Dfile.encoding=UTF-8 runIdea
----

=== Running the plugin from with the IDE

==== About

You most likely want to do this for fast turnaround times when running single tests, and debugging both tests and the plugin itself.
Please use IntelliJ IDEA as an IDE for developing on this plugin.

You can use the most recent version of the IDE.
The `build.gradle` file specifies the minimum version for all users of the plugin, but when developing you are free to use a more recent version.

==== Setup Tasks

. Checkout the GitHub project and import it as a gradle project.

. Ensure to install the following two plugin in your IDE (your IDE should recommend to install them once you open the project):
+
--
GrammarKit:: Helps with highlighting and code completion in Grammar files (*.flex).

PsiViewer:: Helps analyzing the PSI (abstract syntax tree) created from the plugin in the IDE.
--

. Go to "Project Structure... | Platform Settings | SDK":

.. add "JetBrains JDK 8" (see <<JDK>> above where to download)

.. add "IntelliJ IDEA SDK" and set "JetBrains JDK 8" as the internal Java Platform

.. choose "IntelliJ IDEA SDK" as the JDK for this project

==== Validation Tasks

Perform these tasks to ensure that your setup is ready for development.

. Run the test cases from `AsciiDocLexerTest.java` to see that running tests works in your setup

. There are two ready-to-go run configurations checked in to git that that you can run:
+
--
buildPlugin:: building the plugin as a ZIP-file that you can then install locally into your IDE

runIdea:: runs an IntelliJ community edition with the AsciiDoc plugin enabled.
You can choose to run it in debug mode.
--

== Lexing and Parsing AsciiDoc files

Lexing and parsing input files is the beginning of both highlighting the code in the editor and building auto-completion and refactoring functionality.

[[lexing]]
=== Lexing of input files

Lexing chops the input file into a stream of tokens.
Each token has a type and a snippet of characters.

The standard to do this in IntelliJ is https://jflex.de[JFlex].

The heart of lexing is `asciidoc.flex`.
It defines multiple states, and uses a lot of functionality and tweaking to parse AsciiDoc.
You can add new token types as you go in `AsciiDocTokenTypes`. Ensure to update the list `TOKENS_TO_MERGE` if consecutive identical types of the tokens should be merged.

Once you change `asciidoc.flex`, you should run `gradlew compileJava` to generate the parser code.

A test suite for the lexer in `AsciiDocLexerTest`.
I recommend running it from the IDE.
Each test case contains a `doTest()` method that parses one snippet of AsciiDoc and compares it to an expected "`golden master`" result.

A typical developer workflow for enhancing the lexer looks like this:

. change `asciidoc.flex` in the IDE, adding new entries to `AsciiDocTokenTypes` as needed
. run `gradlew compileJava` on the command line
. add a test case to `AsciiDocLexerTest` and run it from the IDE
. if lexing doesn't work yet as expected repeat from step 1 when
. if lexing returns the expected result, update the `expected` parameter in the test

[WARNING]
--
Things to consider when parsing AsciiDoc with JFlex:

* JFlex has originally been designed to parse Java code. AsciiDoc is different
* There are no wrong characters in AsciiDoc. If you get the syntax wrong, the characters are printed normally "as is", while only a matching set of for example asterisks (`*`) produces bold text.
--

Here some JFlex rules for AsciiDoc together with an explanation of the why:

Look ahead rules::
+
--
Look ahead rules are considered slow in JFlex, but they give the power to recognize tokens only when there is a matching closing token.

A slash (`/`) separates the matching pattern from the look ahead.

.Example from parsing typographic quotes
----
{TYPOGRAPHIC_QUOTE_START} / [^\*\n \t] {WORD}* {TYPOGRAPHIC_QUOTE_END}
----
--

Stateful parser::
+
--
To parse bold, italic and monospace text (that can be nested) there is a set of boolean variables to memorize the current text style.
They are reset at the end of a block (like in regular Asciidoctor).
The function `textFormat()` uses them to determine the current token type from a combination of these flags.

Other states memorize the length of block separator line to find the matching closing separator.
--

qualifying matches, push back and state change::
+
--
After a match the Java code checks additional conditions like if this is an unconstrained position in the stream.
If the code decides to discard the match, two possible strategies out of several are:

. push back all but the first character, and return the token type for the single character (for example when an double-asterisk occurs, but no bold text is to end here, see `{DOUBLEMONO}` in the lexer).

. push back the complete text and continue with a different state using `yybegin()` (for example when matching a `{HEADING_OLDSTYLE}` in the `MULTILINE` state).

Unfortunately, the parser can't continue with other matches in the same state.
To work around this issue blocks are parsed first in state `MULTILINE`, then in state `SINGLELINE`, and finally `INSIDE_LINE` to implement a hierarchy and some ordering of matches.
--

autocompletion::
+
--
Expressions described above match expressions once they have their closing syntax completed and it is essential for the correct highlighting.
To support autocomplete the matching must handle an expression where only the left part of the expression exists.

A special case is in the parser to support autocompletion, as IntelliJ inserts a special string when parsing the content for autocompletion (named `AUTOCOMPLETE` in our parser).

In the case for references (`\<<ref>>`) there are two rules, one for regular parsing and highlighting, one without:

[source,indent=0]
----
  // regular
  {REFSTART} / [^>\n]+ {REFEND} { yybegin(REF); return AsciiDocTokenTypes.REFSTART; }
  // autocomplete
  {REFSTART} / [^>\n ]* {AUTOCOMPLETE} { yybegin(REFAUTO); return AsciiDocTokenTypes.REFSTART; }
----
--

[[highlighting]]
=== Highlighting

Highlighting is coloring the text in the editor.

The file `AsciiDocSyntaxHighlighter` defines one `TextAttributesKey` to each entry in `AsciiDocTokenTypes` parsed during lexing.
Currently several tokens have the same highlighting `ASCIIDOC_MARKER`, so users have the same color for the pointy brackets around references references (`\<<ref>>`)and markers for bold (`\*bold*`).

Once you add a new `TextAttributesKey`, you should either

. reference an existing color (like `ASCIIDOC_COMMENT` references `DefaultLanguageHighlighterColors.LINE_COMMENT`) OR
. add a color the AsciiDoc themes `AsciidocDefault.xml` and `AsciidocDarcula.xml`

Once you add a new token you will need to add it to `AsciiDocColorSettingsPage` so users can customize the colors of their theme.
This class references also `SampleDocument.adoc` and `AsciiDocBundle.properties`, therefore you'll probably need to change these two files as well.

=== Parsing

TODO: parsing, refactoring, folding, linking, autocompletion, finding references

== Preview rendering

=== Rendering AsciiDoc to HTML

The central class and method to create AsciiDoc from HTML is `AsciiDoc.render()`.
It is implemented as a singleton.

It registers custom Asciidoctor extensions that are needed for improve the preview.
It also enables custom extensions in the `.asciidoctorconfig` folder.

=== Displaying the HTML as a preview

There is a `JeditorHtmlPanel` (for Swing) and a `JavaFxHtmlPanel` (for JavaFX) preview.

The JavaFX preview is the current default preview.
It is available when the user is running 64bit JDK with JavaFX (the default JDK for JetBrains IDE).

For the JavaFX preview the HTML is enriched with CSS and JavaScript.

The JavaFX preview uses JavaScript to scroll the preview to the current position: once the user moves the cursor, the cursor line is transmitted to the preview using `scrollToLine()` and repositions the preview using JavaScript.

When the user interacts with the JavaFX preview (for example clicks on a text or a link), there is a bridge `JavaPanelBridge` back from JavaScript to Java to trigger actions like scrolling the editor or opening a link in the browser.
