= Features of the AsciiDoc IntelliJ plugin
:experimental:
:icons: font

////
= Contribution Guideline for this document:

This guideline should lead to a style that is comprehensible to the user.

Don't assume people are developers and have worked with IntelliJ before -- this should be for writers or business analysts as well, and also for first-time IntelliJ users.

Naming the actor, the active voice and the present tense makes it easier for non-native speakers to understand this document.
Adding the shortcuts should help users new to IntelliJ.

Each sentence should on its own line.

== Check lists for writing content

Name the actor::
Examples: user, preview, editor, plugin

Provide Keyboard shortcuts::
Example: kbd:[Alt+7]

Use active voice::
Good: "The preview displays the result" +
Bad: "The result is displayed"

Use present tense::
Good: "The preview displays the result" +
Bad: "The preview will display the result"

Use only on capital letter for Keyboard shortcuts::
Good: kbd:[Alt+7] +
Bad: kbd:[ALT+7]
////

== About

This document details the features available in the plugin to users of the plugin.
Use it as a reference guide to find out what the plugin can do today.
The plugin should work "`like any other IntelliJ plugin`" when it comes to shortcuts and configurations.
If not, please describe the expected behaviour in a https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[GitHub issue].

Please consider to contribute to this document: open a bug when something is unclear, missing or wrong.
You can even create a pull request for this document!

NOTE: Parts that are marked to be experimental are likely to have corner cases that are not yet implemented, may have bugs. They can change their behaviour between releases at any time.

== Features

=== Basic

* Recognizes the AsciiDoc file extension (.adoc, .asciidoc, .ad)
* Provides a split view with
** editor with syntax highlighting (per default on the left) and
** live preview (per default on the right)
* Toolbar and context menu for basic formatting and to create tables
* Refactor Markdown to AsciiDoc: Right click on a file, or use the Refactor menu, and plugin replaces the Markdown document by the AsciiDoc equivalent. Also supports undo, in case the user is not happy with the result!

=== Editor

==== Navigation

// see: AsciiDocFoldingBuilder
The user can fold sections and blocks using the small +/- symbols on the left of the editor.
Folded sections and blocks show their first line except when this is block id (like `\[[id]]`).

// see: AsciiDocStructureViewElement
The structure of the file kbd:[Alt+7] shows the hierarchy of sections and blocks with titles.
This contains (if available) the first block attribute element (like \[source], \[quote] or \[verse]) and the title of the block or section.
If an element like an `image::[]` references another file, it shows the icon of the file and the file's name.
If an `include::[]` references an AsciiDoc file, it includes the file as a sub-tree in the structure view.
Clicking on either a referenced file or an element of a sub-tree opens the referenced file.

// see: AsciiDocChooseByNameContributor and AsciiDocSearchEverywhereClassifier
The search all view kbd:[Shift]kbd:[Shift] shows section titles and IDs of blocks.

The breadcrumbs view (bottom of the editor) shows the hierarchy leading to the current sections and blocks.
It contains the same elements like in the structure view for the cursor position.

For `include::[]` and `image::[]` block macros the keys kbd:[Ctrl+Click] and kbd:[Ctrl+B] navigate to the referenced file.

For references (like `\<<id>>`) the keys kbd:[Ctrl+Click] and kbd:[Ctrl+B] navigate to the reference (like `\[[id]]`). This works similarly for attributes (`\{attrib}` and `:attrib:`).
"`Find Usages`" (kbd:[Alt+F7]) finds usages of references and attributes and allows navigation.

// see: AsciiDocDocumentationProvider
The user can show quick documentation for the element at the cursor's position using kbd:[Ctrl+Q].
At the moments this works for attributes (`\{attrib}` and `:attrib:`) both in the editor and when using autocomplete.

The plugin highlights matching braces including symmetric formatting for bold, italic and monospace.

IntelliJ's built-in spell checker verifies all text areas of the document.
It underlines unknown words with a green wavy line.
With the context menu the user can change the spelling or to add the word to the project's dictionary.
To enable spell-checking support for other languages, the user can add a dictionary file via "`Editor | Spelling`".
Dictionaries are available online for example at http://www.winedt.org/dict.html. Word lists need to be in the UTF-8 format to work.

// see: ExternalAnnotator
During rendering Asciidoctor might indicate problems in the file including a line number.
The editor shows them as red and yellow annotations.
Hover over the annotations to see the full warning or error message.
The user can disable this feature in the settings.
If it is disabled in the settings, errors show up in the event log.

When the text contains Markdown style headings (starting with `#`) or old style Asciidoc headings (titles underlined with string or characters matching the length or the heading), the editor highlights this in yellow and offers a quick fix to convert these to a new style Asciidoc heading.

The editor supports a default and dark theme.
The user can change the colors of the theme in the IDE settings.

When using listings with `[source,lang]`, the plugin triggers language injection to the following code block when the language is supported by the IDE (either by default, or by a language plugin).
This allows syntax highlighting and code completion specific to the language of the code block.
The user can disable this feature in the settings completely or for selected languages.
For the user to re-format the code block, use "`Edit Fragment`" (kbd:[Alt+Enter]) and "`Reformat Code`" ( kbd:[Ctrl+Shift+L]).

All comments containing a `TODO` and `FIXME` and are indexed in the Todo-View (kbd:[Alt+6]).
The user can configure the keywords in the IDE settings.

// see: BrowserPanel for creating the HTML
// see: PreviewStaticServer for delivering the contents to the Browser
In the editor the user can select from a list of browsers that are showing in the upper right corner of the editor to preview the document.
The user can also trigger this action from the context menu.
To update the preview in the browser the user needs to refresh the contents by pressing kbd:[F5] in the browser.

The user can open an AsciiDoc file in an external tool (like for example Google Chrome with the https://github.com/asciidoctor/asciidoctor-browser-extension[Asciidoctor Extension] installed). To do this, add Chrome as an https://www.jetbrains.com/help/idea/settings-tools-external-tools.html[external Tool in the settings].
Provide `$FilePath$` as the argument so that Chrome knows where to find the file.
The user can assign a shortcut to the external tool using "`Help | Find action... | (type the name of external tool) | kbd:[Alt+Enter] | (type the shortcut of choice) | OK`".

==== Writing

// see: AsciiDocSmartEnterProcessor
When adding block attributes, the plugin supports statement completion (also known as "`Smart Enter`") using the shortcut kbd:[Shift+Ctrl+Enter].
For example: a `[source,java` receives a closing bracket and two listing separator lines.

// see: AsciiDocBraceMatcher
When the user opens a quote or a bracket, the plugin automatically adds a closing quote if it followed by whitespace or a closing bracket.

For references, attributes and images, and several block macros like include, image and diagrams it provides auto-completion using kbd:[Ctrl+Space].
References and attributes support renaming within a project.

There are several live templates included.
Once the user starts typing kbd:[a]kbd:[d], a list of templates appears.
Continued typing any character of the template name restricts the list. A kbd:[Tab] selects and entry.

The user can extract and inline includes.
This is available from the "`Refactor`" context menu and via context-sensitive intentions via kbd:[Alt+Enter] ("`Inline Include Directive`" and "`Extract Include Directive`").
// see: ExtractIncludeDialog.java
Extract will extract either the currently selected text, the current block or the current section including subsections.
// see: InlineIncludeDialog.java
Inline will inline the complete referenced file at the current include; optionally it can provide a preview, inline all occurrences of the file and delete the included file afterwards.
All of these changes can be undone (kbd:[Ctrl+Z]).

The user can disable and enable intentions in "`Settings... | Editor | Intentions | AsciiDoc`".

*Experimental:* The user can reformat the source in the editor using "`Reformat Code`" (kbd:[Ctrl+Alt+L]).
In order to use this feature, the user has to enable it in the settings of the plugin.
Currently it adjusts empty lines around headings, lists and blocks.
It also adjusts spaces around list items. +
In the project view the user can reformat a single file or all files in a folder and its sub folders using the same shortcut or the entry from the context menu.

=== Preview

Per default the preview is on the right side of a vertical split screen.
Using the configuration, the user can change the split to horizontal, and change the position of the preview.

The plugin uses https://github.com/asciidoctor/asciidoctorj[AsciidoctorJ] 2.x to render the preview.

It renders the content of the editor including all referenced includes, images and diagrams like PlantUML on the fly.
// see: plantuml-png-patch.rb
As JavaFX has a problem displaying SVG files correctly, the plugin displays all PlantUML diagrams as PNG on the fly.

When the user moves the cursor in the editor, the preview scrolls the text into the preview.

When the user clicks on text in the preview, the editor moves the cursor to the clicked text.
This is accurate at block level, unfortunately not yet on line or character level.

When the user clicks on an external URL, the preview opens it in an external browser.

When the user clicks on a relative link within the project (usually a `\link:[]` reference), the preview opens the referenced file in a new editor.

When the user right-clicks on an image, the editor shows a dialog to save the file to the local file system.
For diagrams like PlantUML it offers to save the files as PNG or SVG.
Windows and Linux users have a drop down menu for this.
MacOS users need to type the extension for the target file name (`.svg` or `.png`)

The user can zoom in and out of the preview by holding kbd:[Ctrl] and scrolling the mouse wheel up or down.
Clicking the middle mouse button whilst holding kbd:[Ctrl] will reset the zoom to 100%.

=== Advanced

==== Configuration File

To provide a common set of variables when rendering the preview, the plugin reads an _.asciidoctorconfig_ configuration file.
Use this to optimize the preview the project contains a document that is split out to multiple include files.
See https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations[Wiki page] for details

==== Extensions

Asciidoctor Extensions can provide additional macros.
To see the rendered result in the preview, the plugin can use extensions during rendering.
See https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-for-Asciidoctor-Extensions[Wiki page] for details

