= IntelliJ AsciiDoc Plugin
Alexander Schwartz
:experimental:
:url-ci-travis: https://travis-ci.org/asciidoctor/asciidoctor-intellij-plugin

image:https://api.travis-ci.org/asciidoctor/asciidoctor-intellij-plugin.svg?branch=master[link={url-ci-travis}]
image:https://img.shields.io/jetbrains/plugin/v/7391-asciidoc.svg[JetBrains Plugins,link=https://plugins.jetbrains.com/plugin/7391-asciidoc]
image:https://img.shields.io/jetbrains/plugin/d/7391-asciidoc.svg[Downloads,link=https://plugins.jetbrains.com/plugin/7391-asciidoc]

A plugin for the IntelliJ platform (IntelliJ IDEA, RubyMine, etc.) that provides support for the http://www.asciidoc.org[AsciiDoc] markup language.
It also supports https://antora.org/[Antora], the documentation CMS build with AsciiDoc.

*To contribute as a developer, some issues are labeled with link:https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22["good first issue"].* Maintainers are willing to help.
Feel free to choose these or any other ticket to participate, or create pull requests without a prior ticket.

*You can meet the maintainers in person:* Please ping them via eMail or chat before or during the event!

* https://www.ahus1.de/[Alex] at https://www.devoxx.co.uk/[Deovxx UK], 2020-08-24..26

== Installation

You can install the plugin (named "`AsciiDoc`") from the plugins section inside your JetBrains IDE or download it from the https://plugins.jetbrains.com/plugin/7391[JetBrains Plugin Repository].

The most advanced and recommended preview mode (and default for new installations) is JavaFX.

To use the JavaFX preview instead of the Swing preview, you'll need to run IntelliJ with 64bit Java and JavaFX installed.
Oracle JDK installations include JavaFX, but can make the IDE unstable and crash.
Pre-bundled OpenJDK installations usually don't include JavaFX.
Therefore, JetBrains OpenJDK pre-bundled with your IDE is recommended.

From 2017.1 onwards a JetBrains OpenJDK 64bit is included even in the Windows versions.
Please only use the JDK provided by JetBrains, as the JavaFX rendering seems to be most stable in the JetBrains JDK. See https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under[Selecting the JDK version the IDE will run under] for more details.

== Features

* Recognizes the AsciiDoc file extension (.adoc, .asciidoc, .ad)
* Provides a two-pane AsciiDoc preview editor based on https://github.com/asciidoctor/asciidoctorj[AsciidoctorJ] with live preview.
* Toolbar and context menu for basic formatting and to create tables.
* Refactor Markdown to AsciiDoc: Right click on a file, or use the Refactor menu, and the Markdown document will be replaced by the AsciiDoc equivalent.
Also, supports undo if the user is not happy with the result!

Refer to the link:FEATURES.adoc[Features list] for a detailed overview of the features.

If you are missing features, please don't hesitate to let me know on Twitter: http://www.twitter.com/ahus1de[@ahus1de] or create an issue in the GitHub issue tracker!

Refer to the link:CHANGELOG.adoc[CHANGELOG] for a complete list of changes in older releases.

== Dependencies

This project uses AsciiDoctorJ and JRuby for the rendering of the AsciiDoc content.

For the conversion of Markdown to AsciiDoc, we use Pegdown and the https://github.com/bodiam/markdown-to-asciidoc[Markdown to AsciiDoc] converter.

== Building, Contributing, Code of Conduct

Issues that can give you a good start are https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[have the label "`good first issue`"] and maintainers are willing to help.
Feel free to choose these or any other ticket to contribute, or even create pull requests without a prior ticket.

Please have a look at the link:CONTRIBUTING.adoc["`How to Build and Contribute`"] documentation.
This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the link:CODE_OF_CONDUCT.adoc[Contributor Covenant code of conduct].

== Copyright and Licensing

Copyright (C) 2013-2020 Julien Viet, Erik Pragt and Alexander Schwartz.
Released under the Apache License, Version 2.0 (see link:LICENSE[LICENSE]).

== Credits

This plugin is based on the https://github.com/nicoulaj/idea-markdown[Intellij Markdown plugin by Julien Nicoulaud].

Also, great help was received from Erik Pragt, Harro Lissenberg, Alexander Schwartz and Dan Allen.
Thank you all for your support!
