= Frequently asked questions (FAQ)
:navtitle: Frequently asked questions
:description: Find answers to previously asked questions, or open a new issue to find a solution to your issue.

Missing an entry in the FAQ list? Please open an issue in the https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[GitHub issues^] for this project.

[NOTE]
--
This documentation website is still work in progress.
More content is available in the https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki[wiki of this plugin's GitHub repository].
--

== Troubleshooting

=== I'm using MPS and see exceptions, how can I fix this?

See xref:faq/troubleshooting-mps.adoc[] for more information.

=== The preview doesn't show some remote images! Is this a proxy issue?

The JCEF preview doesn't support the IDE's proxy settings.
See xref:faq/jcef-no-proxy-support.adoc[] for more information.

=== Pasting from clipboard removes leading spaces (aka indent). Why?

This is an automatic reformatting option in the IDE's settings.
Stripping leading spaces should not change your rendered output.

See xref:faq/indent-missing-on-pasting.adoc[] for more information.

=== The preview doesn't show and in the notification I see "`Errno::ENOENT message`".

This might be due to non-US-ASCII characters in folder names.

See xref:faq/errno-enoent.adoc[] for more information.

=== Something is not working as I expect it to work, where can I get help?

Please open an issue in the https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[GitHub issues^] for this project.

== Supporting the project

=== I'm a user of the plugin, where can I show my support?

Please consider adding a rating for the pluigin in the https://plugins.jetbrains.com/plugin/7391-asciidoc[JetBrains Marketplace].

This plugin is based on Asciidoctor and a lot of ideas from its community.
To support Asciidoctor, please consider contribute funds via https://opencollective.com/asciidoctor[Opencollective].
