= Frequently asked questions (FAQ)
:navtitle: Frequently asked questions
:description: Find answers to previously asked questions, or open a new issue to find a solution to your issue.

Missing an entry in the FAQ list?
Please open an issue in the https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[GitHub issues^] for this project.

== General Troubles

=== I'm using MPS and see exceptions. How can I fix this?

See xref:faq/troubleshooting-mps.adoc[] for more information.

=== There is an _ad-tag-include_ template in all my files. Why?

See xref:features/advanced/livetemplates.adoc#ad-tag-include[Special template _ad-tag-include_] on how this works and how to disable it if you don't need it.

=== There is an _.asciidoctor_ folder appearing all over my project. Why?

This is a folder that holds temporary files that are created for dynamic diagrams when running in any other mode than UNSAFE.

Read more in xref:features/preview/diagrams.adoc#temp-folder-asciidoctor[Temporary folder _.asciidoctor_ appearing in several places].

== Updating troubles

=== Updating the plugin via JetBrains Marketplace not working

Due to an error of the currently installed plugin version, the upgrade and download from the Marketplace might fail.

As a remedy, download the file from the Marketplace manually and install it xref::installation.adoc#download-install-from-disk[as described in the installation chapter].

== Editor Troubles

=== Pasting from clipboard removes leading spaces (aka indent). Why?

This is an automatic reformatting option in the IDE's settings.
Stripping leading spaces should not change your rendered output.

See xref:faq/indent-missing-on-pasting.adoc[] for more information.

=== How to avoid scrolling left/right for long lines?

An AsciiDoc recommended practice is to have link:https://asciidoctor.org/docs/asciidoc-recommended-practices/[_one sentence per line_].

See xref:recommended-settings.adoc#configuring-editor[section "`Configuring editor`" in chapter "`Configuring the plugin`"] on how to enable soft-wrap.

=== I'm editing a file that shows validation errors

The editor shows several validation warnings and errors, for example, for cross-references.
This works the best if the IDE opens all files that belong together as a project.

See xref:faq/validation-for-asciidoc-files.adoc[] for details.

== Interaction troubles

=== Whenever I run a code snippet from the editor, a new terminal tab opens

This might happen when a custom shell has been configured and the folder contains a blank.

Re-configure via menu:File[Settings...,Tools,Terminal,Shell path] and add quotes around the path and executable.

See xref:features/editor.adoc#interaction-new-terminal[Running shell commands from the same terminal] for more details.

== Preview Troubles

=== The preview doesn't show some remote images! Is this a proxy issue?

The JCEF preview doesn't support the IDE's proxy settings prior to IntelliJ 2021.1.
Configuring a proxy for JCEF requires an IDE restart.
See xref:faq/jcef-no-proxy-support.adoc[] for more information.

=== The preview doesn't show and in the notification I see "`Errno::ENOENT message`".

This might be due to non-US-ASCII characters in folder names.

See xref:faq/errno-enoent.adoc[] for more information.

=== The preview could not find executable to render diagrams

Some diagram types need external helpers to render diagrams in the preview.

See xref:faq/could-not-find-dot-executable.adoc[] for more information.

=== The preview is blurry!

This sometimes happens when using the JavaFX preview on high-resolution displays.

See xref:faq/blurry-preview.adoc[] for more information.

=== The preview is ugly!

This sometimes happens when using Swing preview.
This activates when neither JavaFX nor JCEF preview are available.

See chapters '`xref:features/preview/jcef-preview.adoc[]`' and '`xref:features/preview/javafx-preview.adoc[]`' for more information.

=== Could not find the 'dot' (or other) executable. How to fix it?

Some diagram types need helper applications installed locally.
Another alternative is to use a cloud-based renderer like Kroki.

See xref:faq/could-not-find-dot-executable.adoc[] for more information.

== PDF troubles

=== Creating a PDF with Kroki enabled shows URLs instead of diagrams

include::partial$kroki-pdf.adoc[leveloffset=+2]

=== Diagrams embedded in PDFs don't show arrows or text properly

Some SVG diagrams embed HTML to show text or arrows, for example, Mermaid or Diagrams.net.
This is not supported by Asciidoctor PDF.

See xref:faq/diagrams-in-pdf-without-text.adoc[] for more details.

== Other Troubles

=== Something is not working as I expect it to work, where can I get help?

Please open an issue in the https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[GitHub issues^] for this project.

== Supporting the project

=== I'm a user of the plugin, where can I show my support?

Please consider adding a rating for the plugin in the https://plugins.jetbrains.com/plugin/7391-asciidoc[JetBrains Marketplace].

This plugin is based on Asciidoctor and a lot of ideas from its community.
To support Asciidoctor, please consider contributing funds via https://opencollective.com/asciidoctor[Open Collective].
