= Features of the IntelliJ AsciiDoc plugin
:navtitle: Plugin's Features
:description: This plugin has a context-sensitive editor, configurable preview and can convert Markdown to AsciiDoc.

This document details the features available in the plugin to users of the plugin.
Use it as a reference guide to find out what the plugin can do today.
The plugin should work "`like any other IntelliJ plugin`" when it comes to shortcuts and configurations.
If not, describe the expected behaviour in a https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[GitHub issue].

Please consider contributing to this document: open a bug when something is unclear, missing or wrong.
You can even create a pull request for this document!

== Benefits of this plugin

The IntelliJ AsciiDoc Plugin adds to your IDE:

* A context-sensitive editor with syntax highlighting, auto-completion and in-line validation messages.
* A configurable preview to proofread and navigate the content.
* Integrations to a Markdown-to-AsciiDoc converter, in-line diagrams like PlantUML, xref:features/advanced/antora.adoc[Antora, a static site generator], and xref:features/advanced/spring-rest-docs.adoc[Spring REST docs].
* Convert AsciiDoc files to xref:features/advanced/creating-html.adoc[HTML], xref:features/advanced/creating-pdf.adoc[PDF] and xref:features/advanced/creating-docx.adoc[DOCX] files from within the IDE.

== Context-sensitive editor

* Recognizes the AsciiDoc file extension (.adoc, .asciidoc, .ad)
* Toolbar and context menu for basic formatting and to create tables.

Learn more about it in the xref:features/editor.adoc[] section.

== Advanced search functionality

* All named elements can be searched, like section titles, IDs, and attribute names.
* Two additional search scopes to filter searching in AsciiDoc content.

Learn more about it in the xref:features/search.adoc[] section.

== Configurable preview

* Provides a two-pane AsciiDoc preview editor based on https://github.com/asciidoctor/asciidoctorj[AsciidoctorJ] with a live preview.
+
By default, it has a vertical split and the preview is on the right.
Use the settings to flip editor and preview and change to a horizontal split.

Learn more about it in the xref:features/preview.adoc[] section.

== Integrations to the AsciiDoc ecosystem

* Refactor Markdown to AsciiDoc: Right-click on a file, or use the Refactor menu, and the Markdown document will be replaced by the AsciiDoc equivalent.
+
These supports undo when you're not happy with the result.

