= Overview of the IntelliJ AsciiDoc Plugin
:navtitle: Overview
:description: Write documentation without leaving your IDE. \
Preview your docs locally before publishing them. \
Collaborate using a version control system.

////
This is the start page of plugin's documentation, and therefore likely the first thing people read.
This doc provides a brief overview of the functionality this plugin provides.

Write about why it is a good idea to use AsciiDoc and the plugin (and maybe when not to use it).
Mention unique-selling-propositions (USP) that differentiate this plugin from others.

Assumed reader type: someone who is new to the plugin, but might have heard about AsciiDoc before.
////

{description}
Publish with confidence using automated builds.

== Writing technical documentation

When writing technical documentation, it needs a team effort where everyone contributes and collaborates.
For the content you write, you want to be able to publish for different audiences in different target formats like static HTML pages, in-line help or PDFs.

== Why to use AsciiDoc and IntelliJ

The AsciiDoc format allows you to write your content once and automate its publishing using standard build automation tools.

The IntelliJ family of IDEs like IntelliJ IDEA, GoLand, WebStorm or PyCharm allows you to efficiently navigate and edit your content.
It allows you to collaborate with other developers writers using version control systems like Git.

== How this plugin helps writers and developers

This plugin adds AsciiDoc functionality to your IDE to make your productive when writing your technical documentation.

It provides the writer with...

* a context-sensitive editor,
* a configurable preview and
* integrations to the AsciiDoc ecosystem.

== Where to go from here

To continue the journey with one of the following:

* Visit the
** (short) xref:quick-start.adoc[] guide or the
** (in depth) xref:technical-writing/index.adoc[] guide.
* Read about the xref:features.adoc[].
* Use the navigation on the left to learn about a specific topic you are interested in.

If you got questions, please raise them as a https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues[new GitHub issue].
