= Installing a preview release
:description: Preview-releases can be installed manually from the GitHub releases page.

{description}
Find the description on how to do this below.

If you want to install new pre-releases regularly, check out xref:user/add-eap-repository-to-ide.adoc[how to add the Early Access repository of the AsciiDoc plugin to your IDE].

== Installing a preview-release

All preview releases are available on the https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases[GitHub releases page of the plugin^].
Each release has a title and a short description linking to the GitHub issues that are part of the release.

To try out a preview release:

. Download the new release file `asciidoctor-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
. Go to menu:File[Settings... > Plugins > Gear Icon] (icon:gear[]).
. Choose menu:Install plugin from disk...[].
. Choose the downloaded file in the file selection dialogue.
. Restart the IDE to activate the new plugin version.

Use the GitHub issue numbers given in the release notes to join the discussion on the respective GitHub issues.
