= Upvote an IDEA issue
:navtitle: Upvote IDEA issues
:description: Now and then there is a bug in IntelliJ IDEA.

{description}
Or something needs to be implemented in IntelliJ IDEA, so this plugin can build new functionality on top of it.

Users can raise the visibility of these issues up-voting this issue by clicking on the thumbs-up icon (&#128077;) in the JetBrains YouTrack issue tracker.

This lists some issues Alexander (the current maintainer of the plugin) marked as important to him.
Have a look an up-vote those that are important to you as well to raise the visibility of these issues.

https://youtrack.jetbrains.com/issue/CWM-790[CWM-790]::
IntelliJ client doesn't show toolbar and split/preview window of custom editor

https://youtrack.jetbrains.com/issue/CWM-1550[CWM-1550]::
No markdown preview is shown

https://youtrack.jetbrains.com/issue/IDEA-276954[IDEA-276954]::
Assertion failed after changing settings

https://youtrack.jetbrains.com/issue/QD-1291[QD-1291]::
Qodana easy plugin installation

https://youtrack.jetbrains.com/issue/IDEA-292335[IDEA-292335]::
Make extension point org.intellij.markdown.markdownRunner independent of the markup language

https://youtrack.jetbrains.com/issue/IDEA-292343[IDEA-292343]::
When Markdown contains two commands in a line, both commands are disabled in gutter
