package org.asciidoc.intellij.psi;

import com.intellij.psi.impl.source.tree.FileElement;
import org.asciidoc.intellij.lexer.AsciiDocTokenTypes;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class AsciiDocSectionTest {

  private static class MockTitleAsciiDocSection extends AsciiDocSection {
    private String title;

    MockTitleAsciiDocSection(String title) {
      super(new FileElement(AsciiDocTokenTypes.WHITE_SPACE, ""));
      this.title = title;
    }

    @Override
    protected String getAttribute(String idprefix) {
      return "_";
    }

    @Override
    public String getTitle() {
      return title;
    }
  }

  @Test
  public void verifyIdContainsSeparators() {
    MockTitleAsciiDocSection section = new MockTitleAsciiDocSection("My Title.");
    assertEquals("_my_title", section.getAutogeneratedId());
  }

  @Test
  public void verifyMatchingIdIgnoresSuffix() {
    MockTitleAsciiDocSection section = new MockTitleAsciiDocSection("My Title.");
    assertTrue(section.matchesAutogeneratedId("_my_title_2"));
  }
}
