= Edit documentation content
:description: Learn how to contribute documentation changes for the plugin.

{description}

== Prerequisites

For small changes, writers can use the web browser and the web-based text editor of GitHub.

The preview of GitHub doesn't take into account the Antora macros, therefore, consider using the IntelliJ AsciiDoc plugin for changes.

== How-to edit content using only a web browser

Follow these steps to change the documentation content on the plugin's homepage using the browser:

. Click on the "`Edit this page`" link on the documentation website of the plugin
. Edit the content
. Follow the instructions on the end of the page to commit the changes, creating a fork of the repository and submitting a pull request

Once a maintainer approves the pull request, the changes will be visible on the plugin's homepage.

*Optional:* Writers can build the plugin's documentation website locally for a preview by following the steps in xref:docs/change-documentation-theme.adoc[].

== How-to edit content using an IDE on the local PC

Follow these steps to change the documentation content on the plugin's homepage:

. Fork and clone the plugin's repository: https://github.com/asciidoctor/asciidoctor-intellij-plugin
. Change documentation in the sub-folder _doc_
. Proofread changes in the editor's live preview
. Update navigation contents in the _nav.adoc_ file as needed to re-ordered, added or removed content
. Create a pull request on GitHub

Once a maintainer approves the pull request, the changes will be visible on the plugin's homepage.

*Optional:* Writers can build the plugin's documentation website locally for a preview by following the steps in xref:docs/change-documentation-theme.adoc[].
