/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

package org.asciidoc.intellij.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>asciidoc.flex</tt>
 */
class _AsciiDocLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int INSIDE_LINE = 2;
  public static final int HEADING = 4;
  public static final int LISTING_BLOCK = 6;
  public static final int INSIDE_LISTING_BLOCK_LINE = 8;
  public static final int COMMENT_BLOCK = 10;
  public static final int INSIDE_COMMENT_BLOCK_LINE = 12;
  public static final int EXAMPLE_BLOCK = 14;
  public static final int INSIDE_EXAMPLE_BLOCK_LINE = 16;
  public static final int PASSTRHOUGH_BLOCK = 18;
  public static final int INSIDE_PASSTRHOUGH_BLOCK_LINE = 20;
  public static final int SIDEBAR_BLOCK = 22;
  public static final int INSIDE_SIDEBAR_BLOCK_LINE = 24;
  public static final int QUOTE_BLOCK = 26;
  public static final int INSIDE_QUOTE_BLOCK_LINE = 28;
  public static final int BLOCK_MACRO = 30;
  public static final int BLOCK_MACRO_ATTRS = 32;
  public static final int TITLE = 34;
  public static final int BLOCK_ATTRS = 36;
  public static final int MONOSPACE = 38;
  public static final int INSIDE_MONOSPACE = 40;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 
    16, 16, 17, 17, 18, 18, 19, 19, 20, 20
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [9, 6, 6]
   * Total runtime size is 1568 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>12]|((ch>>6)&0x3f)]<<6)|(ch&0x3f)];
  }

  /* The ZZ_CMAP_Z table has 272 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\100\1\200\u010d\100");

  /* The ZZ_CMAP_Y table has 192 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\175\3\1\4\77\3");

  /* The ZZ_CMAP_A table has 320 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\12\1\2\3\13\22\0\1\1\11\0\1\7\1\4\1\0\1\5\1\17\1\3\12\15\1\16\2\0"+
    "\1\6\3\0\32\15\1\11\1\0\1\21\1\14\1\10\1\20\32\15\3\0\1\14\6\0\1\13\242\0"+
    "\2\13\26\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\25\0\1\1\1\2\6\1\1\3\1\1\1\0\2\1"+
    "\1\4\1\5\1\6\1\4\1\7\1\10\1\11\1\10"+
    "\1\12\1\13\1\12\1\14\1\15\1\14\1\16\1\17"+
    "\1\16\1\20\1\21\1\20\1\22\1\23\1\22\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\0\1\33"+
    "\10\0\1\34\7\0\3\33\2\0\3\35\12\0\1\36"+
    "\1\33\5\0\2\37\6\0\1\40\1\41\1\42\1\43"+
    "\1\0\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\22\0\44\0\66\0\110\0\132\0\154\0\176"+
    "\0\220\0\242\0\264\0\306\0\330\0\352\0\374\0\u010e"+
    "\0\u0120\0\u0132\0\u0144\0\u0156\0\u0168\0\u017a\0\u0168\0\u018c"+
    "\0\u019e\0\u01b0\0\u01c2\0\u01d4\0\u01e6\0\u0168\0\u0168\0\u017a"+
    "\0\u01f8\0\u020a\0\u017a\0\u0168\0\u0168\0\u0168\0\u0168\0\u0168"+
    "\0\u0168\0\u021c\0\u0168\0\u0168\0\u022e\0\u0168\0\u0168\0\u0240"+
    "\0\u0168\0\u0168\0\u0252\0\u0168\0\u0168\0\u0264\0\u0168\0\u0168"+
    "\0\u0276\0\u0168\0\u0168\0\u0168\0\u0168\0\u0168\0\u0168\0\u0168"+
    "\0\u0288\0\u029a\0\u02ac\0\u02be\0\u02d0\0\u02e2\0\u02f4\0\u0306"+
    "\0\u01f8\0\u0318\0\u0168\0\u032a\0\u033c\0\u034e\0\u0360\0\u0372"+
    "\0\u0384\0\u0396\0\u03a8\0\u03ba\0\u03cc\0\u03de\0\u03f0\0\u017a"+
    "\0\u02d0\0\u0168\0\u0402\0\u0414\0\u0426\0\u0438\0\u044a\0\u045c"+
    "\0\u046e\0\u0480\0\u0492\0\u04a4\0\u0168\0\u04b6\0\u04c8\0\u04da"+
    "\0\u04ec\0\u04fe\0\u0510\0\u017a\0\u0168\0\u0522\0\u0534\0\u0546"+
    "\0\u0558\0\u056a\0\u057c\0\u0288\0\u0288\0\u0288\0\u0288\0\u058e"+
    "\0\u0288\0\u0288\0\u0168\0\u0168\0\u0168\0\u0168\0\u0168\0\u0168"+
    "\0\u05a0\0\u05b2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\26\1\41\1\26\1\42\1\43"+
    "\1\26\2\44\1\45\10\44\1\0\4\44\1\46\1\44"+
    "\2\47\1\45\10\47\1\0\6\47\2\50\1\51\2\50"+
    "\1\52\5\50\1\0\10\50\1\51\10\50\1\0\6\50"+
    "\2\53\1\54\1\55\7\53\1\0\10\53\1\54\10\53"+
    "\1\0\6\53\2\56\1\57\3\56\1\60\4\56\1\0"+
    "\10\56\1\57\10\56\1\0\6\56\2\61\1\62\1\61"+
    "\1\63\6\61\1\0\10\61\1\62\10\61\1\0\6\61"+
    "\2\64\1\65\4\64\1\66\3\64\1\0\10\64\1\65"+
    "\10\64\1\0\6\64\2\67\1\70\5\67\1\71\2\67"+
    "\1\0\10\67\1\70\10\67\1\0\6\67\2\72\1\45"+
    "\6\72\1\73\1\72\1\0\6\72\2\74\1\45\10\74"+
    "\1\0\6\74\2\75\1\45\10\75\1\0\6\75\2\76"+
    "\1\45\10\76\1\0\5\76\1\77\2\100\1\0\10\100"+
    "\1\0\4\100\1\37\1\100\22\0\2\40\1\101\10\40"+
    "\1\0\10\40\1\101\1\102\7\40\1\0\10\40\1\101"+
    "\1\40\1\103\6\40\1\0\10\40\1\101\2\40\1\104"+
    "\5\40\1\0\7\40\1\105\1\101\3\40\1\106\3\40"+
    "\1\105\1\0\10\40\1\101\4\40\1\107\3\40\1\0"+
    "\10\40\1\101\5\40\1\110\2\40\1\0\1\40\1\111"+
    "\1\112\5\40\1\101\5\40\1\111\2\40\1\0\1\40"+
    "\1\111\1\112\3\40\1\113\1\0\15\113\1\0\2\113"+
    "\5\0\1\114\17\0\1\115\24\0\1\116\17\0\1\117"+
    "\24\0\1\120\22\0\1\121\15\0\3\122\5\0\1\122"+
    "\5\0\2\123\1\101\1\124\7\123\1\125\6\123\2\40"+
    "\1\101\1\40\1\126\6\40\1\0\10\40\1\101\2\40"+
    "\1\127\5\40\1\0\6\40\1\130\1\131\1\101\7\130"+
    "\1\131\1\132\6\130\1\40\1\105\1\101\3\40\1\133"+
    "\3\40\1\105\1\0\10\40\1\101\4\40\1\134\3\40"+
    "\1\0\10\40\1\101\5\40\1\135\2\40\1\0\1\40"+
    "\1\111\1\112\5\40\1\101\10\40\1\0\2\40\1\136"+
    "\3\40\5\0\1\137\17\0\1\140\24\0\1\141\17\0"+
    "\1\142\24\0\1\143\22\0\1\144\13\0\1\145\1\0"+
    "\3\122\5\0\1\122\5\0\2\123\1\101\10\123\1\125"+
    "\10\123\1\101\1\146\7\123\1\125\6\123\2\125\1\0"+
    "\17\125\2\40\1\101\1\40\1\147\6\40\1\0\10\40"+
    "\1\101\2\40\1\150\5\40\1\0\7\40\1\105\1\101"+
    "\3\40\1\151\3\40\1\105\1\0\10\40\1\101\4\40"+
    "\1\152\3\40\1\0\10\40\1\101\5\40\1\153\2\40"+
    "\1\0\1\40\1\111\1\112\3\40\2\154\1\101\10\154"+
    "\1\155\6\154\5\0\1\156\17\0\1\157\24\0\1\160"+
    "\17\0\1\161\24\0\1\162\22\0\1\163\11\0\2\123"+
    "\1\164\1\146\7\123\1\125\6\123\2\40\1\165\1\40"+
    "\1\147\6\40\1\0\10\40\1\166\2\40\1\150\5\40"+
    "\1\0\7\40\1\105\1\167\3\40\1\170\3\40\1\105"+
    "\1\0\10\40\1\171\4\40\1\152\3\40\1\0\10\40"+
    "\1\172\5\40\1\153\2\40\1\0\1\40\1\111\1\112"+
    "\3\40\2\0\1\173\2\0\1\156\16\0\1\174\1\157"+
    "\20\0\1\175\3\0\1\160\15\0\1\176\1\0\1\161"+
    "\17\0\1\177\4\0\1\162\14\0\1\200\5\0\1\163"+
    "\11\0\1\40\1\105\1\167\3\40\1\201\3\40\1\105"+
    "\1\0\7\40\1\105\1\167\3\40\1\202\3\40\1\105"+
    "\1\0\10\40\1\167\3\40\1\202\4\40\1\0\6\40";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1476];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\24\0\1\10\1\1\1\11\6\1\2\11\1\0\3\1"+
    "\6\11\1\1\2\11\1\1\2\11\1\1\2\11\1\1"+
    "\2\11\1\1\2\11\1\1\7\11\1\0\1\1\10\0"+
    "\1\11\7\0\3\1\2\0\2\1\1\11\12\0\1\11"+
    "\1\1\5\0\1\1\1\11\6\0\4\1\1\0\2\1"+
    "\6\11\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[130];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
 int blockDelimiterLength;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _AsciiDocLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yybegin(INSIDE_LINE); return AsciiDocTokenTypes.TEXT;
            }
          case 44: break;
          case 2: 
            { return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 45: break;
          case 3: 
            { yybegin(BLOCK_ATTRS); return AsciiDocTokenTypes.BLOCK_ATTRS_START;
            }
          case 46: break;
          case 4: 
            { yybegin(MONOSPACE); return AsciiDocTokenTypes.MONOSPACE;
            }
          case 47: break;
          case 5: 
            { return AsciiDocTokenTypes.TEXT;
            }
          case 48: break;
          case 6: 
            { yybegin(YYINITIAL); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 49: break;
          case 7: 
            { return AsciiDocTokenTypes.HEADING;
            }
          case 50: break;
          case 8: 
            { yybegin(INSIDE_LISTING_BLOCK_LINE); return AsciiDocTokenTypes.LISTING_TEXT;
            }
          case 51: break;
          case 9: 
            { yybegin(LISTING_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 52: break;
          case 10: 
            { yybegin(INSIDE_COMMENT_BLOCK_LINE); return AsciiDocTokenTypes.BLOCK_COMMENT;
            }
          case 53: break;
          case 11: 
            { yybegin(COMMENT_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 54: break;
          case 12: 
            { yybegin(INSIDE_EXAMPLE_BLOCK_LINE); return AsciiDocTokenTypes.EXAMPLE_BLOCK;
            }
          case 55: break;
          case 13: 
            { yybegin(EXAMPLE_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 56: break;
          case 14: 
            { yybegin(INSIDE_PASSTRHOUGH_BLOCK_LINE); return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK;
            }
          case 57: break;
          case 15: 
            { yybegin(PASSTRHOUGH_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 58: break;
          case 16: 
            { yybegin(INSIDE_SIDEBAR_BLOCK_LINE); return AsciiDocTokenTypes.SIDEBAR_BLOCK;
            }
          case 59: break;
          case 17: 
            { yybegin(SIDEBAR_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 60: break;
          case 18: 
            { yybegin(INSIDE_QUOTE_BLOCK_LINE); return AsciiDocTokenTypes.QUOTE_BLOCK;
            }
          case 61: break;
          case 19: 
            { yybegin(QUOTE_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 62: break;
          case 20: 
            { return AsciiDocTokenTypes.BLOCK_MACRO_BODY;
            }
          case 63: break;
          case 21: 
            { yybegin(BLOCK_MACRO_ATTRS); return AsciiDocTokenTypes.BLOCK_MACRO_ATTRIBUTES;
            }
          case 64: break;
          case 22: 
            { return AsciiDocTokenTypes.BLOCK_MACRO_ATTRIBUTES;
            }
          case 65: break;
          case 23: 
            { return AsciiDocTokenTypes.TITLE;
            }
          case 66: break;
          case 24: 
            { return AsciiDocTokenTypes.BLOCK_ATTR_NAME;
            }
          case 67: break;
          case 25: 
            { yybegin(YYINITIAL); return AsciiDocTokenTypes.BLOCK_ATTRS_END;
            }
          case 68: break;
          case 26: 
            { return AsciiDocTokenTypes.MONOSPACE;
            }
          case 69: break;
          case 27: 
            { return AsciiDocTokenTypes.LINE_COMMENT;
            }
          case 70: break;
          case 28: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzStartRead, 1);
            { yybegin(TITLE); return AsciiDocTokenTypes.TITLE;
            }
          case 71: break;
          case 29: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzMarkedPos, -1);
            { yybegin(HEADING); return AsciiDocTokenTypes.HEADING;
            }
          case 72: break;
          case 30: 
            { String[] part = yytext().toString().split("\n");
      boolean sameCharactersInSecondLine = true;
      // must be same character all of second line
      for(int i = 0; i < part[1].length(); ++i) {
        if(part[1].charAt(0) != part[1].charAt(i)) {
          sameCharactersInSecondLine = false;
          break;
        }
      }
      // must be same length plus/minus one character
      if(part[0].length() >= part[1].length() -1
         && part[0].length() <= part[1].length() +1
         && sameCharactersInSecondLine) {
        return AsciiDocTokenTypes.HEADING;
      } else {
        yypushback(yylength()-1); // part[1].length() + 1
        yybegin(INSIDE_LINE);
        return AsciiDocTokenTypes.TEXT;
      }
            }
          case 73: break;
          case 31: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzMarkedPos, -1);
            { yybegin(BLOCK_MACRO); return AsciiDocTokenTypes.BLOCK_MACRO_ID;
            }
          case 74: break;
          case 32: 
            { yybegin(COMMENT_BLOCK); blockDelimiterLength = yylength(); return AsciiDocTokenTypes.BLOCK_COMMENT;
            }
          case 75: break;
          case 33: 
            { yybegin(PASSTRHOUGH_BLOCK); blockDelimiterLength = yylength(); return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK_DELIMITER;
            }
          case 76: break;
          case 34: 
            { yybegin(LISTING_BLOCK); blockDelimiterLength = yylength(); return AsciiDocTokenTypes.LISTING_BLOCK_DELIMITER;
            }
          case 77: break;
          case 35: 
            { yybegin(EXAMPLE_BLOCK); blockDelimiterLength = yylength(); return AsciiDocTokenTypes.EXAMPLE_BLOCK_DELIMITER;
            }
          case 78: break;
          case 36: 
            { yybegin(SIDEBAR_BLOCK); blockDelimiterLength = yylength(); return AsciiDocTokenTypes.SIDEBAR_BLOCK_DELIMITER;
            }
          case 79: break;
          case 37: 
            { yybegin(QUOTE_BLOCK); blockDelimiterLength = yylength(); return AsciiDocTokenTypes.QUOTE_BLOCK_DELIMITER;
            }
          case 80: break;
          case 38: 
            { if (yylength() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.LISTING_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.LISTING_TEXT;
    }
            }
          case 81: break;
          case 39: 
            { if (yylength() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.BLOCK_COMMENT;
    } else {
      return AsciiDocTokenTypes.BLOCK_COMMENT;
    }
            }
          case 82: break;
          case 40: 
            { if (yylength() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.EXAMPLE_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.EXAMPLE_BLOCK;
    }
            }
          case 83: break;
          case 41: 
            { if (yylength() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK;
    }
            }
          case 84: break;
          case 42: 
            { if (yylength() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.SIDEBAR_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.SIDEBAR_BLOCK;
    }
            }
          case 85: break;
          case 43: 
            { if (yylength() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.QUOTE_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.QUOTE_BLOCK;
    }
            }
          case 86: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
