/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

package org.asciidoc.intellij.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>asciidoc.flex</tt>
 */
class _AsciiDocLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int INSIDE_LINE = 2;
  public static final int HEADING = 4;
  public static final int LISTING_BLOCK = 6;
  public static final int INSIDE_LISTING_BLOCK_LINE = 8;
  public static final int COMMENT_BLOCK = 10;
  public static final int INSIDE_COMMENT_BLOCK_LINE = 12;
  public static final int EXAMPLE_BLOCK = 14;
  public static final int INSIDE_EXAMPLE_BLOCK_LINE = 16;
  public static final int PASSTRHOUGH_BLOCK = 18;
  public static final int INSIDE_PASSTRHOUGH_BLOCK_LINE = 20;
  public static final int SIDEBAR_BLOCK = 22;
  public static final int INSIDE_SIDEBAR_BLOCK_LINE = 24;
  public static final int QUOTE_BLOCK = 26;
  public static final int INSIDE_QUOTE_BLOCK_LINE = 28;
  public static final int BLOCK_MACRO = 30;
  public static final int BLOCK_MACRO_ATTRS = 32;
  public static final int TITLE = 34;
  public static final int BLOCK_ATTRS = 36;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 
    16, 16, 17, 17, 18, 18
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [9, 6, 6]
   * Total runtime size is 1568 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>12]|((ch>>6)&0x3f)]<<6)|(ch&0x3f)];
  }

  /* The ZZ_CMAP_Z table has 272 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\1\100\1\200\u010d\100");

  /* The ZZ_CMAP_Y table has 192 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\1\2\175\3\1\4\77\3");

  /* The ZZ_CMAP_A table has 320 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\13\1\2\3\14\22\0\1\1\2\0\1\11\6\0\1\7\1\4\1\0\1\5\1\20\1\3\12\16\1"+
    "\17\2\0\1\6\3\0\32\16\1\12\1\0\1\21\1\15\1\10\1\0\32\16\3\0\1\15\6\0\1\14"+
    "\242\0\2\14\26\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\23\0\1\1\1\2\7\1\1\3\3\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\7\1\11\1\12\1\11\1\13"+
    "\1\14\1\13\1\15\1\16\1\15\1\17\1\20\1\17"+
    "\1\21\1\22\1\21\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\0\1\31\11\0\1\32\7\0\3\31\2\0"+
    "\3\33\14\0\1\34\1\31\5\0\2\35\7\0\1\31"+
    "\1\36\1\0\1\37\1\0\1\40\1\0\1\41\2\0"+
    "\1\42\1\0\1\43\2\0\1\44\1\0\1\45\1\0"+
    "\1\46\1\0\1\47\1\0\1\50\1\0\1\51\1\33"+
    "\4\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\22\0\44\0\66\0\110\0\132\0\154\0\176"+
    "\0\220\0\242\0\264\0\306\0\330\0\352\0\374\0\u010e"+
    "\0\u0120\0\u0132\0\u0144\0\u0156\0\u0168\0\u017a\0\u018c\0\u019e"+
    "\0\u01b0\0\u01c2\0\u01d4\0\u01e6\0\u0168\0\u0168\0\u01f8\0\u020a"+
    "\0\u0168\0\u0168\0\u0168\0\u0168\0\u0168\0\u021c\0\u0168\0\u0168"+
    "\0\u022e\0\u0168\0\u0168\0\u0240\0\u0168\0\u0168\0\u0252\0\u0168"+
    "\0\u0168\0\u0264\0\u0168\0\u0168\0\u0276\0\u0168\0\u0168\0\u0168"+
    "\0\u0168\0\u0168\0\u0168\0\u0156\0\u0288\0\u029a\0\u02ac\0\u02be"+
    "\0\u02d0\0\u02e2\0\u02f4\0\u0306\0\u01f8\0\u0318\0\u032a\0\u0168"+
    "\0\u033c\0\u034e\0\u0360\0\u0372\0\u0384\0\u0396\0\u03a8\0\u03ba"+
    "\0\u03cc\0\u03de\0\u03f0\0\u0402\0\u0156\0\u02d0\0\u0168\0\u0414"+
    "\0\u0426\0\u0438\0\u044a\0\u045c\0\u046e\0\u0480\0\u0492\0\u04a4"+
    "\0\u04b6\0\u04c8\0\u04da\0\u0168\0\u04ec\0\u04fe\0\u0510\0\u0522"+
    "\0\u0534\0\u0546\0\u0156\0\u0168\0\u0558\0\u056a\0\u057c\0\u058e"+
    "\0\u05a0\0\u05b2\0\u05c4\0\u05d6\0\u0288\0\u05e8\0\u0288\0\u05fa"+
    "\0\u0288\0\u060c\0\u0288\0\u061e\0\u0630\0\u0288\0\u0642\0\u0288"+
    "\0\u0654\0\u0666\0\u0168\0\u0678\0\u0168\0\u068a\0\u0168\0\u069c"+
    "\0\u0168\0\u06ae\0\u0168\0\u06c0\0\u0168\0\u060c\0\u06d2\0\u06e4"+
    "\0\u06f6\0\u0708";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\2\24\1\37\1\24\1\40\1\24"+
    "\2\41\1\42\17\41\2\43\1\42\17\43\2\44\1\45"+
    "\2\44\1\46\16\44\1\45\17\44\2\47\1\50\1\51"+
    "\20\47\1\50\17\47\2\52\1\53\3\52\1\54\15\52"+
    "\1\53\17\52\2\55\1\56\1\55\1\57\17\55\1\56"+
    "\17\55\2\60\1\61\4\60\1\62\14\60\1\61\17\60"+
    "\2\63\1\64\5\63\1\65\13\63\1\64\17\63\2\66"+
    "\1\42\7\66\1\67\7\66\2\70\1\42\17\70\2\71"+
    "\1\42\17\71\2\72\1\42\16\72\1\73\2\74\1\75"+
    "\11\74\1\0\5\74\22\0\2\74\1\75\1\76\10\74"+
    "\1\0\7\74\1\75\1\74\1\77\7\74\1\0\7\74"+
    "\1\75\2\74\1\100\6\74\1\0\6\74\1\101\1\75"+
    "\3\74\1\102\4\74\1\101\1\0\7\74\1\75\4\74"+
    "\1\103\4\74\1\0\7\74\1\75\5\74\1\104\3\74"+
    "\1\0\1\74\1\105\1\106\3\74\1\101\1\75\6\74"+
    "\1\107\1\74\1\101\1\0\7\74\1\75\5\74\1\105"+
    "\3\74\1\0\1\74\1\105\1\106\2\74\1\110\1\0"+
    "\16\110\1\0\1\110\5\0\1\111\17\0\1\112\24\0"+
    "\1\113\17\0\1\114\24\0\1\115\22\0\1\116\15\0"+
    "\3\117\6\0\1\117\4\0\2\120\1\75\1\121\10\120"+
    "\1\122\5\120\2\74\1\75\1\74\1\123\7\74\1\0"+
    "\7\74\1\75\2\74\1\124\6\74\1\0\5\74\1\125"+
    "\1\126\1\75\10\125\1\126\1\127\5\125\1\74\1\101"+
    "\1\75\3\74\1\130\4\74\1\101\1\0\7\74\1\75"+
    "\4\74\1\131\4\74\1\0\7\74\1\75\5\74\1\132"+
    "\3\74\1\0\1\74\1\105\1\106\4\74\1\75\11\74"+
    "\1\0\2\74\1\133\3\74\1\101\1\75\6\74\1\134"+
    "\1\74\1\101\1\0\5\74\5\0\1\135\17\0\1\136"+
    "\24\0\1\137\17\0\1\140\24\0\1\141\22\0\1\142"+
    "\12\0\1\143\1\144\1\0\3\117\4\0\1\143\1\0"+
    "\1\117\4\0\2\120\1\75\11\120\1\122\7\120\1\75"+
    "\1\145\10\120\1\122\5\120\2\122\1\0\17\122\2\74"+
    "\1\75\1\74\1\146\7\74\1\0\7\74\1\75\2\74"+
    "\1\147\6\74\1\0\6\74\1\101\1\75\3\74\1\150"+
    "\4\74\1\101\1\0\7\74\1\75\4\74\1\151\4\74"+
    "\1\0\7\74\1\75\5\74\1\152\3\74\1\0\1\74"+
    "\1\105\1\106\2\74\2\153\1\75\11\153\1\154\5\153"+
    "\1\74\1\101\1\75\6\74\1\155\1\74\1\101\1\0"+
    "\5\74\5\0\1\156\17\0\1\157\24\0\1\160\17\0"+
    "\1\161\24\0\1\162\22\0\1\163\12\0\1\143\1\144"+
    "\10\0\1\143\6\0\1\120\1\164\1\165\1\145\7\120"+
    "\1\164\1\122\5\120\1\74\1\166\1\167\1\74\1\146"+
    "\6\74\1\166\1\0\6\74\1\170\1\171\2\74\1\147"+
    "\5\74\1\170\1\0\6\74\1\172\1\173\3\74\1\174"+
    "\4\74\1\172\1\0\6\74\1\175\1\176\4\74\1\151"+
    "\3\74\1\175\1\0\6\74\1\177\1\200\5\74\1\152"+
    "\2\74\1\177\1\0\1\74\1\105\1\106\3\74\1\101"+
    "\1\75\6\74\1\201\1\74\1\101\1\0\5\74\1\0"+
    "\1\202\1\203\2\0\1\156\5\0\1\202\7\0\1\204"+
    "\1\205\1\157\7\0\1\204\7\0\1\206\1\207\3\0"+
    "\1\160\4\0\1\206\7\0\1\210\1\211\1\0\1\161"+
    "\6\0\1\210\7\0\1\212\1\213\4\0\1\162\3\0"+
    "\1\212\7\0\1\214\1\215\5\0\1\163\2\0\1\214"+
    "\6\0\1\120\1\164\1\165\10\120\1\164\1\122\5\120"+
    "\1\74\1\166\1\167\10\74\1\166\1\0\6\74\1\170"+
    "\1\171\10\74\1\170\1\0\5\74\1\125\1\216\1\173"+
    "\10\125\1\216\1\127\5\125\1\74\1\172\1\173\3\74"+
    "\1\217\4\74\1\172\1\0\6\74\1\175\1\176\10\74"+
    "\1\175\1\0\6\74\1\177\1\200\10\74\1\177\1\0"+
    "\6\74\1\101\1\75\6\74\1\220\1\74\1\101\1\0"+
    "\5\74\1\0\1\202\1\203\10\0\1\202\7\0\1\204"+
    "\1\205\10\0\1\204\7\0\1\206\1\207\10\0\1\206"+
    "\7\0\1\210\1\211\10\0\1\210\7\0\1\212\1\213"+
    "\10\0\1\212\7\0\1\214\1\215\10\0\1\214\6\0"+
    "\1\74\1\172\1\173\3\74\1\221\4\74\1\172\1\0"+
    "\6\74\1\101\1\75\10\74\1\101\1\0\6\74\1\222"+
    "\1\173\3\74\1\221\4\74\1\222\1\0\6\74\1\222"+
    "\1\173\10\74\1\222\1\0\5\74";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1818];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\23\0\1\1\1\11\7\1\2\11\2\1\5\11\1\1"+
    "\2\11\1\1\2\11\1\1\2\11\1\1\2\11\1\1"+
    "\2\11\1\1\6\11\2\0\1\1\11\0\1\11\7\0"+
    "\3\1\2\0\2\1\1\11\14\0\1\11\1\1\5\0"+
    "\1\1\1\11\7\0\2\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\2\0\1\1\1\0\1\1\2\0\1\11"+
    "\1\0\1\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\1\4\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
 int blockDelimiterLength;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  _AsciiDocLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { yybegin(INSIDE_LINE); return AsciiDocTokenTypes.TEXT;
            }
          case 42: break;
          case 2: 
            { return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 43: break;
          case 3: 
            { yybegin(BLOCK_ATTRS); return AsciiDocTokenTypes.BLOCK_ATTRS_START;
            }
          case 44: break;
          case 4: 
            { return AsciiDocTokenTypes.TEXT;
            }
          case 45: break;
          case 5: 
            { yybegin(YYINITIAL); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 46: break;
          case 6: 
            { return AsciiDocTokenTypes.HEADING;
            }
          case 47: break;
          case 7: 
            { yybegin(INSIDE_LISTING_BLOCK_LINE); return AsciiDocTokenTypes.LISTING_TEXT;
            }
          case 48: break;
          case 8: 
            { yybegin(LISTING_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 49: break;
          case 9: 
            { yybegin(INSIDE_COMMENT_BLOCK_LINE); return AsciiDocTokenTypes.BLOCK_COMMENT;
            }
          case 50: break;
          case 10: 
            { yybegin(COMMENT_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 51: break;
          case 11: 
            { yybegin(INSIDE_EXAMPLE_BLOCK_LINE); return AsciiDocTokenTypes.EXAMPLE_BLOCK;
            }
          case 52: break;
          case 12: 
            { yybegin(EXAMPLE_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 53: break;
          case 13: 
            { yybegin(INSIDE_PASSTRHOUGH_BLOCK_LINE); return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK;
            }
          case 54: break;
          case 14: 
            { yybegin(PASSTRHOUGH_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 55: break;
          case 15: 
            { yybegin(INSIDE_SIDEBAR_BLOCK_LINE); return AsciiDocTokenTypes.SIDEBAR_BLOCK;
            }
          case 56: break;
          case 16: 
            { yybegin(SIDEBAR_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 57: break;
          case 17: 
            { yybegin(INSIDE_QUOTE_BLOCK_LINE); return AsciiDocTokenTypes.QUOTE_BLOCK;
            }
          case 58: break;
          case 18: 
            { yybegin(QUOTE_BLOCK); return AsciiDocTokenTypes.LINE_BREAK;
            }
          case 59: break;
          case 19: 
            { return AsciiDocTokenTypes.BLOCK_MACRO_BODY;
            }
          case 60: break;
          case 20: 
            { yybegin(BLOCK_MACRO_ATTRS); return AsciiDocTokenTypes.BLOCK_MACRO_ATTRIBUTES;
            }
          case 61: break;
          case 21: 
            { return AsciiDocTokenTypes.BLOCK_MACRO_ATTRIBUTES;
            }
          case 62: break;
          case 22: 
            { return AsciiDocTokenTypes.TITLE;
            }
          case 63: break;
          case 23: 
            { return AsciiDocTokenTypes.BLOCK_ATTR_NAME;
            }
          case 64: break;
          case 24: 
            { yybegin(YYINITIAL); return AsciiDocTokenTypes.BLOCK_ATTRS_END;
            }
          case 65: break;
          case 25: 
            { return AsciiDocTokenTypes.LINE_COMMENT;
            }
          case 66: break;
          case 26: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzStartRead, 1);
            { yybegin(TITLE); return AsciiDocTokenTypes.TITLE;
            }
          case 67: break;
          case 27: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzMarkedPos, -1);
            { yybegin(HEADING); return AsciiDocTokenTypes.HEADING;
            }
          case 68: break;
          case 28: 
            { String[] part = yytext().toString().split("\n");
      // remove all trailing white space
      String heading = part[0].replaceAll("[ \t]*$","");
      String underlining = part[1].replaceAll("[ \t]*$","");
      boolean sameCharactersInSecondLine = true;
      // must be same character all of second line
      for(int i = 0; i < underlining.length(); ++i) {
        if(underlining.charAt(0) != underlining.charAt(i)) {
          sameCharactersInSecondLine = false;
          break;
        }
      }
      // must be same length plus/minus one character
      if(heading.length() >= underlining.length() -1
         && heading.length() <= underlining.length() +1
         && sameCharactersInSecondLine) {
        yypushback(1);
        return AsciiDocTokenTypes.HEADING;
      } else {
        yypushback(yylength()-1); // heading.length() + 1
        yybegin(INSIDE_LINE);
        return AsciiDocTokenTypes.TEXT;
      }
            }
          case 69: break;
          case 29: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL/*, zzStartRead, zzEndRead - zzStartRead*/, zzMarkedPos, -1);
            { yybegin(BLOCK_MACRO); return AsciiDocTokenTypes.BLOCK_MACRO_ID;
            }
          case 70: break;
          case 30: 
            { yybegin(COMMENT_BLOCK); blockDelimiterLength = yytext().toString().trim().length(); return AsciiDocTokenTypes.BLOCK_COMMENT;
            }
          case 71: break;
          case 31: 
            { yybegin(PASSTRHOUGH_BLOCK); blockDelimiterLength = yytext().toString().trim().length(); return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK_DELIMITER;
            }
          case 72: break;
          case 32: 
            { yybegin(LISTING_BLOCK); blockDelimiterLength = yytext().toString().trim().length(); return AsciiDocTokenTypes.LISTING_BLOCK_DELIMITER;
            }
          case 73: break;
          case 33: 
            { yybegin(EXAMPLE_BLOCK); blockDelimiterLength = yytext().toString().trim().length(); return AsciiDocTokenTypes.EXAMPLE_BLOCK_DELIMITER;
            }
          case 74: break;
          case 34: 
            { yybegin(SIDEBAR_BLOCK); blockDelimiterLength = yytext().toString().trim().length(); return AsciiDocTokenTypes.SIDEBAR_BLOCK_DELIMITER;
            }
          case 75: break;
          case 35: 
            { yybegin(QUOTE_BLOCK); blockDelimiterLength = yytext().toString().trim().length(); return AsciiDocTokenTypes.QUOTE_BLOCK_DELIMITER;
            }
          case 76: break;
          case 36: 
            { if (yytext().toString().trim().length() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.LISTING_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.LISTING_TEXT;
    }
            }
          case 77: break;
          case 37: 
            { if (yytext().toString().trim().length() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.BLOCK_COMMENT;
    } else {
      return AsciiDocTokenTypes.BLOCK_COMMENT;
    }
            }
          case 78: break;
          case 38: 
            { if (yytext().toString().trim().length() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.EXAMPLE_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.EXAMPLE_BLOCK;
    }
            }
          case 79: break;
          case 39: 
            { if (yytext().toString().trim().length() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.PASSTRHOUGH_BLOCK;
    }
            }
          case 80: break;
          case 40: 
            { if (yytext().toString().trim().length() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.SIDEBAR_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.SIDEBAR_BLOCK;
    }
            }
          case 81: break;
          case 41: 
            { if (yytext().toString().trim().length() == blockDelimiterLength) {
      yybegin(YYINITIAL);
      return AsciiDocTokenTypes.QUOTE_BLOCK_DELIMITER;
    } else {
      return AsciiDocTokenTypes.QUOTE_BLOCK;
    }
            }
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
