= Setup for technical writing
:description: This article guides users new to IntelliJ IDEA through the necessary steps to set up their environment for technical writing with AsciiDoc.

{description}

It describes best practices and shows an opinionated approach to make it simple for users new to IntelliJ.

For users already familiar with JetBrains IntelliJ, there's a xref:quick-start.adoc[] documentation.
For advanced installation options, see the page xref:installation.adoc[].

== Why to use IntelliJ for technical writing

The AsciiDoc plugin provides an as-you-type preview, syntax highlighting,  auto-completion and content validation in one plugin.
The IntelliJ IDE offers a great integration with Git and also plugins for spell and grammar checking.

To get a full overview of all features of the plugin, see xref:features.adoc[].

== Steps to set up a writer's environment

Follow these steps to set up IntelliJ IDEA as the tool for technical writing.
Each page gives a brief overview to get started and links to other pages in this guide for additional information.

If the information in the following pages is missing an aspect and leaves questions unanswered, visit the xref:./getting-help.adoc[] page to find more documentation resources and learn where to contact other users of the plugin to collaborate and to get answers to questions.

. xref:./installing-intellij.adoc[Installing IntelliJ IDEA as the workplace for technical writing].
. xref:./starting-intellij-first-time.adoc[Starting IntelliJ IDEA for the first time and installing the AsciiDoc plugin].
. xref:./opening-the-first-project.adoc[Opening the first project in IntelliJ IDEA].
. xref:./editing-an-asciidoc-file.adoc[Adding a file to a project and editing AsciiDoc content in an existing project].
. xref:./navigating-in-a-project.adoc[Navigating from one file to other referenced files in a project].
. xref:./searching-in-a-project.adoc[Searching AsciiDoc content in a project].
. xref:./git-integration.adoc[Collaborate with others using IntelliJ IDEA's Git integration].
. xref:./preparing-a-repository.adoc[Preparing a Git repository for AsciiDoc and IntelliJ to work with a team of technical writers].
. xref:./recommended-plugins.adoc[Enhance a writer's productivity with plugins for IntelliJ].

== Improving this guide

Each of the pages in the guide has an "`Edit this page`" link in the upper right corner.
Use this to edit the content on GitHub.
As an alternative, all content to this guide is hosted in the https://github.com/asciidoctor/asciidoctor-intellij-plugin[Git repository of the AsciiDoc plugin] in the _doc_ folder, so it can be edited in an IDE like any other AsciiDoc content.

If there are missing features, link:mailto:alexander.schwartz@gmx.net?subject=Feedback%20to%20IntelliJ%20Technical%20Setup[contact the maintainer via email] or https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/new/choose[create an issue on GitHub].

== Further reading

To get a full overview of all features of the plugin, see xref:features.adoc[].

To customize the plugin's settings, see xref:recommended-settings.adoc[] for recommended settings.
