= Create a PDF from an AsciiDoc file
:description: Create PDF from an AsciiDoc file directly in your IDE.
:navtitle: Create PDF

{description}

The user can choose _Create PDF from current file_ from the editor's action toolbar to convert the file shown in the current AsciiDoc editor to a PDF using Asciidoctor PDF version 2.1.x.
If creation of the PDF file succeeds, the plugin opens the PDF in the system's PDF viewer.
To find out more how to configure the output and formatting, visit https://asciidoctor.org/docs/asciidoctor-pdf/.

On Windows, users need to close the PDF viewer first to be able to create a new instance of the PDF as the file would otherwise be locked.

== Downloading Asciidoctor PDF support

As of the AsciiDoc Plugin version 0.31.14+, Asciidoctor PDF is no longer included in the plugin as default as it adds approximately 2 MB to the download of the installation and each update.

When creating a PDF for the first time, the plugin will download the necessary dependency.

include::partial$download-dependencies.adoc[]
