= Creating HTML and PDF
:description: Create HTML and PDF from an AsciiDoc file directly from your IDE.
:navtitle: HTML and PDF

{description}

== Creating an HTML file

The user can choose _Create HTML from current file_ from the editor's action toolbar to convert the file to the HTML format.
If creation of the HTML file succeeds, the exported file is opened in the system's default browser.

== Creating a PDF file

The user can choose _Create PDF from current file_ from the editor's action toolbar to convert the file shown in the current AsciiDoc editor to a PDF using Asciidoctor PDF version 1.6.x.
If creation of the PDF file succeeds, the plugin opens the PDF in the system's PDF viewer.
To find out more how to configure the output and formatting, visit https://asciidoctor.org/docs/asciidoctor-pdf/.

=== Downloading Asciidoctor PDF support

As of the AsciiDoc Plugin version 0.31.14+, Asciidoctor PDF is no longer included in the plugin as default as it adds approximately 2 MB to the download of the installation and each update.

When creating a PDF for the first time, the plugin will download the necessary dependency.

include::partial$download-dependencies.adoc[]
