= Live Templates
:description: Live templates provide snippets for common AsciiDoc patterns. They guide authors to structure their documents.

{description}

== Basic Functionality

Once the user types kbd:[a]kbd:[d], a list of templates appears.
Continue typing characters to restrict the list of the template names.
A kbd:[Tab] expands the current entry.

Users can add their own live templates to avoid repetitive typing and to ensure consistency.
Go to menu:File[Settings... > Editor > Live Templates > AsciiDoc] for this configuration.

[#ad-tag-include]
== Special template _ad-tag-include_

=== How the snippet tag include template works

All live templates of this plugin except one will only be available when editing AsciiDoc content. +
One live template is special: **_ad-tag-include_**

This template adds comments with the tag-syntax to your source file that mark snippets to be extracted by AsciiDoc include preprocessor macros later.
Read more in the Asciidoctor user manual in section https://asciidoctor.org/docs/user-manual/#include-partial[_Select Portions of a Document to Include_].

[%collapsible]
.Example showing how snippets work
====

Given the following text file...

.Text file with a marked snippet
[source,asciidoc]
----
Other text
// tag::tagname[]
Some Snippet
// end::tagname[]
more text
----

{empty}... and an AsciiDoc source like the following ...

.AsciiDoc document that includes the snippet
[source,asciidoc]
----
Some text from another file:

\include::text.txt[tag=tagname]
----

{empty}... this produces the following output:

=====
Some text from another file:

Some Snippet
=====

====

=== Using the tag include live template

This live template works in two ways:

Create an empty snippet:: Type _ad-tag-include_ when no text is selected.
+
This creates empty snippets with tag boundaries.
The plugin places the cursor at the tag name.
Once the user has changed the tag name and pressed kbd:[Enter], the plugin places the cursor within the snippet, and the user can start typing the snippet's text.

Create a snippet from existing text::
Selecting a text block, then choose _Surround with..._ (Shortcut kbd:[Ctrl+Alt+T] on Linux/Windows or kbd:[⌘+⌥+T] on macOS) and then choose _ad-tag-include_.
+
This creates the tag boundaries before and after the previously selected text.
The plugin places the cursor at the tag name.
Then the user types the tag name and presses kbd:[Enter].

=== Disabling the tag include live template

If a user doesn't want to see the _ad-tag-include_ live template when typing content in any other language, there are two options to disable it:

Disable this live template completely::
. Go to menu menu:File[Settings... > Editor > Live Templates > AsciiDoc > _ad-tag-include_].
. Uncheck the checkbox to disable this live template.

Choose specific languages for this live template::
. Go to menu menu:File[Settings... > Editor > Live Templates > AsciiDoc].
. Select the entry _ad-tag-include_.
. Choose _Change_ at the end of the line starting with _Applicable in..._ (might need to make the dialog a little wider).
. Select the file types where the live template should appear.
