= Custom stylesheets for the preview
:navtitle: Custom stylesheets
:description: The user can provide custom stylesheets for the preview to make the preview look similar to the live site they publish the content to.

{description}

== Configuring stylesheets

This chapter walks you through the steps to prepare an _.asciidoctorconfig_ file to either replace the stylesheet or to add additional styles to the HTML header.

The _.asciidoctorconfig_ file will configure the preview of all AsciiDoc files in the folder where it is located and this folder's subfolders.
See _xref:features/advanced/asciidoctorconfig-file.adoc[]_ for more details.

WARNING: If the configuration references remote content like fonts or stylesheets, these will require an online connection for the preview to load them.
Therefore, the user will not be able to work off-line anymore.
Consider using a conditional like `ifdef` to provide an attribute for the user to switch off the custom stylesheets when they are offline.

=== Replace default stylesheet

This replaces the standard stylesheet with a custom stylesheet.
You can use local content, or link to a remote stylesheet.

==== Using local project's content

NOTE: The stylesheet will be embedded in the preview, therefore relative links to the local file system will not work.

. Create a file _.asciidoctorconfig_ with the following contents:
+
..asciidoctorconfig
[source,asciidoc]
----
:stylesdir: {asciidoctorconfigdir}/.asciidoctor <1>
:stylesheet: preview-stylesheet.css <2>
----
<.> point to a directory with the stylesheet.
As this uses \{asciidoctorconfigdir}, the folder is relative to the _.asciidoctorconfig_ file.
<.> filename of the stylesheet to be used.

. Place your stylesheet in the _.asciidoctor_ folder:
+
..asciidoctor/preview-stylesheet.css
[source,css]
----
body {
  /* ... */
}
----

[#remote-stylesheet]
==== Using a remote stylesheet

NOTE: This is available from plugin version 0.31.31+.

Once the document or the configuration set the `linkcss` attribute, the preview will link to an external stylesheet and will no longer embed the stylesheet.

Apply the following steps:

. Create a file _.asciidoctorconfig_ with the following contents:
+
..asciidoctorconfig
[source,asciidoc]
----
:linkcss:
:stylesdir: https://example.com/css
:stylesheet: preview-stylesheet.css
----

. Host an external stylesheet +
In the example above, the preview will fetch it from \https://example.com/css/preview-stylesheet.css
+
.preview-stylesheet.css
[source,css]
----
body {
  /* ... */
}
----

The https://github.com/darshandsoni/asciidoctor-skins[asciidoctor-skins] project hosts multiple stylesheets you can link to.
The following example uses a dark skin.

.Dark theme based on the asciidoctor-skins project
[source,asciidoc]
----
:linkcss:
:stylesdir: https://darshandsoni.com/asciidoctor-skins/css
:stylesheet: dark.css
----

=== Add additional styles or HTML headers

This adds additional styles and HTML headers in addition to the default stylesheet.
The chapter https://asciidoctor.org/docs/user-manual/#docinfo-file["`Docinfo Files`" in the Asciidoctor User Manual^] provides more information about this capability.

[NOTE]
====
* The contents will be embedded in the preview, therefore relative links to the local file system will not work.
* Attribute substitution is supported in plugin version 0.31.35+.
To prevent an infinite recursion, substitution is limited to 100 attributes and 20 substitutions per attribute.
====

Follow these steps to enable Docinfo Files:

. Create a file _.asciidoctorconfig_ with the following contents:
+
..asciidoctorconfig
[source,asciidoc]
----
:docinfodir: {asciidoctorconfigdir}/.asciidoctor <1>
:docinfo: shared <2>
----
<.> point to a directory with docinfo files.
As this uses \{asciidoctorconfigdir}, the folder is relative to the _.asciidoctorconfig_ file.
<.> tell the renderer to include the shared docinfo file _docinfo.html_

. Place your _docinfo.html_ in the _.asciidoctor_ folder
+
..asciidoctor/docinfo.html
[source]
----
<style>
body {
  /* ... */
}
</style>
----
