= JCEF Preview
:description: JCEF preview allows the most advanced rich preview of AsciiDoc content.

{description}

[NOTE]
====
This is available from IntelliJ 2020.2+ and plugin version 0.31.x.

Please update to IntelliJ 2020.3+ for best experience, as this fixes some limitations of earlier versions.
====

== Why to use the JCEF preview

The JCEF preview provides better HTML preview and additional features like scroll-to-view and opening links in the browser.
As the preview is based on an up-to-date Google Chrome rendering engine, it offers in-par rendering compared to modern browsers.
This includes rendering of fonts and SVGs.

== Security options

include::partial$content-security-policy.adoc[]

<<devtools,Activate the dev tools for the JCEF preview>> to debug issues where the preview doesn't show content due to CSP.

[[limitations]]
== Limitations of the JCEF preview

When using tool windows in undocked mode, the preview will overlap with the tool window.
See issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/751[#751] for details.
It seems to be rooted in the platform.
All plugins that use the JCEF preview (including JetBrains's Markdown plugin) are affected.
Please vote for the following issues to raise attention for this problem: https://youtrack.jetbrains.com/issue/IDEA-257702[IDEA-257702] and https://youtrack.jetbrains.com/issue/IDEA-252845[IDEA-252845].

The JCEF preview doesn't support the IntelliJ proxy configuration prior to 2021.1.
Configuring a proxy for JCEF requires an IDE restart.
Therefore, remote images in the preview might not show if you are behind a proxy.
See '`xref:faq/jcef-no-proxy-support.adoc[]`' for more information.

Once a JCEF preview is open in a project, it now and then brings the focus to the project when editing files in a different window in IntelliJ 2020.2.
This is fixed in the https://blog.jetbrains.com/idea/2020/11/intellij-idea-2020-2-4/[2020.2.4] and 2020.3 release.
See JetBrains issue https://youtrack.jetbrains.com/issue/IDEA-247541["`JCEF: steals focus from a different frame`"] for more information.

On macOS there is no copy-and-paste from the JCEF preview in IntelliJ 2020.2.
This is fixed in IntelliJ 2020.3 (see issues https://youtrack.jetbrains.com/issue/IDEA-241604/[IDEA-241604] and https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/533[asciidoctor-intellij-plugin/#322]).
As a workaround, open the preview in the browser by clicking on your favorite browser symbol when hovering in the upper right corner of the editor and copy the contents from the browser window.

== Benefits of the JCEF preview

[[devtools]]
JCEF preview is an embedded Chrome browser.
After https://plugins.jetbrains.com/docs/intellij/enabling-internal.html[enabling the internal mode^] users can right-click on the preview and use "`Open DevTools`".
This opens a fully equipped Chrome developer tools window that allows users to inspect the HTML created in the preview and to view the JavaScript console of the preview.

[NOTE]
====
// https://youtrack.jetbrains.com/issue/IDEA-276906
Starting from IntelliJ 2021.3, set the property `ide.browser.jcef.contextMenu.devTools.enabled=true` to enable this feature.

This property is then specific to enable the DevTools, and won't change any other IDE configuration.
====

== When you can use JCEF preview

JCEF preview is only available from IntelliJ 2020.2+ and plugin version 0.31.x.
It requires that the user runs on the pre-packaged JetBrains OpenJDK 11.

[[choose-jdk]]
=== Selecting a different JetBrains JDK using the "`Choose Runtime`" plugin

This is recommended for Android Studio 4.2 and 2020.3+ that doesn't ship with either JavaFX or JCEF support.
You can watch https://issuetracker.google.com/issues/159933628[this issue] in Android Studio's issue tracker for the progress.

JavaFX preview that used to work with Android Studio 4.0 will not work with Android Studio 4.2 as it doesn't package the necessary classes in the IDE.
Therefore, follow these steps to enable JCEF preview for Android Studio.

*For Android Studio 2021.1+:*

* Open menu item menu:Help[Find action...] and search for "`Choose Boot Java runtime for the IDE...`"
* Choose a runtime "`11.0.x...`" labeled "`JetBrains Runtime with JCEF`" and install it.
The IDE will restart.
* Go to the settings of the AsciiDoc plugin and check if the preview is set to "`JCEF Browser`".
Change it to "`JCEF Browser`" if this is not the case.

*For Android Studio 4.2 and 2020.3+:*

* Install the plugin "`Choose Runtime`".
* Open menu item menu:Help[Find action...] and search for "`Choose Runtime...`"
* Choose a runtime "jbrsdk-11_0_...tar.gz" or later and install it.
The IDE will restart.
* Go to the settings of the AsciiDoc plugin and check if the preview is set to "`JCEF Browser`".
Change it to "`JCEF Browser`" if this is not the case.

=== Troubleshooting JCEF

Please follow the https://intellij-support.jetbrains.com/hc/en-us/articles/360016644459-Reporting-JCEF-problems[JetBrains Knowledge Base article on "`Reporting JCEF Problems`"].
