= Highlighting source code
:description: The preview supports different highlighting for source code like Coderay, Rouge and highlight.js.

Source highlighting shows source code listings in a document colored for better readability similar to an IDE.
The preview supports different highlighting for source code like Coderay, Rouge and highlight.js.
The plugin supports this both for the JCEF and the JavaFX preview modes.

== How to use source highlighting

Source highlighting in the preview works best when JCEF or JavaFX are selected in the plugin's settings as the preview browser.

Once a document contains a code block marked with a language that the source highlighter supports, the preview shows it highlighted.

The default highlighter for the plugin's preview is the http://coderay.rubychan.de/[CodeRay source highlighter].
See <<configure-source-highlighters>> for how to set up source highlighting when rendering documents outside the plugin, and to change the source highlighting package to support other languages or different highlighters.

.Source for a minimal code block in the document with language _C_
-----
[source,c]
----
#include<stdio.h>

int main() {
	printf("Hello World\n");
	return 0;
}
----
-----

.Rendered output in the preview with source highlighting
[source,c]
----
#include<stdio.h>

int main() {
	printf("Hello World\n");
	return 0;
}
----

[#configure-source-highlighters]
== Configuring Source Highlighters

The default highlighter for the plugin's preview is the http://coderay.rubychan.de/[CodeRay source highlighter].
To activate source highlighting with CodeRay when rendering documents outside the IDE, set the following attribute in the header of the document:

[source,asciidoc]
----
:source-highlighter: coderay
----

While source highlighters are configurable and pluggable in Asciidoctor, the AsciiDoc plugin for IntelliJ supports only a distinct number of source highlighters.

The following lists the values for the _source-highlighter_ attribute supported by this plugin.

coderay::
The default highlighter for the plugin's preview.
See http://coderay.rubychan.de/[CodeRay source highlighter] for more information.

rouge::
An alternative highlighter.
See http://rouge.jneen.net/[Rouge source highlighter] for more information.

highlight.js::
A syntax highlighter based on JavaScript.
The plugin supports also _highlightjs_ as an alias for the name of the source highlighter.
See https://highlightjs.org/[highlight.js source highlighter] for more information.
+
Support for this highlighter is available since plugin version 0.32.50, earlier versions include only partial support.
The plugin pre-bundles the common languages as listed on https://highlightjs.org/download/[highlight.js' download page] plus AsciiDoc.
+
The plugin supports the attributes _highlightjsdir_, _highlightjs-theme_ and _highlightjs-languages_.
Attributes _highlightjs-theme_ and _highlightjs-languages_ are only supported when a _highlightjsdir_ has been specified, and the necessary files are available.
+
Valid values for the attribute _highlightjsdir_ are:
+
--
* A URL starting with either _http://_ or _https://_,
* a local directory with an absolute path within the current project, or
* a relative directory from the project's root folder.
--
+
An example configuration for a local configuration could look like this: +
+
.Configuration of highlight.js files in the local project
[source,asciidoc]
-----
include::example$highlightjs-highlighting.adoc[]
-----
<.> If the user specifies the attribute _highlightjsdir_, they *must* place the JavaScript bundle and a theme in the current project.
For this example, the JavaScript bundle must be named _/hljs/highlight.min.js_.
See the next item for the theme.
<.> If the user specifies a _highlightjsdir_, they can override the highlighting theme using _highlightjs-theme_.
A CSS file matching the selected theme must be placed in the current project.
If a user does not specify _highlightjs-theme_, the default is _github_ and the user must place the CSS file for the _github_ theme in the _styles_ folder.
For this example, it must be named _/hljs/styles/default.min.css_.
<.> If the user specifies a _highlightjsdir_, the user can specify additional languages for highlighting using _highlightjs-languages_.
This requires a file for each language defined here.
For this example, the user must place _/hljs/languages/basic.min.js_ in the current project.

Users can change the default code highlighter:

* To change this for all documents, configure attribute _source-highlighter_ to the desired value in the plugin's settings.
* To change this for a single document, set the attribute _source-highlighter_ in the document.
* To change this for all documents in a folder or within a project, set the attribute _source-highlighter_ in an xref:features/advanced/asciidoctorconfig-file.adoc[].

== More Information

Read more about https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/[source highlighting in the AsciiDoc documentation].

