= Source highlighting in the preview
:description: The preview supports different highlighting for source code like Coderay, Rouge and hightlight.js.

Source highlighting shows source code listings in a document colored for better readability similar to an IDE.
The preview supports different highlighting for source code like Coderay, Rouge and hightlight.js.
The plugin supports this both for the JCEF and the JavaFX preview modes.

== How to use source highlighting

Source highlighting in the preview works best when JCEF or JavaFX are selected in the plugin's settings as the preview browser.

Once a document contains a code block marked with a language that the source highlighter supports, the preview shows it highlighted.

The default highlighter for the plugin's preview is the http://coderay.rubychan.de/[CodeRay source highlighter].
See <<configure-source-highlighters>> for how to set up source highlighting when rendering documents outside the plugin, and to change the source highlighting package to support other languages or different highlighters.

.Source for a minimal code block in the document with language _C_
-----
[source,c]
----
#include<stdio.h>

int main() {
	printf("Hello World\n");
	return 0;
}
----
-----

.Rendered output in the preview with source highlighting
[source,c]
----
#include<stdio.h>

int main() {
	printf("Hello World\n");
	return 0;
}
----

[#configure-source-highlighters]
== Configuring Source Highlighters

The default highlighter for the plugin's preview is the http://coderay.rubychan.de/[CodeRay source highlighter].
To activate source highlighting with CodeRay when rendering documents outside the IDE, set the following attribute in the header of the document:

[source,asciidoc]
----
:source-highlighter: coderay
----

While source highlighters are configurable and pluggable in Asciidoctor, the AsciiDoc plugin for IntelliJ supports only a distinct number of source highlighters.

The following lists the values for the _source-highlighter_ attribute supported by this plugin.

coderay::
The default highlighter for the plugin's preview.
See http://coderay.rubychan.de/[CodeRay source highlighter] for more information.

rouge::
An alternative highlighter.
See http://rouge.jneen.net/[Rouge source highlighter] for more information.

--
highlight.js::
A syntax highlighter based on JavaScript.
See https://highlightjs.org/[highlight.js source highlighter] for more information.
Support for this highlighter is available from plugin version 0.32.46.
The plugin pre-bundles the common languages as listed on https://highlightjs.org/download/[highlight.js' download page] plus AsciiDoc.
+
The plugin supports also _highlightjs_ as an alias (as of plugin version 0.32.39).
+
The plugin doesn't support the attributes _highlightjsdir_ and _highlightjs-theme_ yet.
--

Users can change the default code highlighter:

* To change this for all documents, configure attribute _source-highlighter_ to the desired value in the plugin's settings.
* To change this for a single document, set the attribute _source-highlighter_ in the document.
* To change this for all documents in a folder or within a project, set the attribute _source-highlighter_ in an xref:features/advanced/asciidoctorconfig-file.adoc[].

== More Information

Read more about https://docs.asciidoctor.org/asciidoc/latest/verbatim/source-highlighter/[source highlighting in the AsciiDoc documentation].

